// Generated by GitHub Copilot

import type { CanonicalType, Ontology } from "../types.js";

/** Resolves relation labels, filters support, and emits an internally valid ontology. */
export function emitOntology(
  canonicalTypes: CanonicalType[],
  documentCount: number,
  candidateCount: number,
  supportThreshold: number,
): Ontology {
  const supportedNodes = canonicalTypes.filter(
    (type) => type.kind === "NodeType" && type.supportCount >= supportThreshold,
  );
  const labelIndex = buildLabelIndex(supportedNodes);
  const nodeIds = new Set(supportedNodes.map(({ id }) => id));
  const emittedNodes = supportedNodes.map((type) => sanitizeParent(type, nodeIds));
  const emittedRelations = canonicalTypes
    .filter((type) => type.kind === "RelType" && type.supportCount >= supportThreshold)
    .map((type) => resolveRelation(type, labelIndex))
    .filter((type): type is CanonicalType => type !== undefined);
  const types = [...emittedNodes, ...emittedRelations].map(cloneCanonicalType);

  return {
    types,
    generatedAt: Date.now(),
    stats: {
      documentCount,
      candidateCount,
      typeCount: types.length,
      droppedBelowThreshold: canonicalTypes.length - types.length,
    },
  };
}

/** Builds a case-insensitive label and alias index for supported nodes. */
function buildLabelIndex(types: CanonicalType[]): Map<string, string> {
  const index = new Map<string, string>();
  for (const type of types) {
    for (const label of [type.label, ...type.aliases]) {
      const key = normalizeLookup(label);
      if (!index.has(key)) {
        index.set(key, type.id);
      }
    }
  }
  return index;
}

/** Removes parent references whose node was filtered from the output. */
function sanitizeParent(type: CanonicalType, nodeIds: Set<string>): CanonicalType {
  const clone = cloneCanonicalType(type);
  if (clone.parent !== undefined && !nodeIds.has(clone.parent)) {
    delete clone.parent;
  }
  sanitizeAttributeReferences(clone);
  return clone;
}

/** Removes entity metadata references that do not identify emitted attributes. */
function sanitizeAttributeReferences(type: CanonicalType): void {
  const names = new Set([
    ...type.attributes,
    ...(type.attributeDefinitions ?? []).map(({ name }) => name),
  ]);
  if (type.primaryKeyAttribute !== undefined && !names.has(type.primaryKeyAttribute)) {
    delete type.primaryKeyAttribute;
  }
  if (type.labelAttribute !== undefined && !names.has(type.labelAttribute)) {
    delete type.labelAttribute;
  }
}

/** Resolves a relation's domain and range labels to emitted canonical ids. */
function resolveRelation(
  type: CanonicalType,
  labelIndex: Map<string, string>,
): CanonicalType | undefined {
  if (type.domain === undefined || type.range === undefined) {
    return undefined;
  }
  const domain = labelIndex.get(normalizeLookup(type.domain));
  const range = labelIndex.get(normalizeLookup(type.range));
  if (domain === undefined || range === undefined) {
    return undefined;
  }
  return { ...cloneCanonicalType(type), domain, range };
}

/** Normalizes labels only for deterministic reference lookup. */
function normalizeLookup(value: string): string {
  return value.trim().replace(/\s+/g, " ").toLocaleLowerCase("en");
}

/** Creates a detached canonical type. */
function cloneCanonicalType(type: CanonicalType): CanonicalType {
  return {
    ...type,
    attributes: [...type.attributes],
    ...(type.attributeDefinitions === undefined
      ? {}
      : { attributeDefinitions: type.attributeDefinitions.map((item) => ({ ...item })) }),
    ...(type.visual === undefined ? {} : { visual: { ...type.visual } }),
    aliases: [...type.aliases],
    provenance: type.provenance.map((item) => ({ ...item })),
  };
}