// Generated by GitHub Copilot

import { deduplicateCandidates } from "../candidates/deduplicate.js";
import { canonicalizeCandidates } from "../canonicalization/canonicalizer.js";
import { splitDocuments } from "../chunking/split-documents.js";
import { resolveConfig } from "../config.js";
import { emitOntology } from "../consolidation/emit-ontology.js";
import { ConcurrentJobError, StoreConflictError } from "../errors.js";
import { extractChunks } from "../extraction/extract-chunks.js";
import { ExtractionJobHandle, type JobContext } from "../job/extraction-job.js";
import type {
  ExtractionJob,
  ExtractedCandidate,
  InputDocument,
  Ontology,
  OntologyExtractorConfig,
  ResolvedOntologyExtractorConfig,
  StoredCandidate,
} from "../types.js";

type PipelineMode = "extract" | "refine" | "consolidate";

/** Coordinates extraction jobs while preserving candidates as the source of truth. */
export class OntologyExtractor {
  readonly #config: ResolvedOntologyExtractorConfig;
  #activeJob: ExtractionJobHandle | undefined;
  #ontology: Ontology = createEmptyOntology();

  /** Creates an extractor with validated dependencies and defaults. */
  constructor(config: OntologyExtractorConfig) {
    this.#config = resolveConfig(config);
  }

  /** Starts a cold extraction and rejects a non-empty store inside the job. */
  extract(documents: InputDocument[]): ExtractionJob {
    return this.#startJob("extract", documents);
  }

  /** Extracts only unseen documents and rebuilds the ontology from all candidates. */
  refine(documents: InputDocument[]): ExtractionJob {
    return this.#startJob("refine", documents);
  }

  /** Rebuilds the ontology without making extraction calls. */
  consolidate(): ExtractionJob {
    return this.#startJob("consolidate", []);
  }

  /** Returns a detached copy of the last successfully published ontology. */
  async getOntology(): Promise<Ontology> {
    return cloneOntology(this.#ontology);
  }

  /** Returns the persisted candidate source layer. */
  async getCandidates(): Promise<StoredCandidate[]> {
    return this.#config.store.getAllCandidates();
  }

  /** Creates and immediately reserves the extractor's single active job slot. */
  #startJob(mode: PipelineMode, documents: InputDocument[]): ExtractionJobHandle {
    if (this.#activeJob !== undefined) {
      throw new ConcurrentJobError("An extraction job is already active");
    }
    const job = new ExtractionJobHandle(documents.length);
    this.#activeJob = job;
    job.start((context) => this.#runPipeline(mode, documents, context));
    void job.completed().then(
      () => this.#releaseJob(job),
      () => this.#releaseJob(job),
    );
    return job;
  }

  /** Runs map, persistence, canonicalization, and atomic ontology publication. */
  async #runPipeline(
    mode: PipelineMode,
    documents: InputDocument[],
    context: JobContext,
  ): Promise<Ontology> {
    const documentIds = await this.#config.store.getDocumentIds();
    if (mode === "extract" && documentIds.length > 0) {
      throw new StoreConflictError("extract requires an empty CandidateStore; use refine instead");
    }
    const unseenDocuments = await this.#selectDocuments(mode, documents);
    if (mode !== "consolidate") {
      await this.#extractAndPersist(unseenDocuments, context);
    }
    return this.#consolidateAndPublish(context);
  }

  /** Filters already processed ids during refinement. */
  async #selectDocuments(
    mode: PipelineMode,
    documents: InputDocument[],
  ): Promise<InputDocument[]> {
    if (mode !== "refine") {
      return documents;
    }
    const checks = await Promise.all(
      documents.map(async (document) => ({
        document,
        exists: await this.#config.store.hasDocument(document.id),
      })),
    );
    return checks.filter(({ exists }) => !exists).map(({ document }) => document);
  }

  /** Extracts a complete batch before persisting any of its documents. */
  async #extractAndPersist(
    documents: InputDocument[],
    context: JobContext,
  ): Promise<void> {
    context.update({ phase: "chunking" });
    const chunks = splitDocuments(documents, this.#config.chunking);
    context.update({ phase: "extracting", chunks: { total: chunks.length, processed: 0 } });
    let processedChunks = 0;
    let rawCandidates = 0;
    let extractionCalls = 0;
    const candidates = await extractChunks(
      chunks,
      this.#config.llm,
      this.#config.extraction,
      context.signal,
      {
        onLlmCall: () => {
          extractionCalls += 1;
          context.update({
            llmCalls: {
              extraction: extractionCalls,
              canonicalization: 0,
            },
          });
        },
        onChunkProcessed: (candidateCount) => {
          processedChunks += 1;
          rawCandidates += candidateCount;
          context.update({
            chunks: { total: chunks.length, processed: processedChunks },
            candidates: { raw: rawCandidates, deduped: 0 },
          });
        },
      },
    );
    await this.#persistBatch(documents, candidates, context);
  }

  /** Persists each document after extraction has completed for the whole batch. */
  async #persistBatch(
    documents: InputDocument[],
    candidates: ExtractedCandidate[],
    context: JobContext,
  ): Promise<void> {
    let processed = 0;
    for (const document of documents) {
      context.signal.throwIfAborted();
      await this.#config.store.appendCandidates(
        document.id,
        candidates.filter((candidate) => candidate.documentId === document.id),
      );
      processed += 1;
      context.update({ documents: { total: documents.length, processed } });
    }
  }

  /** Rebuilds canonicals from the store and publishes only a successful snapshot. */
  async #consolidateAndPublish(context: JobContext): Promise<Ontology> {
    context.update({ phase: "canonicalizing" });
    const storedCandidates = await this.#config.store.getAllCandidates();
    const candidates = deduplicateCandidates(storedCandidates);
    let canonicalizationCalls = 0;
    const canonicalTypes = await canonicalizeCandidates(
      candidates,
      this.#config.embeddings,
      this.#config.llm,
      this.#config.canonicalization,
      context.signal,
      {
        onLlmCall: () => {
          canonicalizationCalls += 1;
          context.update({
            llmCalls: {
              extraction: context.progress.llmCalls.extraction,
              canonicalization: canonicalizationCalls,
            },
          });
        },
        onTypeCount: (canonicalTypesCount) =>
          context.update({ canonicalTypes: canonicalTypesCount }),
      },
    );
    context.update({
      phase: "consolidating",
      candidates: { raw: storedCandidates.length, deduped: candidates.length },
    });
    const documentIds = await this.#config.store.getDocumentIds();
    context.update({ phase: "emitting" });
    const ontology = emitOntology(
      canonicalTypes,
      documentIds.length,
      storedCandidates.length,
      this.#config.output.supportCountThreshold,
    );
    this.#ontology = cloneOntology(ontology);
    return ontology;
  }

  /** Releases the active slot only for the job that currently owns it. */
  #releaseJob(job: ExtractionJobHandle): void {
    if (this.#activeJob === job) {
      this.#activeJob = undefined;
    }
  }
}

/** Creates the initial empty projection returned before the first successful run. */
function createEmptyOntology(): Ontology {
  return {
    types: [],
    generatedAt: 0,
    stats: {
      documentCount: 0,
      candidateCount: 0,
      typeCount: 0,
      droppedBelowThreshold: 0,
    },
  };
}

/** Creates a detached ontology snapshot. */
function cloneOntology(ontology: Ontology): Ontology {
  return {
    ...ontology,
    types: ontology.types.map((type) => ({
      ...type,
      attributes: [...type.attributes],
      ...(type.attributeDefinitions === undefined
        ? {}
        : { attributeDefinitions: type.attributeDefinitions.map((item) => ({ ...item })) }),
      ...(type.visual === undefined ? {} : { visual: { ...type.visual } }),
      aliases: [...type.aliases],
      provenance: type.provenance.map((item) => ({ ...item })),
    })),
    stats: { ...ontology.stats },
  };
}