// Generated by GitHub Copilot

import multipart from "@fastify/multipart";
import Fastify, {
  type FastifyInstance,
  type FastifyRequest,
} from "fastify";
import { readFile } from "node:fs/promises";
import { basename, extname } from "node:path";
import type { InputDocument } from "ontology-extractor";

import { createProviderAdapters, type ProviderAdapters } from "../providers.js";
import { JobRegistry, TooManyJobsError } from "./job-registry.js";
import type { WebRuntimeConfig } from "./runtime-config.js";
import { renderWebPage } from "./web-page.js";

const allowedExtensions = new Set([".txt", ".md", ".markdown", ".html", ".htm"]);
const allowedMimeTypes = new Set([
  "text/plain",
  "text/markdown",
  "text/html",
  "application/octet-stream",
]);

export interface CreateWebAppOptions {
  config: WebRuntimeConfig;
  adapters?: ProviderAdapters;
  webClientUrl?: URL;
}

/** Creates a testable same-origin Fastify application without opening a socket. */
export async function createWebApp(options: CreateWebAppOptions): Promise<FastifyInstance> {
  const app = Fastify({ logger: false, bodyLimit: options.config.maxTotalBytes });
  const adapters = options.adapters ?? createProviderAdapters(options.config.provider);
  const registry = new JobRegistry({
    adapters,
    maxActiveJobs: options.config.maxActiveJobs,
    ttlMs: options.config.jobTtlMs,
    supportCountThreshold: options.config.supportCountThreshold,
    extractionAccuracy: options.config.extractionAccuracy,
  });
  const clientUrl = options.webClientUrl ?? new URL("../web-client.js", import.meta.url);
  await app.register(multipart, {
    limits: {
      files: options.config.maxFiles,
      fileSize: options.config.maxFileBytes,
      parts: options.config.maxFiles,
    },
  });

  app.addHook("onSend", async (request, reply, payload) => {
    reply.header("X-Content-Type-Options", "nosniff");
    reply.header("Referrer-Policy", "no-referrer");
    reply.header("X-Frame-Options", "DENY");
    if (request.url.startsWith("/api/")) {
      reply.header("Cache-Control", "no-store");
    }
    return payload;
  });
  app.addHook("onClose", async () => registry.close());

  app.get("/", async (_request, reply) => reply
    .header("Content-Type", "text/html; charset=utf-8")
    .header(
      "Content-Security-Policy",
      "default-src 'self'; script-src 'self'; style-src 'unsafe-inline'; img-src data:; object-src 'none'; base-uri 'none'; frame-ancestors 'none'",
    )
    .send(renderWebPage()));
  app.get("/web-client.js", async (_request, reply) => reply
    .header("Content-Type", "text/javascript; charset=utf-8")
    .send(await readFile(clientUrl)));
  app.get("/api/config", async () => ({
    provider: adapters.summary,
    limits: {
      maxFiles: options.config.maxFiles,
      maxFileBytes: options.config.maxFileBytes,
      maxTotalBytes: options.config.maxTotalBytes,
    },
  }));

  app.post("/api/jobs", async (request, reply) => {
    const documents = await readUploadedDocuments(request, options.config);
    try {
      const job = registry.start(documents);
      return reply.code(202).send(job);
    } catch (error) {
      if (error instanceof TooManyJobsError) {
        return reply.code(429).send({ error: error.message });
      }
      throw error;
    }
  });
  app.get<{ Params: { id: string } }>("/api/jobs/:id", async (request, reply) => {
    const job = registry.get(request.params.id);
    return job === undefined
      ? reply.code(404).send({ error: "Job not found" })
      : reply.send(job);
  });
  app.get<{ Params: { id: string } }>("/api/jobs/:id/ontology", async (request, reply) => {
    const job = registry.get(request.params.id);
    if (job === undefined) {
      return reply.code(404).send({ error: "Job not found" });
    }
    const ontology = registry.getOntology(request.params.id);
    return ontology === undefined
      ? reply.code(409).send({ error: "Ontology is not ready" })
      : reply.send(ontology);
  });
  app.delete<{ Params: { id: string } }>("/api/jobs/:id", async (request, reply) => {
    return await registry.cancel(request.params.id)
      ? reply.code(202).send({ id: request.params.id, status: "cancelling" })
      : reply.code(409).send({ error: "Job is not running" });
  });
  app.get<{ Params: { id: string } }>("/api/jobs/:id/events", async (request, reply) => {
    const snapshot = registry.get(request.params.id);
    if (snapshot === undefined) {
      return reply.code(404).send({ error: "Job not found" });
    }
    reply.hijack();
    reply.raw.writeHead(200, {
      "Content-Type": "text/event-stream; charset=utf-8",
      "Cache-Control": "no-store",
      Connection: "keep-alive",
      "X-Accel-Buffering": "no",
    });
    const writeEvent = (type: string, data: unknown): void => {
      reply.raw.write(`event: ${type}\ndata: ${JSON.stringify(data)}\n\n`);
    };
    writeEvent("progress", snapshot);
    if (snapshot.status !== "running") {
      if (snapshot.status === "done") {
        writeEvent("done", { id: snapshot.id });
      } else if (snapshot.status === "cancelled") {
        writeEvent("cancelled", { id: snapshot.id });
      } else {
        writeEvent("error", { id: snapshot.id, message: snapshot.error ?? "Ontology extraction failed" });
      }
      reply.raw.end();
      return;
    }
    const unsubscribe = registry.subscribe(request.params.id, (event) => {
      writeEvent(event.type, event.data);
      if (event.type !== "progress") {
        reply.raw.end();
      }
    });
    if (unsubscribe === undefined) {
      reply.raw.end();
      return;
    }
    const heartbeat = setInterval(() => reply.raw.write(": heartbeat\n\n"), 15_000);
    heartbeat.unref();
    reply.raw.on("close", () => {
      clearInterval(heartbeat);
      unsubscribe();
    });
  });

  app.setErrorHandler((error, _request, reply) => {
    const statusCode = isHttpError(error) && error.statusCode >= 400
      ? error.statusCode
      : 500;
    let message = "Invalid request";
    if (statusCode >= 500) {
      message = "Request processing failed";
    } else if (error instanceof Error) {
      message = error.message;
    }
    void reply.code(statusCode).send({ error: message.slice(0, 500) });
  });
  return app;
}

/** Parses and validates the complete multipart upload before starting a job. */
async function readUploadedDocuments(
  request: FastifyRequest,
  config: WebRuntimeConfig,
): Promise<InputDocument[]> {
  const documents: InputDocument[] = [];
  const ids = new Set<string>();
  let totalBytes = 0;
  for await (const part of request.parts()) {
    if (part.type !== "file" || part.fieldname !== "documents") {
      continue;
    }
    const id = basename(part.filename);
    const extension = extname(id).toLocaleLowerCase("en");
    if (!allowedExtensions.has(extension) || !allowedMimeTypes.has(part.mimetype)) {
      throw createHttpError(415, `Unsupported document type: ${id}`);
    }
    if (ids.has(id)) {
      throw createHttpError(400, `Duplicate document filename: ${id}`);
    }
    const content = await part.toBuffer();
    totalBytes += content.byteLength;
    if (totalBytes > config.maxTotalBytes) {
      throw createHttpError(413, "Uploaded documents exceed the total size limit");
    }
    let text: string;
    try {
      text = new TextDecoder("utf-8", { fatal: true }).decode(content);
    } catch {
      throw createHttpError(400, `Document is not valid UTF-8: ${id}`);
    }
    if (text.trim().length === 0) {
      throw createHttpError(400, `Document is empty: ${id}`);
    }
    ids.add(id);
    documents.push({ id, text });
  }
  if (documents.length === 0) {
    throw createHttpError(400, "At least one document is required");
  }
  return documents;
}

/** Creates a minimal Fastify-compatible HTTP error. */
function createHttpError(statusCode: number, message: string): Error & { statusCode: number } {
  return Object.assign(new Error(message), { statusCode });
}

/** Narrows unknown errors carrying an HTTP status code. */
function isHttpError(error: unknown): error is Error & { statusCode: number } {
  return error instanceof Error
    && "statusCode" in error
    && typeof error.statusCode === "number";
}