// Generated by GitHub Copilot

import multipart from "@fastify/multipart";
import Fastify, {
  type FastifyInstance,
  type FastifyRequest,
} from "fastify";
import { readFile } from "node:fs/promises";
import { basename, extname } from "node:path";
import type { InputDocument } from "ontology-extractor";

import {
  convertDocumentToMarkdown,
  supportedDocumentExtensions,
  supportedDocumentMimeTypes,
} from "../document-conversion.js";
import { createProviderAdapters, type ProviderAdapters } from "../providers.js";
import { JobRegistry, TooManyJobsError, type WebExtractorSettings } from "./job-registry.js";
import type { WebRuntimeConfig } from "./runtime-config.js";
import { renderWebPage } from "./web-page.js";

export interface CreateWebAppOptions {
  config: WebRuntimeConfig;
  adapters?: ProviderAdapters;
  webClientUrl?: URL;
}

/** Creates a testable same-origin Fastify application without opening a socket. */
export async function createWebApp(options: CreateWebAppOptions): Promise<FastifyInstance> {
  const app = Fastify({ logger: false, bodyLimit: options.config.maxTotalBytes });
  const adapters = options.adapters ?? createProviderAdapters(options.config.provider);
  const registry = new JobRegistry({
    adapters,
    maxActiveJobs: options.config.maxActiveJobs,
    ttlMs: options.config.jobTtlMs,
    supportCountThreshold: options.config.supportCountThreshold,
    extractionAccuracy: options.config.extractionAccuracy,
  });
  const clientUrl = options.webClientUrl ?? new URL("../web-client.js", import.meta.url);
  await app.register(multipart, {
    limits: {
      files: options.config.maxFiles,
      fileSize: options.config.maxFileBytes,
      parts: options.config.maxFiles + 1,
    },
  });

  app.addHook("onSend", async (request, reply, payload) => {
    reply.header("X-Content-Type-Options", "nosniff");
    reply.header("Referrer-Policy", "no-referrer");
    reply.header("X-Frame-Options", "DENY");
    if (request.url.startsWith("/api/")) {
      reply.header("Cache-Control", "no-store");
    }
    return payload;
  });
  app.addHook("onClose", async () => registry.close());

  app.get("/", async (_request, reply) => reply
    .header("Content-Type", "text/html; charset=utf-8")
    .header(
      "Content-Security-Policy",
      "default-src 'self'; script-src 'self'; style-src 'unsafe-inline'; img-src data:; object-src 'none'; base-uri 'none'; frame-ancestors 'none'",
    )
    .send(renderWebPage()));
  app.get("/web-client.js", async (_request, reply) => reply
    .header("Content-Type", "text/javascript; charset=utf-8")
    .send(await readFile(clientUrl)));
  app.get("/api/config", async () => ({
    provider: adapters.summary,
    limits: {
      maxFiles: options.config.maxFiles,
      maxFileBytes: options.config.maxFileBytes,
      maxTotalBytes: options.config.maxTotalBytes,
    },
    settings: {
      chunking: { strategy: "recursive", chunkSize: 4_000, chunkOverlap: 800 },
      extraction: {
        concurrency: 8,
        accuracy: options.config.extractionAccuracy,
        requireExamples: true,
      },
      canonicalization: {
        topK: 5,
        autoMatchThreshold: 0.92,
        autoNewThreshold: 0.6,
        useLlmForAmbiguous: true,
      },
      output: { supportCountThreshold: options.config.supportCountThreshold },
    },
  }));

  app.post("/api/jobs", async (request, reply) => {
    const { documents, settings } = await readUploadedDocuments(request, options.config);
    try {
      const job = registry.start(documents, settings);
      return reply.code(202).send(job);
    } catch (error) {
      if (error instanceof TooManyJobsError) {
        return reply.code(429).send({ error: error.message });
      }
      throw error;
    }
  });
  app.get<{ Params: { id: string } }>("/api/jobs/:id", async (request, reply) => {
    const job = registry.get(request.params.id);
    return job === undefined
      ? reply.code(404).send({ error: "Job not found" })
      : reply.send(job);
  });
  app.get<{ Params: { id: string } }>("/api/jobs/:id/ontology", async (request, reply) => {
    const job = registry.get(request.params.id);
    if (job === undefined) {
      return reply.code(404).send({ error: "Job not found" });
    }
    const ontology = registry.getOntology(request.params.id);
    return ontology === undefined
      ? reply.code(409).send({ error: "Ontology is not ready" })
      : reply.send(ontology);
  });
  app.delete<{ Params: { id: string } }>("/api/jobs/:id", async (request, reply) => {
    return await registry.cancel(request.params.id)
      ? reply.code(202).send({ id: request.params.id, status: "cancelling" })
      : reply.code(409).send({ error: "Job is not running" });
  });
  app.get<{ Params: { id: string } }>("/api/jobs/:id/events", async (request, reply) => {
    const snapshot = registry.get(request.params.id);
    if (snapshot === undefined) {
      return reply.code(404).send({ error: "Job not found" });
    }
    reply.hijack();
    reply.raw.writeHead(200, {
      "Content-Type": "text/event-stream; charset=utf-8",
      "Cache-Control": "no-store",
      Connection: "keep-alive",
      "X-Accel-Buffering": "no",
    });
    const writeEvent = (type: string, data: unknown): void => {
      reply.raw.write(`event: ${type}\ndata: ${JSON.stringify(data)}\n\n`);
    };
    writeEvent("progress", snapshot);
    if (snapshot.status !== "running") {
      if (snapshot.status === "done") {
        writeEvent("done", { id: snapshot.id });
      } else if (snapshot.status === "cancelled") {
        writeEvent("cancelled", { id: snapshot.id });
      } else {
        writeEvent("error", { id: snapshot.id, message: snapshot.error ?? "Ontology extraction failed" });
      }
      reply.raw.end();
      return;
    }
    const unsubscribe = registry.subscribe(request.params.id, (event) => {
      writeEvent(event.type, event.data);
      if (event.type !== "progress") {
        reply.raw.end();
      }
    });
    if (unsubscribe === undefined) {
      reply.raw.end();
      return;
    }
    const heartbeat = setInterval(() => reply.raw.write(": heartbeat\n\n"), 15_000);
    heartbeat.unref();
    reply.raw.on("close", () => {
      clearInterval(heartbeat);
      unsubscribe();
    });
  });

  app.setErrorHandler((error, _request, reply) => {
    const statusCode = isHttpError(error) && error.statusCode >= 400
      ? error.statusCode
      : 500;
    let message = "Invalid request";
    if (statusCode >= 500) {
      message = "Request processing failed";
    } else if (error instanceof Error) {
      message = error.message;
    }
    void reply.code(statusCode).send({ error: message.slice(0, 500) });
  });
  return app;
}

/** Parses and validates the complete multipart upload before starting a job. */
async function readUploadedDocuments(
  request: FastifyRequest,
  config: WebRuntimeConfig,
): Promise<{ documents: InputDocument[]; settings: WebExtractorSettings }> {
  const documents: InputDocument[] = [];
  const ids = new Set<string>();
  let totalBytes = 0;
  let settings: WebExtractorSettings = {};
  let receivedSettings = false;
  for await (const part of request.parts()) {
    if (part.type === "field" && part.fieldname === "settings") {
      if (receivedSettings) {
        throw createHttpError(400, "Duplicate settings field");
      }
      settings = parseExtractorSettings(part.value);
      receivedSettings = true;
      continue;
    }
    if (part.type !== "file" || part.fieldname !== "documents") {
      continue;
    }
    const id = basename(part.filename);
    const extension = extname(id).toLocaleLowerCase("en");
    if (!supportedDocumentExtensions.has(extension) || !supportedDocumentMimeTypes.has(part.mimetype)) {
      throw createHttpError(415, `Unsupported document type: ${id}`);
    }
    if (ids.has(id)) {
      throw createHttpError(400, `Duplicate document filename: ${id}`);
    }
    const content = await part.toBuffer();
    totalBytes += content.byteLength;
    if (totalBytes > config.maxTotalBytes) {
      throw createHttpError(413, "Uploaded documents exceed the total size limit");
    }
    const text = await convertDocumentToMarkdown(id, content);
    ids.add(id);
    documents.push({ id, text });
  }
  if (documents.length === 0) {
    throw createHttpError(400, "At least one document is required");
  }
  return { documents, settings };
}

/** Parses bounded user-facing extractor settings from the multipart form field. */
function parseExtractorSettings(value: unknown): WebExtractorSettings {
  if (typeof value !== "string") {
    throw createHttpError(400, "Settings must be a JSON string");
  }
  if (value.length > 30_000) {
    throw createHttpError(413, "Settings exceed the size limit");
  }
  let parsed: unknown;
  try {
    parsed = JSON.parse(value);
  } catch {
    throw createHttpError(400, "Settings must contain valid JSON");
  }
  const root = readRecord(parsed, "settings");
  const chunking = readOptionalRecord(root.chunking, "settings.chunking");
  const extraction = readOptionalRecord(root.extraction, "settings.extraction");
  const canonicalization = readOptionalRecord(root.canonicalization, "settings.canonicalization");
  const output = readOptionalRecord(root.output, "settings.output");
  const settings: WebExtractorSettings = {};
  if (chunking !== undefined) {
    settings.chunking = {
      ...(chunking.strategy === undefined ? {} : { strategy: readEnum(chunking.strategy, ["recursive", "markdown", "html"], "settings.chunking.strategy") }),
      ...(chunking.chunkSize === undefined ? {} : { chunkSize: readInteger(chunking.chunkSize, 1, 100_000, "settings.chunking.chunkSize") }),
      ...(chunking.chunkOverlap === undefined ? {} : { chunkOverlap: readInteger(chunking.chunkOverlap, 0, 99_999, "settings.chunking.chunkOverlap") }),
    };
    if (settings.chunking.chunkSize !== undefined
      && settings.chunking.chunkOverlap !== undefined
      && settings.chunking.chunkOverlap >= settings.chunking.chunkSize) {
      throw createHttpError(400, "settings.chunking.chunkOverlap must be smaller than chunkSize");
    }
  }
  if (extraction !== undefined) {
    settings.extraction = {
      ...(extraction.concurrency === undefined ? {} : { concurrency: readInteger(extraction.concurrency, 1, 64, "settings.extraction.concurrency") }),
      ...(extraction.accuracy === undefined ? {} : { accuracy: readEnum(extraction.accuracy, ["low", "medium", "high"], "settings.extraction.accuracy") }),
      ...(extraction.requireExamples === undefined ? {} : { requireExamples: readBoolean(extraction.requireExamples, "settings.extraction.requireExamples") }),
      ...(extraction.systemPrompt === undefined ? {} : { systemPrompt: readPrompt(extraction.systemPrompt, "settings.extraction.systemPrompt") }),
      ...(extraction.prompt === undefined ? {} : { prompt: readPrompt(extraction.prompt, "settings.extraction.prompt") }),
    };
  }
  if (canonicalization !== undefined) {
    settings.canonicalization = {
      ...(canonicalization.topK === undefined ? {} : { topK: readInteger(canonicalization.topK, 1, 50, "settings.canonicalization.topK") }),
      ...(canonicalization.autoMatchThreshold === undefined ? {} : { autoMatchThreshold: readThreshold(canonicalization.autoMatchThreshold, "settings.canonicalization.autoMatchThreshold") }),
      ...(canonicalization.autoNewThreshold === undefined ? {} : { autoNewThreshold: readThreshold(canonicalization.autoNewThreshold, "settings.canonicalization.autoNewThreshold") }),
      ...(canonicalization.useLlmForAmbiguous === undefined ? {} : { useLlmForAmbiguous: readBoolean(canonicalization.useLlmForAmbiguous, "settings.canonicalization.useLlmForAmbiguous") }),
      ...(canonicalization.systemPrompt === undefined ? {} : { systemPrompt: readPrompt(canonicalization.systemPrompt, "settings.canonicalization.systemPrompt") }),
      ...(canonicalization.prompt === undefined ? {} : { prompt: readPrompt(canonicalization.prompt, "settings.canonicalization.prompt") }),
    };
    if (settings.canonicalization.autoNewThreshold !== undefined
      && settings.canonicalization.autoMatchThreshold !== undefined
      && settings.canonicalization.autoNewThreshold >= settings.canonicalization.autoMatchThreshold) {
      throw createHttpError(400, "settings.canonicalization.autoNewThreshold must be smaller than autoMatchThreshold");
    }
  }
  if (output !== undefined) {
    settings.output = {
      ...(output.supportCountThreshold === undefined ? {} : { supportCountThreshold: readInteger(output.supportCountThreshold, 1, 1_000, "settings.output.supportCountThreshold") }),
    };
  }
  return settings;
}

/** Reads an object value without accepting arrays or null. */
function readRecord(value: unknown, path: string): Record<string, unknown> {
  if (value === null || typeof value !== "object" || Array.isArray(value)) {
    throw createHttpError(400, `${path} must be an object`);
  }
  return value as Record<string, unknown>;
}

/** Reads an optional object value without accepting arrays. */
function readOptionalRecord(value: unknown, path: string): Record<string, unknown> | undefined {
  return value === undefined ? undefined : readRecord(value, path);
}

/** Reads one integer from JSON within a server-defined resource bound. */
function readInteger(value: unknown, minimum: number, maximum: number, path: string): number {
  if (typeof value !== "number" || !Number.isInteger(value) || value < minimum || value > maximum) {
    throw createHttpError(400, `${path} must be an integer between ${minimum} and ${maximum}`);
  }
  return value;
}

/** Reads one cosine threshold from JSON. */
function readThreshold(value: unknown, path: string): number {
  if (typeof value !== "number" || !Number.isFinite(value) || value < 0 || value > 1) {
    throw createHttpError(400, `${path} must be between 0 and 1`);
  }
  return value;
}

/** Reads one boolean setting from JSON. */
function readBoolean(value: unknown, path: string): boolean {
  if (typeof value !== "boolean") {
    throw createHttpError(400, `${path} must be a boolean`);
  }
  return value;
}

/** Reads a string enum setting from JSON. */
function readEnum<Value extends string>(value: unknown, allowed: readonly Value[], path: string): Value {
  if (typeof value !== "string" || !allowed.includes(value as Value)) {
    throw createHttpError(400, `${path} must be one of: ${allowed.join(", ")}`);
  }
  return value as Value;
}

/** Reads bounded prompt text without accepting blank overrides. */
function readPrompt(value: unknown, path: string): string {
  if (typeof value !== "string") {
    throw createHttpError(400, `${path} must be a string`);
  }
  const prompt = value.trim();
  if (prompt.length === 0 || prompt.length > 8_000) {
    throw createHttpError(400, `${path} must be between 1 and 8000 characters`);
  }
  return prompt;
}

/** Creates a minimal Fastify-compatible HTTP error. */
function createHttpError(statusCode: number, message: string): Error & { statusCode: number } {
  return Object.assign(new Error(message), { statusCode });
}

/** Narrows unknown errors carrying an HTTP status code. */
function isHttpError(error: unknown): error is Error & { statusCode: number } {
  return error instanceof Error
    && "statusCode" in error
    && typeof error.statusCode === "number";
}