// Generated by GitHub Copilot

import {
  OntologyExtractor,
  type AggregatedCandidate,
  type CanonicalType,
  type ExtractionAccuracy,
  type ExtractionJob,
  type InputDocument,
  type Ontology,
  type Progress,
} from "ontology-extractor";

import type { ProviderAdapters } from "../providers.js";

export type WebJobStatus = "running" | "done" | "error" | "cancelled";

export interface WebJobSnapshot {
  id: string;
  status: WebJobStatus;
  progress: Progress;
  createdAt: number;
  updatedAt: number;
  error?: string;
}

export interface WebExtractorSettings {
  chunking?: {
    strategy?: "recursive" | "markdown" | "html";
    chunkSize?: number;
    chunkOverlap?: number;
  };
  extraction?: {
    concurrency?: number;
    accuracy?: ExtractionAccuracy;
    requireExamples?: boolean;
    systemPrompt?: string;
    prompt?: string;
  };
  canonicalization?: {
    topK?: number;
    autoMatchThreshold?: number;
    autoNewThreshold?: number;
    useLlmForAmbiguous?: boolean;
    systemPrompt?: string;
    prompt?: string;
  };
  output?: {
    supportCountThreshold?: number;
  };
}

export type JobEvent =
  | { type: "progress"; data: WebJobSnapshot }
  | { type: "done"; data: { id: string } }
  | { type: "error"; data: { id: string; message: string } }
  | { type: "cancelled"; data: { id: string } };

interface JobRecord {
  job: ExtractionJob;
  status: WebJobStatus;
  progress: Progress;
  createdAt: number;
  updatedAt: number;
  ontology?: Ontology;
  error?: string;
  listeners: Set<(event: JobEvent) => void>;
}

export interface JobRegistryOptions {
  adapters: ProviderAdapters;
  maxActiveJobs: number;
  ttlMs: number;
  supportCountThreshold: number;
  extractionAccuracy: ExtractionAccuracy;
  now?: () => number;
}

/** Owns isolated extraction jobs and removes terminal results after a bounded TTL. */
export class JobRegistry {
  readonly #records = new Map<string, JobRecord>();
  readonly #options: JobRegistryOptions;
  readonly #now: () => number;
  readonly #cleanupTimer: NodeJS.Timeout;

  /** Starts periodic cleanup without keeping the Node process alive. */
  constructor(options: JobRegistryOptions) {
    this.#options = options;
    this.#now = options.now ?? Date.now;
    this.#cleanupTimer = setInterval(
      () => this.cleanupExpired(),
      Math.min(options.ttlMs, 60_000),
    );
    this.#cleanupTimer.unref();
  }

  /** Starts one isolated extractor and returns its externally safe snapshot. */
  start(documents: InputDocument[], settings: WebExtractorSettings = {}): WebJobSnapshot {
    if (this.activeCount >= this.#options.maxActiveJobs) {
      throw new TooManyJobsError("The server is already processing the maximum number of jobs");
    }
    const extractor = new OntologyExtractor({
      llm: this.#options.adapters.llm,
      embeddings: this.#options.adapters.embeddings,
      ...(settings.chunking === undefined ? {} : { chunking: settings.chunking }),
      extraction: {
        accuracy: settings.extraction?.accuracy ?? this.#options.extractionAccuracy,
        ...(settings.extraction?.concurrency === undefined ? {} : { concurrency: settings.extraction.concurrency }),
        systemPrompt: settings.extraction?.systemPrompt ?? createWebExtractionSystemPrompt(),
        prompt: settings.extraction?.prompt ?? ((chunk) => JSON.stringify({
          documentId: chunk.documentId,
          chunkIndex: chunk.chunkIndex,
          instruction: "Extract only certain ontology entities that are explicitly supported and central to the main subject of this document fragment.",
          text: chunk.text,
        })),
        ...(settings.extraction?.requireExamples === undefined ? {} : { requireExamples: settings.extraction.requireExamples }),
      },
      canonicalization: {
        ...(settings.canonicalization?.topK === undefined ? {} : { topK: settings.canonicalization.topK }),
        ...(settings.canonicalization?.autoMatchThreshold === undefined ? {} : { autoMatchThreshold: settings.canonicalization.autoMatchThreshold }),
        ...(settings.canonicalization?.autoNewThreshold === undefined ? {} : { autoNewThreshold: settings.canonicalization.autoNewThreshold }),
        ...(settings.canonicalization?.useLlmForAmbiguous === undefined ? {} : { useLlmForAmbiguous: settings.canonicalization.useLlmForAmbiguous }),
        systemPrompt: settings.canonicalization?.systemPrompt ?? createWebCanonicalizationSystemPrompt(),
        prompt: settings.canonicalization?.prompt ?? (({ candidate, neighbors }) => createWebCanonicalizationPrompt(candidate, neighbors)),
      },
      output: { supportCountThreshold: settings.output?.supportCountThreshold ?? this.#options.supportCountThreshold },
    });
    const job = extractor.extract(documents);
    const timestamp = this.#now();
    const record: JobRecord = {
      job,
      status: "running",
      progress: job.progress,
      createdAt: timestamp,
      updatedAt: timestamp,
      listeners: new Set(),
    };
    this.#records.set(job.id, record);
    job.on("progress", (progress) => {
      record.progress = progress;
      record.updatedAt = this.#now();
      this.#emit(record, { type: "progress", data: toSnapshot(job.id, record) });
    });
    job.completed().then(
      (ontology) => {
        record.status = "done";
        record.ontology = cloneOntology(ontology);
        record.updatedAt = this.#now();
        this.#emit(record, { type: "done", data: { id: job.id } });
      },
      (error: unknown) => {
        record.status = job.progress.phase === "cancelled" ? "cancelled" : "error";
        record.progress = job.progress;
        record.updatedAt = this.#now();
        record.error = record.status === "cancelled"
          ? "Extraction cancelled"
          : safeErrorMessage(error);
        this.#emit(
          record,
          record.status === "cancelled"
            ? { type: "cancelled", data: { id: job.id } }
            : { type: "error", data: { id: job.id, message: record.error } },
        );
      },
    );
    return toSnapshot(job.id, record);
  }

  /** Returns a detached snapshot or undefined for unknown/expired ids. */
  get(id: string): WebJobSnapshot | undefined {
    const record = this.#records.get(id);
    return record === undefined ? undefined : toSnapshot(id, record);
  }

  /** Returns a detached ontology only after successful completion. */
  getOntology(id: string): Ontology | undefined {
    const ontology = this.#records.get(id)?.ontology;
    return ontology === undefined ? undefined : cloneOntology(ontology);
  }

  /** Subscribes to event-driven updates and returns an idempotent unsubscribe callback. */
  subscribe(id: string, listener: (event: JobEvent) => void): (() => void) | undefined {
    const record = this.#records.get(id);
    if (record === undefined) {
      return undefined;
    }
    record.listeners.add(listener);
    return () => record.listeners.delete(listener);
  }

  /** Requests cooperative cancellation for a running job. */
  async cancel(id: string): Promise<boolean> {
    const record = this.#records.get(id);
    if (record?.status !== "running") {
      return false;
    }
    await record.job.cancel();
    return true;
  }

  /** Removes terminal jobs older than the configured TTL. */
  cleanupExpired(): void {
    const cutoff = this.#now() - this.#options.ttlMs;
    for (const [id, record] of this.#records) {
      if (record.status !== "running" && record.updatedAt <= cutoff) {
        record.listeners.clear();
        this.#records.delete(id);
      }
    }
  }

  /** Cancels active jobs and releases timers/listeners during server shutdown. */
  async close(): Promise<void> {
    clearInterval(this.#cleanupTimer);
    await Promise.all(
      [...this.#records.values()]
        .filter(({ status }) => status === "running")
        .map(({ job }) => job.cancel()),
    );
    for (const record of this.#records.values()) {
      record.listeners.clear();
    }
    this.#records.clear();
  }

  /** Counts only pipelines that can consume provider capacity. */
  get activeCount(): number {
    return [...this.#records.values()].filter(({ status }) => status === "running").length;
  }

  /** Delivers a stable event to each current subscriber. */
  #emit(record: JobRecord, event: JobEvent): void {
    for (const listener of record.listeners) {
      listener(event);
    }
  }
}

export class TooManyJobsError extends Error {}

/** Creates the web demo extraction policy for certain, topic-centered entities. */
function createWebExtractionSystemPrompt(): string {
  return [
    "Extract ontology schema candidates from the document fragment.",
    "Return only entities, relations, and attributes that are explicitly stated or directly entailed by the text.",
    "Keep only candidates that are central to the fragment's main subject; discard incidental mentions, examples, actors, tools, document metadata, and generic terms unless they define the subject itself.",
    "Prefer fewer high-confidence NodeType and RelType candidates over broad recall.",
    "Use NodeType for stable domain concepts and RelType for stable relations between those concepts.",
    "For RelType include domain and range labels only when both endpoints are certain and central.",
    "Never invent identifiers, colors, constraints, cardinalities, synonyms, or implicit process steps.",
    "Keep definitions concise and grounded in the uploaded text.",
    "Include one or two grounding examples for every candidate.",
  ].join(" ");
}

/** Creates the web demo canonicalization policy for conservative merging. */
function createWebCanonicalizationSystemPrompt(): string {
  return [
    "Decide whether an ontology candidate matches, extends, or differs from known types.",
    "Merge only when the candidate and target represent the same certain, central domain concept or relation.",
    "Use SUBTYPE only when the text clearly supports a narrower kind of the target.",
    "Use NEW when the relationship is uncertain, merely related, incidental, or based only on a broad semantic association.",
    "Do not normalize away domain-specific distinctions that matter to the document's main subject.",
  ].join(" ");
}

/** Creates the ambiguous-judgment payload sent to the LLM during canonicalization. */
function createWebCanonicalizationPrompt(
  candidate: AggregatedCandidate,
  neighbors: Array<{ type: CanonicalType; score: number }>,
): string {
  return JSON.stringify({
    instruction: "Classify the candidate as MATCH, SUBTYPE, or NEW using only certain, main-subject ontology meaning.",
    candidate,
    neighbors,
  });
}

/** Creates an API-safe snapshot without exposing extractor or ontology references. */
function toSnapshot(id: string, record: JobRecord): WebJobSnapshot {
  return {
    id,
    status: record.status,
    progress: structuredClone(record.progress),
    createdAt: record.createdAt,
    updatedAt: record.updatedAt,
    ...(record.error === undefined ? {} : { error: record.error }),
  };
}

/** Prevents provider stack traces and arbitrary thrown values from reaching clients. */
function safeErrorMessage(error: unknown): string {
  if (error instanceof Error && error.name === "CancelledError") {
    return "Extraction cancelled";
  }
  const providerMessage = findProviderErrorMessage(error);
  if (providerMessage?.includes("Virtual Network") === true || providerMessage?.includes("cogsvc-vnet") === true) {
    return "Azure OpenAI rejected the request because the resource is restricted to a Virtual Network. Connect from the allowed network or update the Azure OpenAI networking settings.";
  }
  return "Ontology extraction failed";
}

/** Extracts bounded provider error text without exposing stack traces or credentials. */
function findProviderErrorMessage(error: unknown): string | undefined {
  let current = error;
  const messages: string[] = [];
  for (let depth = 0; depth < 4; depth += 1) {
    if (!(current instanceof Error)) {
      break;
    }
    if (current.message.length > 0) {
      messages.push(current.message);
    }
    current = current.cause;
  }
  const message = messages.join(" ").slice(0, 500);
  return message.length === 0 ? undefined : message;
}

/** Creates a detached ontology result for each API consumer. */
function cloneOntology(ontology: Ontology): Ontology {
  return structuredClone(ontology);
}