// Generated by GitHub Copilot

import type { ExtractionAccuracy } from "ontology-extractor";
import type { ProviderName } from "../providers.js";

export interface WebRuntimeConfig {
  provider: ProviderName;
  host: string;
  port: number;
  maxFiles: number;
  maxFileBytes: number;
  maxTotalBytes: number;
  maxActiveJobs: number;
  jobTtlMs: number;
  supportCountThreshold: number;
  extractionAccuracy: ExtractionAccuracy;
}

/** Reads non-secret web settings from environment variables with conservative defaults. */
export function readWebRuntimeConfig(
  environment: NodeJS.ProcessEnv = process.env,
): WebRuntimeConfig {
  return {
    provider: readProvider(environment.ONTOLOGY_PROVIDER ?? "mock"),
    host: environment.ONTOLOGY_HOST?.trim() || "127.0.0.1",
    port: readInteger(environment.ONTOLOGY_PORT, 3_000, 1, 65_535, "ONTOLOGY_PORT"),
    maxFiles: readInteger(environment.ONTOLOGY_MAX_FILES, 20, 1, 100, "ONTOLOGY_MAX_FILES"),
    maxFileBytes: readInteger(
      environment.ONTOLOGY_MAX_FILE_BYTES,
      2 * 1024 * 1024,
      1_024,
      20 * 1024 * 1024,
      "ONTOLOGY_MAX_FILE_BYTES",
    ),
    maxTotalBytes: readInteger(
      environment.ONTOLOGY_MAX_TOTAL_BYTES,
      20 * 1024 * 1024,
      1_024,
      100 * 1024 * 1024,
      "ONTOLOGY_MAX_TOTAL_BYTES",
    ),
    maxActiveJobs: readInteger(
      environment.ONTOLOGY_MAX_ACTIVE_JOBS,
      2,
      1,
      20,
      "ONTOLOGY_MAX_ACTIVE_JOBS",
    ),
    jobTtlMs: readInteger(
      environment.ONTOLOGY_JOB_TTL_MS,
      30 * 60 * 1_000,
      10_000,
      24 * 60 * 60 * 1_000,
      "ONTOLOGY_JOB_TTL_MS",
    ),
    supportCountThreshold: readInteger(
      environment.ONTOLOGY_SUPPORT_THRESHOLD,
      1,
      1,
      1_000,
      "ONTOLOGY_SUPPORT_THRESHOLD",
    ),
    extractionAccuracy: readExtractionAccuracy(
      environment.ONTOLOGY_EXTRACTION_ACCURACY ?? "medium",
    ),
  };
}

/** Validates the configured provider before constructing any SDK clients. */
function readProvider(value: string): ProviderName {
  if (value !== "mock" && value !== "lmstudio" && value !== "azure") {
    throw new Error("ONTOLOGY_PROVIDER must be mock, lmstudio, or azure");
  }
  return value;
}

/** Validates the configured extraction recall/precision preset. */
function readExtractionAccuracy(value: string): ExtractionAccuracy {
  const normalizedValue = value.trim().toLowerCase();
  if (
    normalizedValue !== "low"
    && normalizedValue !== "medium"
    && normalizedValue !== "high"
  ) {
    throw new Error("ONTOLOGY_EXTRACTION_ACCURACY must be low, medium, or high");
  }
  return normalizedValue;
}

/** Reads one bounded integer without accepting partial numeric strings. */
function readInteger(
  rawValue: string | undefined,
  fallback: number,
  minimum: number,
  maximum: number,
  name: string,
): number {
  if (rawValue === undefined || rawValue.trim().length === 0) {
    return fallback;
  }
  const value = Number(rawValue);
  if (!Number.isInteger(value) || value < minimum || value > maximum) {
    throw new Error(`${name} must be an integer between ${minimum} and ${maximum}`);
  }
  return value;
}