// Generated by GitHub Copilot

import type { EmbeddingsInterface } from "@langchain/core/embeddings";
import type { BaseChatModel } from "@langchain/core/language_models/chat_models";
import { HumanMessage, SystemMessage } from "@langchain/core/messages";

import type {
  EmbeddingAdapter,
  JsonSchema,
  LlmAdapter,
} from "../types.js";

export type LangChainStructuredOutputMethod = "jsonSchema" | "functionCalling" | "jsonMode";

export interface LangChainLlmAdapterOptions {
  structuredOutputMethod?: LangChainStructuredOutputMethod;
}

/** Adapts a LangChain chat model supporting structured output to the core port. */
export class LangChainLlmAdapter implements LlmAdapter {
  readonly #model: BaseChatModel;
  readonly #structuredOutputMethod: LangChainStructuredOutputMethod | undefined;

  /** Creates an adapter without importing a concrete model provider. */
  constructor(model: BaseChatModel, options: LangChainLlmAdapterOptions = {}) {
    this.#model = model;
    this.#structuredOutputMethod = options.structuredOutputMethod;
  }

  /** Invokes LangChain structured output while preserving schema and cancellation. */
  async generateStructured<T>(request: {
    system?: string;
    prompt: string;
    schema: JsonSchema;
    signal?: AbortSignal;
  }): Promise<T> {
    request.signal?.throwIfAborted();
    const runnable = this.#model.withStructuredOutput<Record<string, unknown>>(request.schema, {
      name: "ontology_extractor_output",
      ...(this.#structuredOutputMethod === undefined ? {} : { method: this.#structuredOutputMethod }),
    });
    const messages = [
      ...(request.system === undefined
        ? []
        : [new SystemMessage(request.system)]),
      new HumanMessage(this.#createPrompt(request.prompt, request.schema)),
    ];
    const result = await runnable.invoke(
      messages,
      request.signal === undefined ? {} : { signal: request.signal },
    );
    return result as T;
  }

  /** Adds schema guidance when a provider only supports JSON mode structured output. */
  #createPrompt(prompt: string, schema: JsonSchema): string {
    if (this.#structuredOutputMethod !== "jsonMode") {
      return prompt;
    }
    return [
      prompt,
      "Return only a valid JSON object that matches this JSON Schema.",
      JSON.stringify(schema),
    ].join("\n\n");
  }
}

/** Adapts LangChain embeddings with explicit output-dimension validation metadata. */
export class LangChainEmbeddingAdapter implements EmbeddingAdapter {
  readonly dimensions: number;
  readonly #model: EmbeddingsInterface<number[]>;

  /** Creates an adapter with the dimension expected from the configured model. */
  constructor(model: EmbeddingsInterface<number[]>, dimensions: number) {
    if (!Number.isInteger(dimensions) || dimensions <= 0) {
      throw new TypeError("Embedding dimensions must be a positive integer");
    }
    this.#model = model;
    this.dimensions = dimensions;
  }

  /** Embeds documents and rejects promptly when cancellation is requested. */
  async embed(texts: string[], signal?: AbortSignal): Promise<number[][]> {
    signal?.throwIfAborted();
    const promise = this.#model.embedDocuments(texts);
    return signal === undefined ? promise : abortable(promise, signal);
  }
}

/** Races an API promise with cancellation and removes its listener on settlement. */
function abortable<T>(promise: Promise<T>, signal: AbortSignal): Promise<T> {
  return new Promise<T>((resolve, reject) => {
    const abort = (): void => reject(signal.reason ?? new DOMException("Aborted", "AbortError"));
    signal.addEventListener("abort", abort, { once: true });
    void promise.then(resolve, reject).finally(() => {
      signal.removeEventListener("abort", abort);
    });
  });
}