// Generated by GitHub Copilot

import type {
  AttributeDefinition,
  AttributeValueType,
  CanonicalType,
  Cardinality,
  Ontology,
  VisualDefinition,
} from "../types.js";

export type ImportStatus = "ACTIVE" | "INACTIVE";

export interface OntologyImportOptions {
  name: string;
  namespace: string;
  description?: string;
  status?: ImportStatus;
  variables?: ImportVariable[];
}

export interface ImportOntologyMetadata {
  name: string;
  namespace: string;
  description: string;
  status: ImportStatus;
}

export interface ImportCategory {
  ref: string;
  name: string;
}

export interface ImportVariable {
  ref: string;
  name: string;
  type: AttributeValueType;
}

export interface ImportAttribute {
  id: string;
  name: string;
  type: AttributeValueType;
  label: string;
  indexed: boolean;
  required: boolean;
  restricted: boolean;
  description?: string;
}

export interface ImportEntityDefinition {
  type: string;
  attributes: ImportAttribute[];
  description: string;
  pkAttribute: string;
  visual?: VisualDefinition;
  labelAttribute?: string;
  categoryRef?: string;
}

export interface ImportEntity {
  ref: string;
  name: string;
  status: ImportStatus;
  definition: ImportEntityDefinition;
}

export interface ImportRelationshipDefinition {
  attributes: ImportAttribute[];
  description: string;
  visual?: VisualDefinition;
  cardinality?: string;
  fromCardinality?: Cardinality;
  toCardinality?: Cardinality;
}

export interface ImportRelationship {
  ref: string;
  name: string;
  status: ImportStatus;
  fromEntityRef: string;
  toEntityRef: string;
  definition: ImportRelationshipDefinition;
}

export interface OntologyImportModel {
  version: 1;
  ontology: ImportOntologyMetadata;
  categories: ImportCategory[];
  variables: ImportVariable[];
  entities: ImportEntity[];
  relationships: ImportRelationship[];
}

/** Converts the internal draft ontology into the interoperable import model. */
export function toOntologyImportModel(
  ontology: Ontology,
  options: OntologyImportOptions,
): OntologyImportModel {
  const name = requireText(options.name, "options.name");
  const namespace = requireText(options.namespace, "options.namespace");
  const status = options.status ?? "ACTIVE";
  const nodes = ontology.types.filter((type) => type.kind === "NodeType");
  const relations = ontology.types.filter((type) => type.kind === "RelType");
  const entityRefs = assignUniqueRefs(nodes);
  const relationshipRefs = assignUniqueRefs(relations);
  const categories = buildCategories(nodes);
  const categoryRefs = new Map(
    categories.map((category) => [normalizeKey(category.name), category.ref]),
  );

  return {
    version: 1,
    ontology: {
      name,
      namespace,
      description: options.description?.trim() || `Ontology extracted as ${name}.`,
      status,
    },
    categories,
    variables: (options.variables ?? []).map((variable) => ({ ...variable })),
    entities: nodes.map((type) => toImportEntity(type, entityRefs, categoryRefs, status)),
    relationships: relations.flatMap((type) => {
      const relationship = toImportRelationship(
        type,
        entityRefs,
        relationshipRefs.get(type.id) as string,
        status,
      );
      return relationship === undefined ? [] : [relationship];
    }),
  };
}

/** Converts one canonical node into an import entity. */
function toImportEntity(
  type: CanonicalType,
  refs: Map<string, string>,
  categoryRefs: Map<string, string>,
  status: ImportStatus,
): ImportEntity {
  const ref = refs.get(type.id) as string;
  const projectedAttributes = toImportAttributes(type, ref);
  const { attributes, pkAttribute } = ensurePrimaryKey(
    projectedAttributes,
    type.primaryKeyAttribute,
    type.label,
    ref,
  );
  const names = new Set(attributes.map(({ name }) => name));
  const categoryRef = type.category === undefined
    ? undefined
    : categoryRefs.get(normalizeKey(type.category));
  return {
    ref,
    name: type.label,
    status,
    definition: {
      type: type.label,
      attributes,
      description: type.definition,
      pkAttribute,
      ...(type.visual === undefined ? {} : { visual: { ...type.visual } }),
      ...(type.labelAttribute !== undefined && names.has(type.labelAttribute)
        ? { labelAttribute: type.labelAttribute }
        : {}),
      ...(categoryRef === undefined ? {} : { categoryRef }),
    },
  };
}

/** Guarantees an indexed, required attribute referenced by every entity PK. */
function ensurePrimaryKey(
  currentAttributes: ImportAttribute[],
  extractedPrimaryKey: string | undefined,
  entityName: string,
  entityRef: string,
): { attributes: ImportAttribute[]; pkAttribute: string } {
  const attributes = currentAttributes.map((attribute) => ({ ...attribute }));
  const extracted = extractedPrimaryKey === undefined
    ? undefined
    : attributes.find(({ name }) => name === extractedPrimaryKey);
  const primary = extracted
    ?? attributes.find(({ name }) => /(?:^id$|id$)/i.test(name))
    ?? attributes[0];
  if (primary !== undefined) {
    primary.indexed = true;
    primary.required = true;
    return { attributes, pkAttribute: primary.name };
  }

  const name = `${toLowerCamelCase(entityName)}Id`;
  return {
    attributes: [{
      id: deterministicUuid(`${entityRef}:${normalizeKey(name)}`),
      name,
      type: "STRING",
      label: `${humanize(entityName)} ID`,
      indexed: true,
      required: true,
      restricted: false,
    }],
    pkAttribute: name,
  };
}

/** Converts one resolved canonical relation into an import relationship. */
function toImportRelationship(
  type: CanonicalType,
  entityRefs: Map<string, string>,
  ref: string,
  status: ImportStatus,
): ImportRelationship | undefined {
  if (type.domain === undefined || type.range === undefined) return undefined;
  const fromEntityRef = entityRefs.get(type.domain);
  const toEntityRef = entityRefs.get(type.range);
  if (fromEntityRef === undefined || toEntityRef === undefined) return undefined;
  return {
    ref,
    name: type.label,
    status,
    fromEntityRef,
    toEntityRef,
    definition: {
      attributes: toImportAttributes(type, ref),
      description: type.definition,
      ...(type.visual === undefined ? {} : { visual: { ...type.visual } }),
      ...(type.fromCardinality === undefined
        ? {}
        : { fromCardinality: type.fromCardinality }),
      ...(type.toCardinality === undefined ? {} : { toCardinality: type.toCardinality }),
      ...(type.fromCardinality !== undefined && type.toCardinality !== undefined
        ? { cardinality: `${type.fromCardinality} : ${type.toCardinality}` }
        : {}),
    },
  };
}

/** Projects rich and legacy attributes into one deterministic list. */
function toImportAttributes(type: CanonicalType, ownerRef: string): ImportAttribute[] {
  const definitions = new Map<string, AttributeDefinition>();
  for (const definition of type.attributeDefinitions ?? []) {
    definitions.set(normalizeKey(definition.name), { ...definition });
  }
  for (const name of type.attributes) {
    const key = normalizeKey(name);
    if (!definitions.has(key)) definitions.set(key, { name });
  }
  return [...definitions.values()]
    .sort((left, right) => left.name.localeCompare(right.name))
    .map((definition) => ({
      id: deterministicUuid(`${ownerRef}:${normalizeKey(definition.name)}`),
      name: definition.name,
      type: definition.type ?? "STRING",
      label: definition.label ?? humanize(definition.name),
      indexed: definition.indexed ?? false,
      required: definition.required ?? false,
      restricted: definition.restricted ?? false,
      ...(definition.description === undefined
        ? {}
        : { description: definition.description }),
    }));
}

/** Builds deduplicated categories in stable lexical order. */
function buildCategories(types: CanonicalType[]): ImportCategory[] {
  const names = [...new Set(
    types.flatMap((type) => type.category === undefined ? [] : [type.category.trim()]),
  )].filter(Boolean).sort((left, right) => left.localeCompare(right));
  const used = new Set<string>();
  return names.map((name) => ({ ref: reserveSlug(name, used), name }));
}

/** Assigns deterministic collision-safe refs to canonical node ids. */
function assignUniqueRefs(types: CanonicalType[]): Map<string, string> {
  const refs = new Map<string, string>();
  const used = new Set<string>();
  for (const type of types) refs.set(type.id, reserveSlug(type.label, used));
  return refs;
}

/** Reserves a slug by adding a stable numeric suffix when necessary. */
function reserveSlug(value: string, used: Set<string>): string {
  const base = createSlug(value);
  let ref = base;
  let suffix = 2;
  while (used.has(ref)) {
    ref = `${base}-${suffix}`;
    suffix += 1;
  }
  used.add(ref);
  return ref;
}

/** Converts arbitrary labels into lowercase interoperable refs. */
function createSlug(value: string): string {
  const slug = value.normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/([a-z\d])([A-Z])/g, "$1-$2")
    .toLocaleLowerCase("en")
    .replace(/[^a-z\d]+/g, "-")
    .replace(/^-|-$/g, "");
  return slug || "type";
}

/** Converts a code-style attribute name into a readable label. */
function humanize(value: string): string {
  const words = value
    .replace(/([a-z\d])([A-Z])/g, "$1 $2")
    .replace(/[_-]+/g, " ")
    .trim();
  return words.length === 0 ? value : words.charAt(0).toLocaleUpperCase("en") + words.slice(1);
}

/** Converts an entity label into a stable lower-camel identifier prefix. */
function toLowerCamelCase(value: string): string {
  const words = humanize(value).split(/\s+/).filter(Boolean);
  const [first = "entity", ...rest] = words;
  return first.toLocaleLowerCase("en")
    + rest.map((word) => word.charAt(0).toLocaleUpperCase("en") + word.slice(1)).join("");
}

/** Creates a stable UUID-shaped identifier without runtime crypto dependencies. */
function deterministicUuid(value: string): string {
  const parts = [0x811c9dc5, 0x9e3779b9, 0x85ebca6b, 0xc2b2ae35]
    .map((seed) => hash32(value, seed).toString(16).padStart(8, "0"));
  const hex = parts.join("").split("");
  hex[12] = "5";
  hex[16] = "8";
  return `${hex.slice(0, 8).join("")}-${hex.slice(8, 12).join("")}-${hex.slice(12, 16).join("")}-${hex.slice(16, 20).join("")}-${hex.slice(20, 32).join("")}`;
}

/** Computes a deterministic unsigned 32-bit FNV-style hash. */
function hash32(value: string, seed: number): number {
  let hash = seed >>> 0;
  for (const character of value) {
    hash ^= character.codePointAt(0) ?? 0;
    hash = Math.imul(hash, 0x01000193) >>> 0;
  }
  return hash;
}

/** Normalizes names for case-insensitive identity comparisons. */
function normalizeKey(value: string): string {
  return value.trim().replace(/\s+/g, " ").toLocaleLowerCase("en");
}

/** Validates required serializer metadata without accepting whitespace. */
function requireText(value: string, path: string): string {
  if (value.trim().length === 0) throw new TypeError(`${path} must be a non-empty string`);
  return value.trim();
}
