// Generated by GitHub Copilot

import { CancelledError } from "../errors.js";
import type {
  ExtractionJob,
  Ontology,
  Phase,
  Progress,
} from "../types.js";

interface JobEventMap {
  progress: (progress: Progress) => void;
  phase: (phase: Phase) => void;
  error: (error: Error) => void;
  done: (ontology: Ontology) => void;
}

export interface JobContext {
  readonly signal: AbortSignal;
  readonly progress: Progress;

  /** Atomically updates the observable progress snapshot. */
  update(patch: ProgressPatch): void;
}

export type ProgressPatch = Partial<
  Pick<Progress, "documents" | "chunks" | "candidates" | "canonicalTypes" | "llmCalls">
> & { phase?: Phase };

type JobOperation = (context: JobContext) => Promise<Ontology>;

/** Internal implementation of the public non-blocking ExtractionJob contract. */
export class ExtractionJobHandle implements ExtractionJob {
  readonly id = globalThis.crypto.randomUUID();
  readonly #abortController = new AbortController();
  readonly #listeners = new Map<keyof JobEventMap, Set<JobEventMap[keyof JobEventMap]>>();
  readonly #completion: Promise<Ontology>;
  #resolve!: (ontology: Ontology) => void;
  #reject!: (error: Error) => void;
  #progress: Progress;
  #terminal = false;
  #started = false;

  /** Creates an idle job whose work can be scheduled exactly once. */
  constructor(documentCount: number) {
    const now = Date.now();
    this.#progress = {
      phase: "idle",
      documents: { total: documentCount, processed: 0 },
      chunks: { total: 0, processed: 0 },
      candidates: { raw: 0, deduped: 0 },
      canonicalTypes: 0,
      llmCalls: { extraction: 0, canonicalization: 0 },
      startedAt: now,
      updatedAt: now,
    };
    this.#completion = new Promise<Ontology>((resolve, reject) => {
      this.#resolve = resolve;
      this.#reject = reject;
    });
  }

  /** Returns a detached snapshot suitable for synchronous UI polling. */
  get progress(): Progress {
    return cloneProgress(this.#progress);
  }

  /** Registers a typed listener without special-casing the error event. */
  on<Event extends keyof JobEventMap>(
    event: Event,
    callback: JobEventMap[Event],
  ): this {
    const listeners = this.#listeners.get(event) ?? new Set();
    listeners.add(callback);
    this.#listeners.set(event, listeners);
    return this;
  }

  /** Removes a listener when both event and callback match. */
  off(event: string, callback: (...args: never[]) => unknown): this {
    if (isJobEvent(event)) {
      this.#listeners.get(event)?.delete(callback as JobEventMap[typeof event]);
    }
    return this;
  }

  /** Returns the stable completion promise for this job. */
  completed(): Promise<Ontology> {
    return this.#completion;
  }

  /** Aborts adapters and rejects completion with a typed cancellation error. */
  async cancel(): Promise<void> {
    if (this.#terminal) {
      return;
    }
    this.#abortController.abort();
    const error = new CancelledError(`Extraction job cancelled: ${this.id}`);
    this.#finishWithError(error, "cancelled");
  }

  /** Schedules operation execution in a microtask so construction stays non-blocking. */
  start(operation: JobOperation): void {
    if (this.#started) {
      throw new Error("Extraction job can only be started once");
    }
    this.#started = true;
    queueMicrotask(() => void this.#run(operation));
  }

  /** Runs the operation and owns all terminal state transitions. */
  async #run(operation: JobOperation): Promise<void> {
    try {
      const getProgress = (): Progress => this.progress;
      const ontology = await operation({
        signal: this.#abortController.signal,
        get progress() {
          return getProgress();
        },
        update: (patch) => this.#update(patch),
      });
      if (this.#terminal) {
        return;
      }
      this.#update({ phase: "done" });
      this.#terminal = true;
      this.#emit("done", ontology);
      this.#resolve(ontology);
    } catch (error) {
      if (this.#terminal) {
        return;
      }
      const normalized = error instanceof Error ? error : new Error(String(error));
      this.#finishWithError(normalized, "error");
    }
  }

  /** Replaces progress fields as one coherent observable snapshot. */
  #update(patch: ProgressPatch): void {
    if (this.#terminal) {
      return;
    }
    const previousPhase = this.#progress.phase;
    this.#progress = {
      ...this.#progress,
      ...patch,
      updatedAt: Date.now(),
    };
    if (patch.phase !== undefined && patch.phase !== previousPhase) {
      this.#emit("phase", patch.phase);
    }
    this.#emit("progress", this.progress);
  }

  /** Applies a terminal failure or cancellation exactly once. */
  #finishWithError(error: Error, phase: "error" | "cancelled"): void {
    if (this.#terminal) {
      return;
    }
    this.#progress = {
      ...this.#progress,
      phase,
      updatedAt: Date.now(),
      error: { message: error.message, phase },
    };
    this.#terminal = true;
    this.#emit("phase", phase);
    this.#emit("progress", this.progress);
    this.#emit("error", error);
    this.#reject(error);
  }

  /** Delivers an event to a stable copy of its current listeners. */
  #emit<Event extends keyof JobEventMap>(
    event: Event,
    value: Parameters<JobEventMap[Event]>[0],
  ): void {
    for (const listener of this.#listeners.get(event) ?? []) {
      (listener as (value: Parameters<JobEventMap[Event]>[0]) => void)(value);
    }
  }
}

/** Creates a detached deep copy of the small progress value object. */
function cloneProgress(progress: Progress): Progress {
  return {
    ...progress,
    documents: { ...progress.documents },
    chunks: { ...progress.chunks },
    candidates: { ...progress.candidates },
    llmCalls: { ...progress.llmCalls },
    ...(progress.error === undefined ? {} : { error: { ...progress.error } }),
  };
}

/** Narrows arbitrary event names to supported job events. */
function isJobEvent(event: string): event is keyof JobEventMap {
  return ["progress", "phase", "error", "done"].includes(event);
}