// Generated by GitHub Copilot

import { ConfigurationError } from "./errors.js";
import { InMemoryCandidateStore } from "./store/in-memory-candidate-store.js";
import type {
  ExtractionAccuracy,
  OntologyExtractorConfig,
  ResolvedOntologyExtractorConfig,
} from "./types.js";

/** Applies defaults and validates all cross-field configuration invariants. */
export function resolveConfig(
  config: OntologyExtractorConfig,
): ResolvedOntologyExtractorConfig {
  const chunkSize = config.chunking?.chunkSize ?? 4_000;
  const chunkOverlap = config.chunking?.chunkOverlap ?? 800;
  const autoMatchThreshold =
    config.canonicalization?.autoMatchThreshold ?? 0.92;
  const autoNewThreshold = config.canonicalization?.autoNewThreshold ?? 0.6;

  assertPositiveInteger(chunkSize, "chunking.chunkSize");
  assertNonNegativeInteger(chunkOverlap, "chunking.chunkOverlap");
  if (chunkOverlap >= chunkSize) {
    throw new ConfigurationError(
      "chunking.chunkOverlap must be smaller than chunking.chunkSize",
    );
  }

  assertThreshold(autoNewThreshold, "canonicalization.autoNewThreshold");
  assertThreshold(autoMatchThreshold, "canonicalization.autoMatchThreshold");
  if (autoNewThreshold >= autoMatchThreshold) {
    throw new ConfigurationError(
      "canonicalization.autoNewThreshold must be smaller than autoMatchThreshold",
    );
  }

  const concurrency = config.extraction?.concurrency ?? 8;
  const accuracy = config.extraction?.accuracy ?? "medium";
  const topK = config.canonicalization?.topK ?? 5;
  const supportCountThreshold = config.output?.supportCountThreshold ?? 2;
  assertPositiveInteger(concurrency, "extraction.concurrency");
  assertExtractionAccuracy(accuracy, "extraction.accuracy");
  assertPositiveInteger(topK, "canonicalization.topK");
  assertPositiveInteger(supportCountThreshold, "output.supportCountThreshold");
  assertPositiveInteger(config.embeddings.dimensions, "embeddings.dimensions");

  return {
    llm: config.llm,
    embeddings: config.embeddings,
    store: config.store ?? new InMemoryCandidateStore(),
    chunking: {
      strategy: config.chunking?.strategy ?? "recursive",
      chunkSize,
      chunkOverlap,
    },
    extraction: {
      concurrency,
      accuracy,
      ...(config.extraction?.systemPrompt === undefined
        ? {}
        : { systemPrompt: config.extraction.systemPrompt }),
      ...(config.extraction?.prompt === undefined
        ? {}
        : { prompt: config.extraction.prompt }),
      requireExamples: config.extraction?.requireExamples ?? true,
    },
    canonicalization: {
      topK,
      autoMatchThreshold,
      autoNewThreshold,
      useLlmForAmbiguous:
        config.canonicalization?.useLlmForAmbiguous ?? true,
      ...(config.canonicalization?.systemPrompt === undefined
        ? {}
        : { systemPrompt: config.canonicalization.systemPrompt }),
      ...(config.canonicalization?.prompt === undefined
        ? {}
        : { prompt: config.canonicalization.prompt }),
    },
    output: { supportCountThreshold },
  };
}

/** Rejects extraction accuracy presets outside the public contract. */
function assertExtractionAccuracy(
  value: string,
  path: string,
): asserts value is ExtractionAccuracy {
  if (value !== "low" && value !== "medium" && value !== "high") {
    throw new ConfigurationError(`${path} must be low, medium, or high`);
  }
}

/** Rejects values that are not positive integers. */
function assertPositiveInteger(value: number, path: string): void {
  if (!Number.isInteger(value) || value <= 0) {
    throw new ConfigurationError(`${path} must be a positive integer`);
  }
}

/** Rejects values that are not non-negative integers. */
function assertNonNegativeInteger(value: number, path: string): void {
  if (!Number.isInteger(value) || value < 0) {
    throw new ConfigurationError(`${path} must be a non-negative integer`);
  }
}

/** Rejects cosine thresholds outside the inclusive unit interval. */
function assertThreshold(value: number, path: string): void {
  if (!Number.isFinite(value) || value < 0 || value > 1) {
    throw new ConfigurationError(`${path} must be between 0 and 1`);
  }
}