// Generated by GitHub Copilot

export class OntologyExtractorError extends Error {
  /** Creates a typed library error with a stable name. */
  constructor(message: string, options?: ErrorOptions) {
    super(message, options);
    this.name = new.target.name;
  }
}

export class ConcurrentJobError extends OntologyExtractorError {}

export class CancelledError extends OntologyExtractorError {}

export class LlmAdapterError extends OntologyExtractorError {}

export class EmbeddingAdapterError extends OntologyExtractorError {}

export class SchemaValidationError extends OntologyExtractorError {}

export class ConfigurationError extends OntologyExtractorError {}

export class StoreConflictError extends OntologyExtractorError {}