// Generated by GitHub Copilot

export { deduplicateCandidates, normalizeLabel } from "./candidates/deduplicate.js";
export { canonicalizeCandidates } from "./canonicalization/canonicalizer.js";
export type {
  CanonicalizationHooks,
  CanonicalizationOptions,
} from "./canonicalization/canonicalizer.js";
export { cosineSimilarity, selectTopK } from "./canonicalization/similarity.js";
export type { ScoredItem } from "./canonicalization/similarity.js";
export { splitDocuments } from "./chunking/split-documents.js";
export type { ChunkingOptions } from "./chunking/split-documents.js";
export { resolveConfig } from "./config.js";
export {
  CancelledError,
  ConcurrentJobError,
  ConfigurationError,
  EmbeddingAdapterError,
  LlmAdapterError,
  OntologyExtractorError,
  SchemaValidationError,
  StoreConflictError,
} from "./errors.js";
export { InMemoryCandidateStore } from "./store/in-memory-candidate-store.js";
export { ExtractionJobHandle } from "./job/extraction-job.js";
export type { JobContext, ProgressPatch } from "./job/extraction-job.js";
export { OntologyExtractor } from "./pipeline/ontology-extractor.js";
export { toOntologyImportModel } from "./serialization/ontology-import-model.js";
export type {
  ImportAttribute,
  ImportCategory,
  ImportEntity,
  ImportEntityDefinition,
  ImportOntologyMetadata,
  ImportRelationship,
  ImportRelationshipDefinition,
  ImportStatus,
  ImportVariable,
  OntologyImportModel,
  OntologyImportOptions,
} from "./serialization/ontology-import-model.js";
export type {
  AggregatedCandidate,
  AttributeDefinition,
  AttributeValueType,
  Candidate,
  CandidateStore,
  CanonicalizationPrompt,
  CanonicalizationPromptInput,
  CanonicalType,
  Cardinality,
  DocumentChunk,
  EmbeddingAdapter,
  ExtractionAccuracy,
  ExtractionJob,
  ExtractionPrompt,
  ExtractedCandidate,
  InputDocument,
  JsonSchema,
  LlmAdapter,
  Ontology,
  OntologyExtractorConfig,
  Phase,
  Progress,
  Provenance,
  ResolvedOntologyExtractorConfig,
  StoredCandidate,
  TypeKind,
  VisualDefinition,
} from "./types.js";