// Generated by GitHub Copilot

export type TypeKind = "NodeType" | "RelType";

export type AttributeValueType =
  | "STRING"
  | "NUMBER"
  | "FLOAT"
  | "BOOLEAN"
  | "DATE"
  | "DATETIME";

export type Cardinality = "0" | "1" | "N";

export interface AttributeDefinition {
  name: string;
  type?: AttributeValueType;
  label?: string;
  description?: string;
  indexed?: boolean;
  required?: boolean;
  restricted?: boolean;
}

export interface VisualDefinition {
  icon?: string;
  backColor?: string;
  textColor?: string;
}

export interface InputDocument {
  id: string;
  text: string;
  metadata?: Record<string, unknown>;
}

export interface Candidate {
  label: string;
  definition: string;
  kind: TypeKind;
  domain?: string;
  range?: string;
  attributes?: string[];
  attributeDefinitions?: AttributeDefinition[];
  category?: string;
  primaryKeyAttribute?: string;
  labelAttribute?: string;
  fromCardinality?: Cardinality;
  toCardinality?: Cardinality;
  visual?: VisualDefinition;
  examples?: string[];
}

export interface ExtractedCandidate extends Candidate {
  documentId: string;
  chunkIndex: number;
}

export interface StoredCandidate extends ExtractedCandidate {
  supportCount: number;
}

export interface DocumentChunk {
  documentId: string;
  chunkIndex: number;
  text: string;
}

export interface AggregatedCandidate extends Candidate {
  supportCount: number;
  provenance: Provenance[];
}

export interface Provenance {
  documentId: string;
  chunkIndex: number;
}

export type ExtractionPrompt = string | ((chunk: DocumentChunk) => string);

export interface CanonicalizationPromptInput {
  candidate: AggregatedCandidate;
  neighbors: Array<{ type: CanonicalType; score: number }>;
}

export type CanonicalizationPrompt =
  | string
  | ((input: CanonicalizationPromptInput) => string);

export interface CanonicalType {
  id: string;
  label: string;
  definition: string;
  kind: TypeKind;
  domain?: string;
  range?: string;
  parent?: string;
  attributes: string[];
  attributeDefinitions?: AttributeDefinition[];
  category?: string;
  primaryKeyAttribute?: string;
  labelAttribute?: string;
  fromCardinality?: Cardinality;
  toCardinality?: Cardinality;
  visual?: VisualDefinition;
  aliases: string[];
  supportCount: number;
  provenance: Provenance[];
}

export interface Ontology {
  types: CanonicalType[];
  generatedAt: number;
  stats: {
    documentCount: number;
    candidateCount: number;
    typeCount: number;
    droppedBelowThreshold: number;
  };
}

export type Phase =
  | "idle"
  | "chunking"
  | "extracting"
  | "canonicalizing"
  | "consolidating"
  | "emitting"
  | "done"
  | "error"
  | "cancelled";

export interface Progress {
  phase: Phase;
  documents: { total: number; processed: number };
  chunks: { total: number; processed: number };
  candidates: { raw: number; deduped: number };
  canonicalTypes: number;
  llmCalls: { extraction: number; canonicalization: number };
  startedAt: number;
  updatedAt: number;
  error?: { message: string; phase: Phase };
}

export interface ExtractionJob {
  readonly id: string;
  readonly progress: Progress;

  /** Registers a typed job event listener. */
  on(event: "progress", callback: (progress: Progress) => void): this;
  on(event: "phase", callback: (phase: Phase) => void): this;
  on(event: "error", callback: (error: Error) => void): this;
  on(event: "done", callback: (ontology: Ontology) => void): this;

  /** Removes a previously registered listener. */
  off(event: string, callback: (...args: never[]) => unknown): this;

  /** Resolves with the final ontology or rejects on failure/cancellation. */
  completed(): Promise<Ontology>;

  /** Requests cooperative cancellation of in-flight adapter work. */
  cancel(): Promise<void>;
}

export type JsonSchema = Record<string, unknown>;

export interface LlmAdapter {
  /** Generates a provider-validated structured response. */
  generateStructured<T>(request: {
    system?: string;
    prompt: string;
    schema: JsonSchema;
    signal?: AbortSignal;
  }): Promise<T>;
}

export interface EmbeddingAdapter {
  readonly dimensions: number;

  /** Embeds each input text while preserving its position. */
  embed(texts: string[], signal?: AbortSignal): Promise<number[][]>;
}

export interface CandidateStore {
  /** Reports whether a document has already been processed. */
  hasDocument(documentId: string): Promise<boolean>;

  /** Atomically records a document and all candidates extracted from it. */
  appendCandidates(
    documentId: string,
    candidates: ExtractedCandidate[],
  ): Promise<void>;

  /** Returns all processed document ids, including documents without candidates. */
  getDocumentIds(): Promise<string[]>;

  /** Returns a detached snapshot of all stored candidates. */
  getAllCandidates(): Promise<StoredCandidate[]>;

  /** Removes a document and all of its candidates. */
  removeDocument(documentId: string): Promise<void>;

  /** Removes every document and candidate. */
  clear(): Promise<void>;
}

export type ExtractionAccuracy = "low" | "medium" | "high";

export interface OntologyExtractorConfig {
  llm: LlmAdapter;
  embeddings: EmbeddingAdapter;
  store?: CandidateStore;
  chunking?: {
    strategy?: "recursive" | "markdown" | "html";
    chunkSize?: number;
    chunkOverlap?: number;
  };
  extraction?: {
    concurrency?: number;
    systemPrompt?: string;
    prompt?: ExtractionPrompt;
    accuracy?: ExtractionAccuracy;
    requireExamples?: boolean;
  };
  canonicalization?: {
    topK?: number;
    autoMatchThreshold?: number;
    autoNewThreshold?: number;
    useLlmForAmbiguous?: boolean;
    systemPrompt?: string;
    prompt?: CanonicalizationPrompt;
  };
  output?: {
    supportCountThreshold?: number;
  };
}

export interface ResolvedOntologyExtractorConfig {
  llm: LlmAdapter;
  embeddings: EmbeddingAdapter;
  store: CandidateStore;
  chunking: {
    strategy: "recursive" | "markdown" | "html";
    chunkSize: number;
    chunkOverlap: number;
  };
  extraction: {
    concurrency: number;
    systemPrompt?: string;
    prompt?: ExtractionPrompt;
    accuracy: ExtractionAccuracy;
    requireExamples: boolean;
  };
  canonicalization: {
    topK: number;
    autoMatchThreshold: number;
    autoNewThreshold: number;
    useLlmForAmbiguous: boolean;
    systemPrompt?: string;
    prompt?: CanonicalizationPrompt;
  };
  output: {
    supportCountThreshold: number;
  };
}