// Generated by GitHub Copilot

import { defineConfig } from "@playwright/test";

export default defineConfig({
  testDir: "./e2e",
  fullyParallel: false,
  forbidOnly: true,
  retries: 0,
  reporter: "line",
  webServer: {
    command: "ONTOLOGY_PROVIDER=mock ONTOLOGY_PORT=3210 node dist/server.js",
    url: "http://127.0.0.1:3210/api/config",
    reuseExistingServer: false,
  },
  use: {
    baseURL: "http://127.0.0.1:3210",
    browserName: "chromium",
    headless: true,
    screenshot: "only-on-failure",
  },
});