// Generated by GitHub Copilot

import type {
  AggregatedCandidate,
  AttributeDefinition,
  Provenance,
  StoredCandidate,
} from "../types.js";

interface MutableAggregate extends AggregatedCandidate {
  attributes: string[];
  provenanceKeys: Set<string>;
}

/** Collapses equal kind/label candidates and counts unique chunk provenance. */
export function deduplicateCandidates(
  candidates: StoredCandidate[],
): AggregatedCandidate[] {
  const aggregates = new Map<string, MutableAggregate>();

  for (const candidate of candidates) {
    const label = normalizeLabel(candidate.label);
    const key = `${candidate.kind}:${label.toLocaleLowerCase("en")}`;
    const provenance = {
      documentId: candidate.documentId,
      chunkIndex: candidate.chunkIndex,
    };
    const provenanceKey = toProvenanceKey(provenance);
    const existing = aggregates.get(key);

    if (existing) {
      mergeIntoAggregate(existing, candidate, provenance, provenanceKey);
      continue;
    }

    aggregates.set(key, createAggregate(candidate, label, provenance, provenanceKey));
  }

  return [...aggregates.values()]
    .sort((left, right) =>
      `${left.kind}:${left.label}`.localeCompare(`${right.kind}:${right.label}`),
    )
    .map(({ provenanceKeys: _provenanceKeys, ...candidate }) => candidate);
}

/** Creates the first mutable aggregate from one detached stored candidate. */
function createAggregate(
  candidate: StoredCandidate,
  label: string,
  provenance: Provenance,
  provenanceKey: string,
): MutableAggregate {
  const {
    documentId: _documentId,
    chunkIndex: _chunkIndex,
    supportCount: _supportCount,
    ...candidateFields
  } = candidate;
  return {
    ...candidateFields,
    label,
    definition: candidate.definition.trim(),
    ...(candidate.domain === undefined ? {} : { domain: normalizeLabel(candidate.domain) }),
    ...(candidate.range === undefined ? {} : { range: normalizeLabel(candidate.range) }),
    attributes: mergeStrings([], candidate.attributes),
    ...(candidate.attributeDefinitions === undefined
      ? {}
      : { attributeDefinitions: mergeAttributeDefinitions([], candidate.attributeDefinitions) }),
    ...(candidate.visual === undefined ? {} : { visual: { ...candidate.visual } }),
    ...(candidate.examples === undefined
      ? {}
      : { examples: mergeStrings([], candidate.examples) }),
    supportCount: 1,
    provenance: [provenance],
    provenanceKeys: new Set([provenanceKey]),
  };
}

/** Merges one stored candidate into an existing mutable aggregate. */
function mergeIntoAggregate(
  existing: MutableAggregate,
  candidate: StoredCandidate,
  provenance: Provenance,
  provenanceKey: string,
): void {
  existing.attributes = mergeStrings(existing.attributes, candidate.attributes);
  const attributeDefinitions = mergeAttributeDefinitions(
    existing.attributeDefinitions ?? [],
    candidate.attributeDefinitions ?? [],
  );
  if (attributeDefinitions.length > 0) {
    existing.attributeDefinitions = attributeDefinitions;
  }
  mergeCandidateMetadata(existing, candidate);
  const examples = mergeOptionalStrings(existing.examples, candidate.examples);
  if (examples === undefined) {
    delete existing.examples;
  } else {
    existing.examples = examples;
  }
  if (!existing.provenanceKeys.has(provenanceKey)) {
    existing.provenance.push(provenance);
    existing.provenanceKeys.add(provenanceKey);
    existing.supportCount += 1;
  }
}

/** Completes optional aggregate metadata from another supporting candidate. */
function mergeCandidateMetadata(
  existing: MutableAggregate,
  candidate: StoredCandidate,
): void {
  if (existing.category === undefined && candidate.category !== undefined) {
    existing.category = candidate.category;
  }
  if (existing.primaryKeyAttribute === undefined && candidate.primaryKeyAttribute !== undefined) {
    existing.primaryKeyAttribute = candidate.primaryKeyAttribute;
  }
  if (existing.labelAttribute === undefined && candidate.labelAttribute !== undefined) {
    existing.labelAttribute = candidate.labelAttribute;
  }
  if (existing.fromCardinality === undefined && candidate.fromCardinality !== undefined) {
    existing.fromCardinality = candidate.fromCardinality;
  }
  if (existing.toCardinality === undefined && candidate.toCardinality !== undefined) {
    existing.toCardinality = candidate.toCardinality;
  }
  const visual = mergeDefinedFields(existing.visual, candidate.visual);
  if (visual !== undefined) existing.visual = visual;
}

/** Trims and collapses whitespace in ontology labels. */
export function normalizeLabel(label: string): string {
  return label.trim().replace(/\s+/g, " ");
}

/** Creates a collision-safe key for one provenance location. */
function toProvenanceKey(provenance: Provenance): string {
  return JSON.stringify([provenance.documentId, provenance.chunkIndex]);
}

/** Merges strings deterministically after trimming duplicates. */
function mergeStrings(current: string[], additions?: string[]): string[] {
  return [...new Set([...current, ...(additions ?? [])].map((value) => value.trim()))]
    .filter((value) => value.length > 0)
    .sort((left, right) => left.localeCompare(right));
}

/** Merges attributes by normalized name while retaining the first known value. */
function mergeAttributeDefinitions(
  current: AttributeDefinition[],
  additions: AttributeDefinition[],
): AttributeDefinition[] {
  const merged = new Map<string, AttributeDefinition>();
  for (const definition of [...current, ...additions]) {
    const key = normalizeLabel(definition.name).toLocaleLowerCase("en");
    const previous = merged.get(key);
    merged.set(key, mergeDefinedFields(previous, definition) ?? { ...definition });
  }
  return [...merged.values()].sort((left, right) => left.name.localeCompare(right.name));
}

/** Completes missing object fields without replacing established values. */
function mergeDefinedFields<Value extends object>(
  current: Value | undefined,
  addition: Value | undefined,
): Value | undefined {
  if (current === undefined) return addition === undefined ? undefined : { ...addition };
  if (addition === undefined) return { ...current };
  const result = { ...addition, ...current };
  return result;
}

/** Preserves optionality while merging example strings. */
function mergeOptionalStrings(
  current: string[] | undefined,
  additions: string[] | undefined,
): string[] | undefined {
  const merged = mergeStrings(current ?? [], additions);
  return merged.length === 0 ? undefined : merged;
}