// Generated by GitHub Copilot

import {
  EmbeddingAdapterError,
  LlmAdapterError,
  SchemaValidationError,
} from "../errors.js";
import type {
  AggregatedCandidate,
  CanonicalizationPrompt,
  CanonicalType,
  EmbeddingAdapter,
  JsonSchema,
  LlmAdapter,
  Provenance,
} from "../types.js";
import { cosineSimilarity, selectTopK } from "./similarity.js";

export interface CanonicalizationOptions {
  topK: number;
  autoMatchThreshold: number;
  autoNewThreshold: number;
  useLlmForAmbiguous: boolean;
  systemPrompt?: string;
  prompt?: CanonicalizationPrompt;
}

export interface CanonicalizationHooks {
  /** Reports each ambiguous judgment sent to the LLM. */
  onLlmCall?(): void;
  /** Reports the current canonical type count. */
  onTypeCount?(count: number): void;
}

interface RegistryEntry {
  type: CanonicalType;
  embedding: number[];
}

interface CanonicalizationVerdict {
  verdict: "MATCH" | "NEW" | "SUBTYPE";
  targetId?: string;
}

const verdictSchema: JsonSchema = {
  type: "object",
  additionalProperties: false,
  required: ["verdict"],
  properties: {
    verdict: { type: "string", enum: ["MATCH", "NEW", "SUBTYPE"] },
    targetId: { type: "string" },
  },
};

/** Canonicalizes candidates serially using embedding gates before LLM judgment. */
export async function canonicalizeCandidates(
  candidates: AggregatedCandidate[],
  embeddings: EmbeddingAdapter,
  llm: LlmAdapter,
  options: CanonicalizationOptions,
  signal?: AbortSignal,
  hooks: CanonicalizationHooks = {},
): Promise<CanonicalType[]> {
  const registry: RegistryEntry[] = [];
  const ordered = [...candidates].sort((left, right) =>
    `${left.kind}:${left.label}`.localeCompare(`${right.kind}:${right.label}`),
  );

  for (const candidate of ordered) {
    signal?.throwIfAborted();
    const embedding = await embedCandidate(candidate, embeddings, signal);
    const neighbors = selectTopK(
      registry.filter((entry) => entry.type.kind === candidate.kind),
      (entry) => cosineSimilarity(embedding, entry.embedding),
      (entry) => entry.type.id,
      options.topK,
    );
    const best = neighbors[0];

    if (best === undefined || best.score < options.autoNewThreshold) {
      addCanonical(registry, candidate, embedding, hooks);
      continue;
    }
    if (best.score >= options.autoMatchThreshold) {
      mergeCandidate(best.item.type, candidate);
      continue;
    }
    if (!options.useLlmForAmbiguous) {
      addCanonical(registry, candidate, embedding, hooks);
      continue;
    }

    hooks.onLlmCall?.();
    const verdict = await requestVerdict(candidate, neighbors, llm, options, signal);
    applyVerdict(verdict, neighbors, registry, candidate, embedding, hooks);
  }

  return registry.map(({ type }) => cloneCanonicalType(type));
}

/** Embeds one candidate and validates adapter cardinality and dimensions. */
async function embedCandidate(
  candidate: AggregatedCandidate,
  embeddings: EmbeddingAdapter,
  signal?: AbortSignal,
): Promise<number[]> {
  let vectors: number[][];
  try {
    vectors = await embeddings.embed(
      [`${candidate.label} — ${candidate.definition}`],
      signal,
    );
  } catch (error) {
    throw new EmbeddingAdapterError("Embedding adapter failed", { cause: error });
  }
  const vector = vectors.length === 1 ? vectors[0] : undefined;
  if (vector?.length !== embeddings.dimensions) {
    throw new EmbeddingAdapterError(
      `Embedding adapter returned an invalid vector shape; expected 1x${embeddings.dimensions}`,
    );
  }
  cosineSimilarity(vector, vector);
  return [...vector];
}

/** Requests and validates an LLM verdict against the supplied neighbor ids. */
async function requestVerdict(
  candidate: AggregatedCandidate,
  neighbors: Array<{ item: RegistryEntry; score: number }>,
  llm: LlmAdapter,
  options: Pick<CanonicalizationOptions, "systemPrompt" | "prompt">,
  signal?: AbortSignal,
): Promise<CanonicalizationVerdict> {
  let result: unknown;
  try {
    result = await llm.generateStructured<unknown>({
      system: options.systemPrompt
        ?? "Decide whether an ontology candidate matches, extends, or differs from known types.",
      prompt: createCanonicalizationPrompt(candidate, neighbors, options.prompt),
      schema: verdictSchema,
      ...(signal === undefined ? {} : { signal }),
    });
  } catch (error) {
    throw new LlmAdapterError("LLM canonicalization judgment failed", { cause: error });
  }
  return validateVerdict(result, new Set(neighbors.map(({ item }) => item.type.id)));
}

/** Builds the user prompt for one ambiguous canonicalization judgment. */
function createCanonicalizationPrompt(
  candidate: AggregatedCandidate,
  neighbors: Array<{ item: RegistryEntry; score: number }>,
  prompt: CanonicalizationPrompt | undefined,
): string {
  const publicNeighbors = neighbors.map(({ item, score }) => ({ type: item.type, score }));
  if (typeof prompt === "function") {
    return prompt({ candidate, neighbors: publicNeighbors });
  }
  if (prompt !== undefined) {
    return prompt;
  }
  return JSON.stringify({ candidate, neighbors: publicNeighbors });
}

/** Validates verdict shape and prevents references outside the supplied top-K. */
function validateVerdict(result: unknown, allowedIds: Set<string>): CanonicalizationVerdict {
  if (!isRecord(result) || !["MATCH", "NEW", "SUBTYPE"].includes(String(result.verdict))) {
    throw new SchemaValidationError("Invalid canonicalization verdict");
  }
  const verdict = result.verdict as CanonicalizationVerdict["verdict"];
  if (verdict === "NEW") {
    return { verdict };
  }
  if (typeof result.targetId !== "string" || !allowedIds.has(result.targetId)) {
    throw new SchemaValidationError("Verdict targetId must reference a supplied neighbor");
  }
  return { verdict, targetId: result.targetId };
}

/** Applies a validated verdict to the single-writer registry. */
function applyVerdict(
  verdict: CanonicalizationVerdict,
  neighbors: Array<{ item: RegistryEntry; score: number }>,
  registry: RegistryEntry[],
  candidate: AggregatedCandidate,
  embedding: number[],
  hooks: CanonicalizationHooks,
): void {
  if (verdict.verdict === "NEW") {
    addCanonical(registry, candidate, embedding, hooks);
    return;
  }
  const target = neighbors.find(({ item }) => item.type.id === verdict.targetId)?.item.type;
  if (target === undefined) {
    throw new SchemaValidationError("Canonicalization target disappeared from registry");
  }
  if (verdict.verdict === "MATCH") {
    mergeCandidate(target, candidate);
    return;
  }
  addCanonical(registry, candidate, embedding, hooks, target.id);
}

/** Adds one canonical type with a deterministic projection-local id. */
function addCanonical(
  registry: RegistryEntry[],
  candidate: AggregatedCandidate,
  embedding: number[],
  hooks: CanonicalizationHooks,
  parent?: string,
): void {
  const id = `type-${String(registry.length + 1).padStart(4, "0")}`;
  registry.push({ type: candidateToCanonical(candidate, id, parent), embedding });
  hooks.onTypeCount?.(registry.length);
}

/** Converts one aggregate into a detached canonical type. */
function candidateToCanonical(
  candidate: AggregatedCandidate,
  id: string,
  parent?: string,
): CanonicalType {
  return {
    id,
    label: candidate.label,
    definition: candidate.definition,
    kind: candidate.kind,
    ...(candidate.domain === undefined ? {} : { domain: candidate.domain }),
    ...(candidate.range === undefined ? {} : { range: candidate.range }),
    ...(parent === undefined ? {} : { parent }),
    attributes: [...(candidate.attributes ?? [])],
    ...(candidate.attributeDefinitions === undefined
      ? {}
      : { attributeDefinitions: candidate.attributeDefinitions.map((item) => ({ ...item })) }),
    ...(candidate.category === undefined ? {} : { category: candidate.category }),
    ...(candidate.primaryKeyAttribute === undefined
      ? {}
      : { primaryKeyAttribute: candidate.primaryKeyAttribute }),
    ...(candidate.labelAttribute === undefined
      ? {}
      : { labelAttribute: candidate.labelAttribute }),
    ...(candidate.fromCardinality === undefined
      ? {}
      : { fromCardinality: candidate.fromCardinality }),
    ...(candidate.toCardinality === undefined
      ? {}
      : { toCardinality: candidate.toCardinality }),
    ...(candidate.visual === undefined ? {} : { visual: { ...candidate.visual } }),
    aliases: [],
    supportCount: candidate.supportCount,
    provenance: candidate.provenance.map((item) => ({ ...item })),
  };
}

/** Merges support and descriptive fields without double-counting provenance. */
function mergeCandidate(target: CanonicalType, candidate: AggregatedCandidate): void {
  if (candidate.label !== target.label && !target.aliases.includes(candidate.label)) {
    target.aliases.push(candidate.label);
    target.aliases.sort((left, right) => left.localeCompare(right));
  }
  target.attributes = mergeStrings(target.attributes, candidate.attributes ?? []);
  target.attributeDefinitions = mergeAttributeDefinitions(
    target.attributeDefinitions ?? [],
    candidate.attributeDefinitions ?? [],
  );
  if (target.category === undefined && candidate.category !== undefined) {
    target.category = candidate.category;
  }
  if (target.primaryKeyAttribute === undefined && candidate.primaryKeyAttribute !== undefined) {
    target.primaryKeyAttribute = candidate.primaryKeyAttribute;
  }
  if (target.labelAttribute === undefined && candidate.labelAttribute !== undefined) {
    target.labelAttribute = candidate.labelAttribute;
  }
  if (target.fromCardinality === undefined && candidate.fromCardinality !== undefined) {
    target.fromCardinality = candidate.fromCardinality;
  }
  if (target.toCardinality === undefined && candidate.toCardinality !== undefined) {
    target.toCardinality = candidate.toCardinality;
  }
  if (target.visual !== undefined || candidate.visual !== undefined) {
    target.visual = { ...candidate.visual, ...target.visual };
  }
  const keys = new Set(target.provenance.map(toProvenanceKey));
  for (const provenance of candidate.provenance) {
    const key = toProvenanceKey(provenance);
    if (!keys.has(key)) {
      target.provenance.push({ ...provenance });
      keys.add(key);
    }
  }
  target.supportCount = target.provenance.length;
}

/** Merges unique strings in deterministic lexical order. */
function mergeStrings(left: string[], right: string[]): string[] {
  return [...new Set([...left, ...right])].sort((a, b) => a.localeCompare(b));
}

/** Merges structured attributes by case-insensitive name. */
function mergeAttributeDefinitions(
  left: NonNullable<CanonicalType["attributeDefinitions"]>,
  right: NonNullable<CanonicalType["attributeDefinitions"]>,
): NonNullable<CanonicalType["attributeDefinitions"]> {
  const merged = new Map<string, (typeof left)[number]>();
  for (const definition of [...left, ...right]) {
    const key = definition.name.trim().toLocaleLowerCase("en");
    merged.set(key, { ...definition, ...merged.get(key) });
  }
  return [...merged.values()].sort((a, b) => a.name.localeCompare(b.name));
}

/** Creates a collision-safe provenance identity. */
function toProvenanceKey(provenance: Provenance): string {
  return JSON.stringify([provenance.documentId, provenance.chunkIndex]);
}

/** Creates a detached canonical type result. */
function cloneCanonicalType(type: CanonicalType): CanonicalType {
  return {
    ...type,
    attributes: [...type.attributes],
    ...(type.attributeDefinitions === undefined
      ? {}
      : { attributeDefinitions: type.attributeDefinitions.map((item) => ({ ...item })) }),
    ...(type.visual === undefined ? {} : { visual: { ...type.visual } }),
    aliases: [...type.aliases],
    provenance: type.provenance.map((item) => ({ ...item })),
  };
}

/** Narrows unknown JSON values to records. */
function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}