// Generated by GitHub Copilot

import { EmbeddingAdapterError } from "../errors.js";

export interface ScoredItem<T> {
  item: T;
  score: number;
}

/** Computes cosine similarity after validating vector shape and values. */
export function cosineSimilarity(left: number[], right: number[]): number {
  if (left.length === 0 || left.length !== right.length) {
    throw new EmbeddingAdapterError("Embedding vectors must have equal non-zero dimensions");
  }

  let dotProduct = 0;
  let leftMagnitude = 0;
  let rightMagnitude = 0;
  for (let index = 0; index < left.length; index += 1) {
    const leftValue = left[index];
    const rightValue = right[index];
    if (leftValue === undefined || rightValue === undefined) {
      throw new EmbeddingAdapterError("Embedding vector dimensions are inconsistent");
    }
    if (!Number.isFinite(leftValue) || !Number.isFinite(rightValue)) {
      throw new EmbeddingAdapterError("Embedding vectors must contain finite numbers");
    }
    dotProduct += leftValue * rightValue;
    leftMagnitude += leftValue * leftValue;
    rightMagnitude += rightValue * rightValue;
  }

  if (leftMagnitude === 0 || rightMagnitude === 0) {
    throw new EmbeddingAdapterError("Embedding vectors must not be zero vectors");
  }
  return dotProduct / Math.sqrt(leftMagnitude * rightMagnitude);
}

/** Selects the highest-scoring items with a stable key-based tie break. */
export function selectTopK<T>(
  items: T[],
  score: (item: T) => number,
  stableKey: (item: T) => string,
  limit: number,
): ScoredItem<T>[] {
  return items
    .map((item) => ({ item, score: score(item) }))
    .sort((left, right) =>
      right.score - left.score || stableKey(left.item).localeCompare(stableKey(right.item)),
    )
    .slice(0, limit);
}