// Generated by GitHub Copilot

import { describe, expect, it } from "vitest";

import { createProviderAdapters } from "../src/providers.js";

describe("createProviderAdapters", () => {
  it("creates the offline mock provider without environment configuration", () => {
    const adapters = createProviderAdapters("mock", {});

    expect(adapters.summary).toEqual({
      provider: "mock",
      chatModel: "deterministic-demo",
      embeddingModel: "trigram-hash-32",
    });
    expect(adapters.embeddings.dimensions).toBe(32);
  });

  it("validates LM Studio model names and dimensions without making network calls", () => {
    expect(() => createProviderAdapters("lmstudio", {})).toThrow(
      "LMSTUDIO_CHAT_MODEL",
    );

    const adapters = createProviderAdapters("lmstudio", {
      LMSTUDIO_CHAT_MODEL: "local-chat",
      LMSTUDIO_EMBEDDING_MODEL: "local-embedding",
      ONTOLOGY_EMBEDDING_DIMENSIONS: "768",
    });
    expect(adapters.summary).toEqual({
      provider: "lmstudio",
      chatModel: "local-chat",
      embeddingModel: "local-embedding",
    });
    expect(adapters.embeddings.dimensions).toBe(768);
  });

  it("requires Azure credentials without including secret values in errors", () => {
    const secret = "super-secret-value";

    expect(() =>
      createProviderAdapters("azure", { AZURE_OPENAI_API_KEY: secret }),
    ).toThrow("AZURE_OPENAI_ENDPOINT");
    try {
      createProviderAdapters("azure", { AZURE_OPENAI_API_KEY: secret });
    } catch (error) {
      expect(String(error)).not.toContain(secret);
    }
  });

  it("accepts a canonical Azure endpoint for chat and embeddings", () => {
    const adapters = createProviderAdapters("azure", {
      AZURE_OPENAI_API_KEY: "test-only-key",
      AZURE_OPENAI_ENDPOINT: "https://ontology-resource.openai.azure.com/",
      AZURE_OPENAI_CHAT_DEPLOYMENT: "chat-deployment",
      AZURE_OPENAI_EMBEDDING_DEPLOYMENT: "embedding-deployment",
      ONTOLOGY_EMBEDDING_DIMENSIONS: "3",
    });

    expect(adapters.summary).toEqual({
      provider: "azure",
      chatModel: "chat-deployment",
      embeddingModel: "embedding-deployment",
    });
    expect(adapters.embeddings.dimensions).toBe(3);
  });
});