// Generated by GitHub Copilot

import { describe, expect, it } from "vitest";

import { renderReport } from "../src/report.js";

describe("renderReport", () => {
  it("escapes ontology content and embeds a restrictive CSP", () => {
    const html = renderReport(
      {
        types: [
          {
            id: "type-1",
            label: "<script>alert(1)</script>",
            definition: "Untrusted & document-derived text.",
            kind: "NodeType",
            attributes: [],
            aliases: [],
            supportCount: 1,
            provenance: [],
          },
        ],
        generatedAt: 1,
        stats: {
          documentCount: 1,
          candidateCount: 1,
          typeCount: 1,
          droppedBelowThreshold: 0,
        },
      },
      "Demo <report>",
    );

    expect(html).toContain("default-src 'none'");
    expect(html).toContain("script-src 'self'");
    expect(html).toContain("Demo &lt;report&gt;");
    expect(html).toContain("&lt;script&gt;alert(1)&lt;/script&gt;");
    expect(html).not.toContain("<script>alert(1)</script>");
    expect(html).toContain("\\u003cscript>alert(1)\\u003c/script>");
    expect(html).toContain('id="ontology-graph" role="img"');
    expect(html).toContain('id="graph-search" type="search"');
    expect(html).toContain('id="support-filter" type="range"');
    expect(html).toContain('src="./report-client.js"');
    expect(html).not.toMatch(/(?:src|href)="https?:/);
  });
});