// Generated by GitHub Copilot

import { afterEach, describe, expect, it } from "vitest";
import type { FastifyInstance } from "fastify";
import type { LlmAdapter } from "ontology-extractor";

import { DemoEmbeddingAdapter, DemoLlmAdapter } from "../src/mock-adapters.js";
import { createWebApp } from "../src/web/app.js";
import {
  readWebRuntimeConfig,
  type WebRuntimeConfig,
} from "../src/web/runtime-config.js";

const config: WebRuntimeConfig = {
  provider: "mock",
  host: "127.0.0.1",
  port: 3_000,
  maxFiles: 3,
  maxFileBytes: 2_048,
  maxTotalBytes: 4_096,
  maxActiveJobs: 2,
  jobTtlMs: 60_000,
  supportCountThreshold: 1,
  extractionAccuracy: "medium",
};

const adapters = {
  llm: new DemoLlmAdapter(),
  embeddings: new DemoEmbeddingAdapter(),
  summary: {
    provider: "mock" as const,
    chatModel: "test-chat",
    embeddingModel: "test-embedding",
  },
};

let app: FastifyInstance | undefined;

afterEach(async () => {
  await app?.close();
  app = undefined;
});

describe("web application API", () => {
  it("serves a secured application shell and non-sensitive config", async () => {
    app = await createWebApp({ config, adapters });

    const page = await app.inject({ method: "GET", url: "/" });
    const runtime = await app.inject({ method: "GET", url: "/api/config" });

    expect(page.statusCode).toBe(200);
    expect(page.body).toContain("Ontology Workbench");
    expect(page.body).toContain("Download");
    expect(page.body).toContain("Extractor settings");
    expect(page.body).toContain("SOP example");
    expect(page.headers["content-security-policy"]).toContain("default-src 'self'");
    expect(page.headers["x-content-type-options"]).toBe("nosniff");
    expect(runtime.headers["cache-control"]).toBe("no-store");
    expect(runtime.json()).toEqual({
      provider: adapters.summary,
      limits: {
        maxFiles: 3,
        maxFileBytes: 2_048,
        maxTotalBytes: 4_096,
      },
      settings: {
        chunking: { strategy: "recursive", chunkSize: 4_000, chunkOverlap: 800 },
        extraction: { concurrency: 8, accuracy: "medium", requireExamples: true },
        canonicalization: {
          topK: 5,
          autoMatchThreshold: 0.92,
          autoNewThreshold: 0.6,
          useLlmForAmbiguous: true,
        },
        output: { supportCountThreshold: 1 },
      },
    });
  });

  it("extracts uploaded documents and exposes the final ontology", async () => {
    app = await createWebApp({ config, adapters });
    const upload = createMultipart([
      {
        filename: "architecture.md",
        mimeType: "text/markdown",
        text: "The billing service exposes an API and uses a database.",
      },
    ]);

    const created = await app.inject({
      method: "POST",
      url: "/api/jobs",
      headers: { "content-type": upload.contentType },
      payload: upload.payload,
    });

    expect(created.statusCode).toBe(202);
    const id = created.json<{ id: string }>().id;
    const status = await waitForTerminalJob(app, id);
    expect(status.status).toBe("done");

    const result = await app.inject({ method: "GET", url: `/api/jobs/${id}/ontology` });
    expect(result.statusCode).toBe(200);
    expect(result.json<{ types: Array<{ label: string }> }>().types.map(({ label }) => label))
      .toEqual(["API", "Database", "Service", "exposes", "uses"]);
  });

  it("passes the configured high extraction accuracy to ontology jobs", async () => {
    let request!: Parameters<LlmAdapter["generateStructured"]>[0];
    const capturingLlm: LlmAdapter = {
      async generateStructured<T>(nextRequest: Parameters<LlmAdapter["generateStructured"]>[0]): Promise<T> {
        request = nextRequest;
        return { candidates: [] } as T;
      },
    };
    app = await createWebApp({
      config: { ...config, extractionAccuracy: "high" },
      adapters: { ...adapters, llm: capturingLlm },
    });
    const upload = createMultipart([
      { filename: "architecture.md", mimeType: "text/markdown", text: "service database api" },
    ]);

    const created = await app.inject({
      method: "POST",
      url: "/api/jobs",
      headers: { "content-type": upload.contentType },
      payload: upload.payload,
    });
    const id = created.json<{ id: string }>().id;
    await waitForTerminalJob(app, id);

    expect(created.statusCode).toBe(202);
    expect(request.system).toContain("central to the fragment's main subject");
    expect(request.system).toContain("Prefer fewer high-confidence NodeType and RelType candidates");
    expect(request.prompt).toContain("Extract only certain ontology entities");
    expect(request.schema).toMatchObject({
      properties: {
        candidates: {
          maxItems: 4,
        },
      },
    });
  });

  it("passes per-job extractor settings and prompt overrides to ontology jobs", async () => {
    let request!: Parameters<LlmAdapter["generateStructured"]>[0];
    const capturingLlm: LlmAdapter = {
      async generateStructured<T>(nextRequest: Parameters<LlmAdapter["generateStructured"]>[0]): Promise<T> {
        request = nextRequest;
        return { candidates: [] } as T;
      },
    };
    app = await createWebApp({
      config,
      adapters: { ...adapters, llm: capturingLlm },
    });
    const upload = createMultipart([
      { filename: "architecture.md", mimeType: "text/markdown", text: "service database api" },
    ], {
      settings: JSON.stringify({
        chunking: { chunkSize: 64, chunkOverlap: 0 },
        extraction: {
          accuracy: "low",
          concurrency: 1,
          requireExamples: false,
          systemPrompt: "Custom extraction system prompt",
          prompt: "Custom extraction prompt",
        },
        output: { supportCountThreshold: 1 },
      }),
    });

    const created = await app.inject({
      method: "POST",
      url: "/api/jobs",
      headers: { "content-type": upload.contentType },
      payload: upload.payload,
    });
    const id = created.json<{ id: string }>().id;
    await waitForTerminalJob(app, id);

    expect(created.statusCode).toBe(202);
    expect(request.system).toBe("Custom extraction system prompt");
    expect(request.prompt).toBe("Custom extraction prompt");
    expect(request.schema).toMatchObject({
      properties: { candidates: { maxItems: 12 } },
    });
  });

  it("rejects invalid per-job extractor settings", async () => {
    app = await createWebApp({ config, adapters });
    const upload = createMultipart([
      { filename: "architecture.md", mimeType: "text/markdown", text: "service database api" },
    ], {
      settings: JSON.stringify({
        chunking: { chunkSize: 100, chunkOverlap: 100 },
      }),
    });

    const response = await app.inject({
      method: "POST",
      url: "/api/jobs",
      headers: { "content-type": upload.contentType },
      payload: upload.payload,
    });

    expect(response.statusCode).toBe(400);
    expect(response.json<{ error: string }>().error).toContain("chunkOverlap");
  });

  it("converts uploaded PDF files to Markdown before extraction", async () => {
    let request!: Parameters<LlmAdapter["generateStructured"]>[0];
    const capturingLlm: LlmAdapter = {
      async generateStructured<T>(nextRequest: Parameters<LlmAdapter["generateStructured"]>[0]): Promise<T> {
        request = nextRequest;
        return { candidates: [] } as T;
      },
    };
    app = await createWebApp({
      config,
      adapters: { ...adapters, llm: capturingLlm },
    });
    const upload = createMultipart([
      {
        filename: "architecture.pdf",
        mimeType: "application/pdf",
        content: createSimplePdf("The billing service exposes an API."),
      },
    ]);

    const created = await app.inject({
      method: "POST",
      url: "/api/jobs",
      headers: { "content-type": upload.contentType },
      payload: upload.payload,
    });
    const id = created.json<{ id: string }>().id;
    await waitForTerminalJob(app, id);

    expect(created.statusCode).toBe(202);
    expect(request.prompt).toContain("# architecture.pdf converted from PDF");
    expect(request.prompt).toContain("## Page 1");
    expect(request.prompt).toContain("billing service exposes an API");
  });

  it("passes custom canonicalization prompts to ambiguous ontology judgments", async () => {
    let extractionIndex = 0;
    let canonicalizationRequest!: Parameters<LlmAdapter["generateStructured"]>[0];
    const capturingLlm: LlmAdapter = {
      async generateStructured<T>(request: Parameters<LlmAdapter["generateStructured"]>[0]): Promise<T> {
        const required = Array.isArray(request.schema.required) ? request.schema.required : [];
        if (required.includes("candidates")) {
          extractionIndex += 1;
          return {
            candidates: [
              {
                label: extractionIndex === 1 ? "Application" : "Software Application",
                definition: "A deployed software system.",
                kind: "NodeType",
                examples: ["Billing"],
              },
            ],
          } as T;
        }
        canonicalizationRequest = request;
        return { verdict: "MATCH", targetId: "type-0001" } as T;
      },
    };
    const ambiguousEmbeddings = {
      dimensions: 2,
      async embed(texts: string[]): Promise<number[][]> {
        return texts.map((text) =>
          text.startsWith("Application") ? [1, 0] : [0.7, 0.7],
        );
      },
    };
    app = await createWebApp({
      config,
      adapters: { ...adapters, llm: capturingLlm, embeddings: ambiguousEmbeddings },
    });
    const upload = createMultipart([
      { filename: "one.md", mimeType: "text/markdown", text: "application" },
      { filename: "two.md", mimeType: "text/markdown", text: "software application" },
    ]);

    const created = await app.inject({
      method: "POST",
      url: "/api/jobs",
      headers: { "content-type": upload.contentType },
      payload: upload.payload,
    });
    const id = created.json<{ id: string }>().id;
    await waitForTerminalJob(app, id);

    expect(created.statusCode).toBe(202);
    expect(canonicalizationRequest.system).toContain("same certain, central domain concept");
    expect(canonicalizationRequest.prompt).toContain("main-subject ontology meaning");
    expect(canonicalizationRequest.prompt).toContain("Software Application");
    expect(canonicalizationRequest.prompt).toContain("Application");
  });

  it("rejects unsupported, duplicate, and missing documents", async () => {
    app = await createWebApp({ config, adapters });
    const unsupported = createMultipart([
      { filename: "document.docx", mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document", text: "zip" },
    ]);
    const duplicate = createMultipart([
      { filename: "same.md", mimeType: "text/markdown", text: "service" },
      { filename: "same.md", mimeType: "text/markdown", text: "api" },
    ]);

    const unsupportedResponse = await app.inject({
      method: "POST",
      url: "/api/jobs",
      headers: { "content-type": unsupported.contentType },
      payload: unsupported.payload,
    });
    const duplicateResponse = await app.inject({
      method: "POST",
      url: "/api/jobs",
      headers: { "content-type": duplicate.contentType },
      payload: duplicate.payload,
    });
    const missingResponse = await app.inject({
      method: "POST",
      url: "/api/jobs",
      headers: { "content-type": "multipart/form-data; boundary=empty" },
      payload: Buffer.from("--empty--\r\n"),
    });

    expect(unsupportedResponse.statusCode).toBe(415);
    expect(duplicateResponse.statusCode).toBe(400);
    expect(missingResponse.statusCode).toBe(400);
  });

  it("limits concurrent jobs and supports cooperative cancellation", async () => {
    const slowLlm: LlmAdapter = {
      async generateStructured<T>({ signal }): Promise<T> {
        return new Promise<T>((_resolve, reject) => {
          const abort = (): void => reject(signal?.reason ?? new DOMException("Aborted", "AbortError"));
          signal?.addEventListener("abort", abort, { once: true });
        });
      },
    };
    app = await createWebApp({
      config: { ...config, maxActiveJobs: 1 },
      adapters: { ...adapters, llm: slowLlm },
    });
    const upload = createMultipart([
      { filename: "architecture.md", mimeType: "text/markdown", text: "service" },
    ]);

    const first = await app.inject({
      method: "POST",
      url: "/api/jobs",
      headers: { "content-type": upload.contentType },
      payload: upload.payload,
    });
    const second = await app.inject({
      method: "POST",
      url: "/api/jobs",
      headers: { "content-type": upload.contentType },
      payload: upload.payload,
    });
    const id = first.json<{ id: string }>().id;
    const cancelled = await app.inject({ method: "DELETE", url: `/api/jobs/${id}` });
    const status = await waitForTerminalJob(app, id);

    expect(first.statusCode).toBe(202);
    expect(second.statusCode).toBe(429);
    expect(cancelled.statusCode).toBe(202);
    expect(status.status).toBe("cancelled");
  });

  it("returns an actionable Azure networking error when the provider is blocked by VNet rules", async () => {
    const blockedLlm: LlmAdapter = {
      async generateStructured<T>(): Promise<T> {
        throw new Error(
          "403 A Virtual Network is configured for this resource. Please use the correct endpoint for making requests. Check https://aka.ms/cogsvc-vnet for more details.",
        );
      },
    };
    app = await createWebApp({
      config,
      adapters: { ...adapters, llm: blockedLlm },
    });
    const upload = createMultipart([
      { filename: "architecture.md", mimeType: "text/markdown", text: "service database api" },
    ]);

    const created = await app.inject({
      method: "POST",
      url: "/api/jobs",
      headers: { "content-type": upload.contentType },
      payload: upload.payload,
    });
    const id = created.json<{ id: string }>().id;
    const status = await waitForTerminalJob(app, id) as { status: string; error?: string };

    expect(status.status).toBe("error");
    expect(status.error).toContain("restricted to a Virtual Network");
  });
});

describe("web runtime config", () => {
  it("reads and validates the extraction accuracy preset", () => {
    expect(readWebRuntimeConfig({}).extractionAccuracy).toBe("medium");
    expect(readWebRuntimeConfig({ ONTOLOGY_EXTRACTION_ACCURACY: "HIGH" }).extractionAccuracy)
      .toBe("high");
    expect(() => readWebRuntimeConfig({ ONTOLOGY_EXTRACTION_ACCURACY: "strict" }))
      .toThrow("ONTOLOGY_EXTRACTION_ACCURACY must be low, medium, or high");
  });
});

interface UploadFile {
  filename: string;
  mimeType: string;
  text?: string;
  content?: Buffer;
}

/** Builds a small deterministic multipart body without adding a test-only runtime dependency. */
function createMultipart(files: UploadFile[], fields: Record<string, string> = {}): { contentType: string; payload: Buffer } {
  const boundary = "ontology-test-boundary";
  const fieldChunks = Object.entries(fields).map(([name, value]) => [
    `--${boundary}\r\n`,
    `Content-Disposition: form-data; name="${name}"\r\n\r\n`,
    value,
    "\r\n",
  ]);
  const chunks = files.map((file) => [
    `--${boundary}\r\n`,
    `Content-Disposition: form-data; name="documents"; filename="${file.filename}"\r\n`,
    `Content-Type: ${file.mimeType}\r\n\r\n`,
    file.content ?? file.text ?? "",
    "\r\n",
  ]);
  return {
    contentType: `multipart/form-data; boundary=${boundary}`,
    payload: Buffer.concat([
      ...fieldChunks.flatMap((chunk) => chunk.map((part) => Buffer.from(part, "utf8"))),
      ...chunks.flatMap((chunk) => chunk.map((part) => typeof part === "string" ? Buffer.from(part, "utf8") : part)),
      Buffer.from(`--${boundary}--\r\n`, "utf8"),
    ]),
  };
}

/** Builds a tiny one-page text PDF with deterministic xref offsets for upload tests. */
function createSimplePdf(text: string): Buffer {
  const escapedText = text.replaceAll("\\", "\\\\").replaceAll("(", "\\(").replaceAll(")", "\\)");
  const objects = [
    "1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n",
    "2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n",
    "3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>\nendobj\n",
    "4 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n",
    `5 0 obj\n<< /Length ${escapedText.length + 35} >>\nstream\nBT /F1 18 Tf 72 720 Td (${escapedText}) Tj ET\nendstream\nendobj\n`,
  ];
  let pdf = "%PDF-1.4\n";
  const offsets = [0];
  for (const object of objects) {
    offsets.push(Buffer.byteLength(pdf, "binary"));
    pdf += object;
  }
  const xrefOffset = Buffer.byteLength(pdf, "binary");
  pdf += `xref\n0 ${objects.length + 1}\n`;
  pdf += "0000000000 65535 f \n";
  pdf += offsets.slice(1).map((offset) => `${offset.toString().padStart(10, "0")} 00000 n \n`).join("");
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF\n`;
  return Buffer.from(pdf, "binary");
}

/** Yields to asynchronous extraction until a terminal API state is observable. */
async function waitForTerminalJob(
  instance: FastifyInstance,
  id: string,
): Promise<{ status: string }> {
  for (let attempt = 0; attempt < 30; attempt += 1) {
    const response = await instance.inject({ method: "GET", url: `/api/jobs/${id}` });
    const snapshot = response.json<{ status: string }>();
    if (snapshot.status !== "running") {
      return snapshot;
    }
    await new Promise<void>((resolve) => setImmediate(resolve));
  }
  throw new Error("Job did not reach a terminal state");
}