// Generated by GitHub Copilot

import { describe, expect, it, vi } from "vitest";

import {
  SchemaValidationError,
  canonicalizeCandidates,
  cosineSimilarity,
  type AggregatedCandidate,
  type EmbeddingAdapter,
  type LlmAdapter,
} from "../src/index.js";

const candidates: AggregatedCandidate[] = [
  {
    label: "Application",
    definition: "A deployed software system.",
    kind: "NodeType",
    supportCount: 1,
    provenance: [{ documentId: "one.md", chunkIndex: 0 }],
  },
  {
    label: "Software Application",
    definition: "A software system that is deployed.",
    kind: "NodeType",
    supportCount: 1,
    provenance: [{ documentId: "two.md", chunkIndex: 0 }],
  },
];

/** Creates a deterministic embedding adapter keyed by candidate label. */
function createEmbeddings(vectors: Record<string, number[]>): EmbeddingAdapter {
  return {
    dimensions: 2,
    async embed(texts): Promise<number[][]> {
      return texts.map((text) => {
        const entry = Object.entries(vectors).find(([label]) => text.startsWith(label));
        if (entry === undefined) {
          throw new Error(`Missing vector for ${text}`);
        }
        return entry[1];
      });
    },
  };
}

describe("canonicalizeCandidates", () => {
  it("auto-matches above the high threshold without calling the LLM", async () => {
    const llm = { generateStructured: vi.fn() } as unknown as LlmAdapter;
    const types = await canonicalizeCandidates(
      candidates,
      createEmbeddings({ Application: [1, 0], "Software Application": [0.99, 0.01] }),
      llm,
      {
        topK: 5,
        autoMatchThreshold: 0.92,
        autoNewThreshold: 0.6,
        useLlmForAmbiguous: true,
      },
    );

    expect(llm.generateStructured).not.toHaveBeenCalled();
    expect(types).toHaveLength(1);
    expect(types[0]).toMatchObject({
      id: "type-0001",
      aliases: ["Software Application"],
      supportCount: 2,
    });
  });

  it("uses an ambiguous SUBTYPE verdict with a valid top-K target", async () => {
    const llm: LlmAdapter = {
      async generateStructured<T>(): Promise<T> {
        return { verdict: "SUBTYPE", targetId: "type-0001" } as T;
      },
    };
    const types = await canonicalizeCandidates(
      candidates,
      createEmbeddings({ Application: [1, 0], "Software Application": [0.7, 0.7] }),
      llm,
      {
        topK: 1,
        autoMatchThreshold: 0.95,
        autoNewThreshold: 0.5,
        useLlmForAmbiguous: true,
      },
    );

    expect(types).toHaveLength(2);
    expect(types[1]?.parent).toBe("type-0001");
  });

  it("uses custom canonicalization prompts for ambiguous judgments", async () => {
    let request!: Parameters<LlmAdapter["generateStructured"]>[0];
    const llm: LlmAdapter = {
      async generateStructured<T>(nextRequest: Parameters<LlmAdapter["generateStructured"]>[0]): Promise<T> {
        request = nextRequest;
        return { verdict: "MATCH", targetId: "type-0001" } as T;
      },
    };

    await canonicalizeCandidates(
      candidates,
      createEmbeddings({ Application: [1, 0], "Software Application": [0.7, 0.7] }),
      llm,
      {
        topK: 1,
        autoMatchThreshold: 0.95,
        autoNewThreshold: 0.5,
        useLlmForAmbiguous: true,
        systemPrompt: "Choose the closest ontology type.",
        prompt: ({ candidate, neighbors }) =>
          `${candidate.label} compared with ${neighbors[0]?.type.label}`,
      },
    );

    expect(request.system).toBe("Choose the closest ontology type.");
    expect(request.prompt).toBe("Software Application compared with Application");
  });

  it("rejects verdict targets that were not supplied as neighbors", async () => {
    const llm: LlmAdapter = {
      async generateStructured<T>(): Promise<T> {
        return { verdict: "MATCH", targetId: "invented" } as T;
      },
    };

    await expect(
      canonicalizeCandidates(
        candidates,
        createEmbeddings({ Application: [1, 0], "Software Application": [0.7, 0.7] }),
        llm,
        {
          topK: 1,
          autoMatchThreshold: 0.95,
          autoNewThreshold: 0.5,
          useLlmForAmbiguous: true,
        },
      ),
    ).rejects.toBeInstanceOf(SchemaValidationError);
  });
});

describe("cosineSimilarity", () => {
  it("computes orthogonal and identical vector scores", () => {
    expect(cosineSimilarity([1, 0], [0, 1])).toBe(0);
    expect(cosineSimilarity([1, 2], [1, 2])).toBeCloseTo(1);
  });
});