// Generated by GitHub Copilot

import { describe, expect, it } from "vitest";

import { SchemaValidationError, splitDocuments } from "../src/index.js";

describe("splitDocuments", () => {
  it("creates stable overlapping chunks with provenance", () => {
    const text = "First paragraph has context.\n\nSecond paragraph has a relation.\n\nThird paragraph closes it.";
    const chunks = splitDocuments(
      [{ id: "doc.md", text }],
      { strategy: "markdown", chunkSize: 52, chunkOverlap: 12 },
    );

    expect(chunks.length).toBeGreaterThan(1);
    expect(chunks.map(({ documentId, chunkIndex }) => ({ documentId, chunkIndex }))).toEqual(
      chunks.map((_, chunkIndex) => ({ documentId: "doc.md", chunkIndex })),
    );
    expect(chunks.every((chunk) => chunk.text.length <= 52)).toBe(true);
  });

  it("rejects duplicate ids and empty text", () => {
    expect(() =>
      splitDocuments(
        [
          { id: "same", text: "one" },
          { id: "same", text: "two" },
        ],
        { strategy: "recursive", chunkSize: 10, chunkOverlap: 2 },
      ),
    ).toThrow(SchemaValidationError);

    expect(() =>
      splitDocuments(
        [{ id: "empty", text: "  " }],
        { strategy: "recursive", chunkSize: 10, chunkOverlap: 2 },
      ),
    ).toThrow(SchemaValidationError);
  });
});