// Generated by GitHub Copilot

import { describe, expect, it } from "vitest";

import {
  ConfigurationError,
  InMemoryCandidateStore,
  resolveConfig,
  type EmbeddingAdapter,
  type LlmAdapter,
} from "../src/index.js";

const llm: LlmAdapter = {
  async generateStructured<T>(): Promise<T> {
    throw new Error("Not used by configuration tests");
  },
};

const embeddings: EmbeddingAdapter = {
  dimensions: 3,
  async embed(): Promise<number[][]> {
    return [];
  },
};

describe("resolveConfig", () => {
  it("applies the documented defaults", () => {
    const config = resolveConfig({ llm, embeddings });

    expect(config.chunking).toEqual({
      strategy: "recursive",
      chunkSize: 4_000,
      chunkOverlap: 800,
    });
    expect(config.extraction.concurrency).toBe(8);
    expect(config.extraction.accuracy).toBe("medium");
    expect(config.canonicalization.autoNewThreshold).toBe(0.6);
    expect(config.canonicalization.autoMatchThreshold).toBe(0.92);
    expect(config.output.supportCountThreshold).toBe(2);
    expect(config.store).toBeInstanceOf(InMemoryCandidateStore);
  });

  it("rejects overlapping or inverted configuration ranges", () => {
    expect(() =>
      resolveConfig({
        llm,
        embeddings,
        chunking: { chunkSize: 100, chunkOverlap: 100 },
      }),
    ).toThrow(ConfigurationError);

    expect(() =>
      resolveConfig({
        llm,
        embeddings,
        canonicalization: {
          autoNewThreshold: 0.9,
          autoMatchThreshold: 0.8,
        },
      }),
    ).toThrow(ConfigurationError);
  });

  it("rejects unsupported extraction accuracy presets", () => {
    expect(() =>
      resolveConfig({
        llm,
        embeddings,
        extraction: { accuracy: "strict" },
      } as never),
    ).toThrow(ConfigurationError);
  });

  it("preserves prompt overrides supplied at extractor configuration time", () => {
    const extractionPrompt = () => "custom extraction prompt";
    const canonicalizationPrompt = () => "custom canonicalization prompt";

    const config = resolveConfig({
      llm,
      embeddings,
      extraction: {
        systemPrompt: "custom extraction system prompt",
        prompt: extractionPrompt,
      },
      canonicalization: {
        systemPrompt: "custom canonicalization system prompt",
        prompt: canonicalizationPrompt,
      },
    });

    expect(config.extraction).toMatchObject({
      systemPrompt: "custom extraction system prompt",
      prompt: extractionPrompt,
    });
    expect(config.canonicalization).toMatchObject({
      systemPrompt: "custom canonicalization system prompt",
      prompt: canonicalizationPrompt,
    });
  });
});