// Generated by GitHub Copilot

import { describe, expect, it } from "vitest";

import { deduplicateCandidates, type StoredCandidate } from "../src/index.js";

const base: StoredCandidate = {
  label: " Service ",
  definition: "A deployable capability.",
  kind: "NodeType",
  attributes: ["name"],
  documentId: "one.md",
  chunkIndex: 0,
  supportCount: 1,
};

describe("deduplicateCandidates", () => {
  it("counts unique provenance and merges fields deterministically", () => {
    const result = deduplicateCandidates([
      base,
      { ...base, attributes: ["owner"] },
      {
        ...base,
        label: "service",
        documentId: "two.md",
        examples: ["Billing"],
      },
    ]);

    expect(result).toEqual([
      {
        label: "Service",
        definition: "A deployable capability.",
        kind: "NodeType",
        attributes: ["name", "owner"],
        examples: ["Billing"],
        supportCount: 2,
        provenance: [
          { documentId: "one.md", chunkIndex: 0 },
          { documentId: "two.md", chunkIndex: 0 },
        ],
      },
    ]);
  });
});