// Generated by GitHub Copilot

import { describe, expect, it } from "vitest";

import { emitOntology } from "../src/consolidation/emit-ontology.js";
import type { CanonicalType } from "../src/index.js";

const node = (id: string, label: string, supportCount = 2): CanonicalType => ({
  id,
  label,
  definition: `${label} definition`,
  kind: "NodeType",
  attributes: [],
  aliases: [],
  supportCount,
  provenance: [],
});

describe("emitOntology", () => {
  it("resolves relation labels to canonical ids", () => {
    const types: CanonicalType[] = [
      node("type-1", "Service"),
      node("type-2", "API"),
      {
        id: "type-3",
        label: "exposes",
        definition: "A service exposes an API.",
        kind: "RelType",
        domain: "Service",
        range: "API",
        attributes: [],
        aliases: [],
        supportCount: 2,
        provenance: [],
      },
    ];

    const ontology = emitOntology(types, 2, 3, 2);

    expect(ontology.types[2]).toMatchObject({
      kind: "RelType",
      domain: "type-1",
      range: "type-2",
    });
  });

  it("drops relations whose endpoints do not survive support filtering", () => {
    const types: CanonicalType[] = [
      node("type-1", "Service"),
      node("type-2", "API", 1),
      {
        id: "type-3",
        label: "exposes",
        definition: "A service exposes an API.",
        kind: "RelType",
        domain: "Service",
        range: "API",
        attributes: [],
        aliases: [],
        supportCount: 2,
        provenance: [],
      },
    ];

    const ontology = emitOntology(types, 2, 3, 2);

    expect(ontology.types.map(({ label }) => label)).toEqual(["Service"]);
    expect(ontology.stats.droppedBelowThreshold).toBe(2);
  });
});