// Generated by GitHub Copilot

import { describe, expect, it } from "vitest";

import { LlmAdapterError } from "../src/index.js";
import { extractChunks } from "../src/extraction/extract-chunks.js";
import type { DocumentChunk, LlmAdapter } from "../src/index.js";

const chunks: DocumentChunk[] = Array.from({ length: 5 }, (_, chunkIndex) => ({
  documentId: "doc",
  chunkIndex,
  text: `chunk ${chunkIndex}`,
}));

describe("extractChunks", () => {
  it("never exceeds the configured concurrency limit", async () => {
    let active = 0;
    let peak = 0;
    const llm: LlmAdapter = {
      async generateStructured<T>(): Promise<T> {
        active += 1;
        peak = Math.max(peak, active);
        await Promise.resolve();
        active -= 1;
        return {
          candidates: [
            {
              label: "Service",
              definition: "A deployable capability.",
              kind: "NodeType",
              attributes: ["name", "owner", "status"],
              examples: ["Billing"],
            },
          ],
        } as T;
      },
    };

    const result = await extractChunks(
      chunks,
      llm,
      { concurrency: 2, accuracy: "medium", requireExamples: true },
    );

    expect(peak).toBe(2);
    expect(result).toHaveLength(5);
    expect(result[0]?.attributes).toEqual(["name", "owner", "status"]);
  });

  it("isolates one failed chunk but rejects when every chunk fails", async () => {
    let call = 0;
    const partlyFailing: LlmAdapter = {
      async generateStructured<T>(): Promise<T> {
        call += 1;
        if (call === 1) {
          throw new Error("temporary failure");
        }
        return { candidates: [] } as T;
      },
    };

    await expect(
      extractChunks(
        chunks.slice(0, 2),
        partlyFailing,
        { concurrency: 2, accuracy: "medium", requireExamples: false },
      ),
    ).resolves.toEqual([]);

    const failing: LlmAdapter = {
      async generateStructured(): Promise<never> {
        throw new Error("persistent failure");
      },
    };
    const failure = extractChunks(
      chunks.slice(0, 2),
      failing,
      { concurrency: 2, accuracy: "medium", requireExamples: false },
    );
    await expect(
      failure,
    ).rejects.toBeInstanceOf(LlmAdapterError);
    await expect(
      failure,
    ).rejects.toMatchObject({
      cause: expect.objectContaining({ message: "persistent failure" }),
    });
  });

  it("applies strict importance guidance and candidate caps for high accuracy", async () => {
    let request!: Parameters<LlmAdapter["generateStructured"]>[0];
    const llm: LlmAdapter = {
      async generateStructured<T>(nextRequest: Parameters<LlmAdapter["generateStructured"]>[0]): Promise<T> {
        request = nextRequest;
        return { candidates: [] } as T;
      },
    };

    await extractChunks(
      chunks.slice(0, 1),
      llm,
      { concurrency: 1, accuracy: "high", requireExamples: false },
    );

    expect(request.system).toContain("only the most important concepts and relations");
    expect(request.system).toContain("exclude synonyms, local details, minor attributes");
    expect(request.schema).toMatchObject({
      properties: {
        candidates: {
          maxItems: 4,
        },
      },
    });
  });

  it("uses custom extraction prompts supplied in options", async () => {
    let request!: Parameters<LlmAdapter["generateStructured"]>[0];
    const llm: LlmAdapter = {
      async generateStructured<T>(nextRequest: Parameters<LlmAdapter["generateStructured"]>[0]): Promise<T> {
        request = nextRequest;
        return { candidates: [] } as T;
      },
    };

    await extractChunks(
      chunks.slice(0, 1),
      llm,
      {
        concurrency: 1,
        accuracy: "medium",
        requireExamples: false,
        systemPrompt: "Extract only process ontology terms.",
        prompt: (chunk) => `Document ${chunk.documentId}#${chunk.chunkIndex}: ${chunk.text}`,
      },
    );

    expect(request.system).toBe("Extract only process ontology terms.");
    expect(request.prompt).toBe("Document doc#0: chunk 0");
  });

  it("validates and normalizes rich import metadata", async () => {
    const llm: LlmAdapter = {
      async generateStructured<T>(): Promise<T> {
        return {
          candidates: [{
            label: "Ticket",
            definition: "A support request.",
            kind: "NodeType",
            attributes: ["ticketId"],
            attributeDefinitions: [{
              name: "ticketId",
              type: "STRING",
              label: "Ticket ID",
              indexed: true,
              required: true,
              restricted: false,
            }],
            category: "Support Operations",
            primaryKeyAttribute: "ticketId",
            labelAttribute: "ticketId",
            visual: { icon: "ticket", backColor: "#aabbcc" },
          }],
        } as T;
      },
    };

    const [candidate] = await extractChunks(
      chunks.slice(0, 1),
      llm,
      { concurrency: 1, accuracy: "medium", requireExamples: false },
    );

    expect(candidate).toMatchObject({
      category: "Support Operations",
      primaryKeyAttribute: "ticketId",
      attributeDefinitions: [{ name: "ticketId", type: "STRING", required: true }],
      visual: { icon: "ticket", backColor: "#AABBCC" },
    });
  });

  it("rejects metadata references that do not identify declared attributes", async () => {
    const llm: LlmAdapter = {
      async generateStructured<T>(): Promise<T> {
        return {
          candidates: [{
            label: "Ticket",
            definition: "A support request.",
            kind: "NodeType",
            attributes: ["ticketId"],
            primaryKeyAttribute: "missing",
          }],
        } as T;
      },
    };

    await expect(extractChunks(
      chunks.slice(0, 1),
      llm,
      { concurrency: 1, accuracy: "medium", requireExamples: false },
    )).rejects.toBeInstanceOf(LlmAdapterError);
  });
});