// Generated by GitHub Copilot

import { describe, expect, it, vi } from "vitest";

import {
  CancelledError,
  ExtractionJobHandle,
  type Ontology,
} from "../src/index.js";

const ontology: Ontology = {
  types: [],
  generatedAt: 1,
  stats: {
    documentCount: 0,
    candidateCount: 0,
    typeCount: 0,
    droppedBelowThreshold: 0,
  },
};

describe("ExtractionJobHandle", () => {
  it("starts on a microtask and publishes detached progress snapshots", async () => {
    const operation = vi.fn(async ({ update }) => {
      update({ phase: "chunking", chunks: { total: 2, processed: 0 } });
      return ontology;
    });
    const phases: string[] = [];
    const job = new ExtractionJobHandle(1);
    job.on("phase", (phase) => phases.push(phase));

    job.start(operation);

    expect(operation).not.toHaveBeenCalled();
    expect(job.progress.phase).toBe("idle");
    await expect(job.completed()).resolves.toBe(ontology);
    expect(phases).toEqual(["chunking", "done"]);

    const snapshot = job.progress;
    snapshot.documents.processed = 99;
    expect(job.progress.documents.processed).toBe(0);
  });

  it("cancels cooperatively and rejects with CancelledError", async () => {
    const job = new ExtractionJobHandle(1);
    let receivedSignal: AbortSignal | undefined;
    job.start(async ({ signal }) => {
      receivedSignal = signal;
      await new Promise(() => undefined);
      return ontology;
    });
    await Promise.resolve();

    const completion = job.completed();
    await job.cancel();

    await expect(completion).rejects.toBeInstanceOf(CancelledError);
    expect(receivedSignal?.aborted).toBe(true);
    expect(job.progress.phase).toBe("cancelled");
  });
});