// Generated by GitHub Copilot

import { HumanMessage, SystemMessage } from "@langchain/core/messages";
import { describe, expect, it, vi } from "vitest";

import {
  LangChainEmbeddingAdapter,
  LangChainLlmAdapter,
} from "../src/langchain/index.js";

describe("LangChainLlmAdapter", () => {
  it("forwards schema, messages, and AbortSignal to structured output", async () => {
    const invoke = vi.fn(
      async (_messages: unknown[], _config: { signal?: AbortSignal }) => ({
        candidates: [],
      }),
    );
    const withStructuredOutput = vi.fn(() => ({ invoke }));
    const model = { withStructuredOutput };
    const adapter = new LangChainLlmAdapter(model as never);
    const controller = new AbortController();
    const schema = { type: "object" };

    const result = await adapter.generateStructured({
      system: "system instruction",
      prompt: "document fragment",
      schema,
      signal: controller.signal,
    });

    expect(result).toEqual({ candidates: [] });
    expect(withStructuredOutput).toHaveBeenCalledWith(schema, {
      name: "ontology_extractor_output",
    });
    const [messages, config] = invoke.mock.calls[0] ?? [];
    expect(messages?.[0]).toBeInstanceOf(SystemMessage);
    expect(messages?.[1]).toBeInstanceOf(HumanMessage);
    expect(config).toEqual({ signal: controller.signal });
  });

  it("can force JSON mode and includes schema guidance for local OpenAI-compatible providers", async () => {
    const invoke = vi.fn(
      async (_messages: unknown[], _config: { signal?: AbortSignal }) => ({
        candidates: [],
      }),
    );
    const withStructuredOutput = vi.fn(() => ({ invoke }));
    const model = { withStructuredOutput };
    const adapter = new LangChainLlmAdapter(model as never, { structuredOutputMethod: "jsonMode" });
    const schema = { type: "object", properties: { candidates: { type: "array" } } };

    await adapter.generateStructured({
      prompt: "document fragment",
      schema,
    });

    expect(withStructuredOutput).toHaveBeenCalledWith(schema, {
      name: "ontology_extractor_output",
      method: "jsonMode",
    });
    const [messages] = invoke.mock.calls[0] ?? [];
    const [message] = messages as HumanMessage[];
    if (message === undefined) {
      throw new Error("Expected LangChain prompt message");
    }
    expect(message).toBeInstanceOf(HumanMessage);
    expect(String(message.content)).toContain("Return only a valid JSON object");
    expect(String(message.content)).toContain(JSON.stringify(schema));
  });
});

describe("LangChainEmbeddingAdapter", () => {
  it("forwards texts and exposes configured dimensions", async () => {
    const embedDocuments = vi.fn(async () => [[1, 0], [0, 1]]);
    const adapter = new LangChainEmbeddingAdapter({ embedDocuments, embedQuery: vi.fn() }, 2);

    await expect(adapter.embed(["one", "two"])).resolves.toEqual([
      [1, 0],
      [0, 1],
    ]);
    expect(embedDocuments).toHaveBeenCalledWith(["one", "two"]);
    expect(adapter.dimensions).toBe(2);
  });

  it("rejects immediately for an already aborted signal", async () => {
    const embedDocuments = vi.fn(async () => [[1, 0]]);
    const adapter = new LangChainEmbeddingAdapter({ embedDocuments, embedQuery: vi.fn() }, 2);
    const controller = new AbortController();
    controller.abort();

    await expect(adapter.embed(["one"], controller.signal)).rejects.toMatchObject({
      name: "AbortError",
    });
    expect(embedDocuments).not.toHaveBeenCalled();
  });
});