// Generated by GitHub Copilot

import { describe, expect, it, vi } from "vitest";

import {
  ConcurrentJobError,
  OntologyExtractor,
  type EmbeddingAdapter,
  type LlmAdapter,
} from "../src/index.js";

const embeddings: EmbeddingAdapter = {
  dimensions: 2,
  async embed(texts): Promise<number[][]> {
    return texts.map(() => [1, 0]);
  },
};

describe("OntologyExtractor", () => {
  it("extracts documents end-to-end and accumulates unique support", async () => {
    const generateStructured = vi.fn(async () => ({
      candidates: [
        {
          label: "Service",
          definition: "A deployable software capability.",
          kind: "NodeType",
          examples: ["Billing"],
        },
      ],
    }));
    const extractor = new OntologyExtractor({
      llm: { generateStructured } as LlmAdapter,
      embeddings,
      chunking: { chunkSize: 1_000, chunkOverlap: 100 },
    });

    const job = extractor.extract([
      { id: "one.md", text: "The billing service is deployed." },
      { id: "two.md", text: "A service exposes an API." },
    ]);
    expect(job.progress.phase).toBe("idle");

    const ontology = await job.completed();

    expect(generateStructured).toHaveBeenCalledTimes(2);
    expect(ontology.types).toHaveLength(1);
    expect(ontology.types[0]).toMatchObject({ label: "Service", supportCount: 2 });
    expect(ontology.stats).toMatchObject({
      documentCount: 2,
      candidateCount: 2,
      typeCount: 1,
    });
    expect(job.progress.phase).toBe("done");
  });

  it("preserves extraction calls when an ambiguous type needs LLM judgment", async () => {
    let extractionIndex = 0;
    const llm: LlmAdapter = {
      async generateStructured<T>(
        { schema }: Parameters<LlmAdapter["generateStructured"]>[0],
      ): Promise<T> {
        const required = Array.isArray(schema.required) ? schema.required : [];
        if (required.includes("candidates")) {
          extractionIndex += 1;
          return {
            candidates: [
              {
                label: extractionIndex === 1 ? "Application" : "Software Application",
                definition: "A deployed software system.",
                kind: "NodeType",
                examples: ["Billing"],
              },
            ],
          } as T;
        }
        return { verdict: "MATCH", targetId: "type-0001" } as T;
      },
    };
    const ambiguousEmbeddings: EmbeddingAdapter = {
      dimensions: 2,
      async embed(texts): Promise<number[][]> {
        return texts.map((text) =>
          text.startsWith("Application") ? [1, 0] : [0.7, 0.7],
        );
      },
    };
    const extractor = new OntologyExtractor({
      llm,
      embeddings: ambiguousEmbeddings,
      canonicalization: {
        autoNewThreshold: 0.5,
        autoMatchThreshold: 0.95,
      },
    });

    const job = extractor.extract([
      { id: "one", text: "application" },
      { id: "two", text: "software application" },
    ]);
    await job.completed();

    expect(job.progress.llmCalls).toEqual({ extraction: 2, canonicalization: 1 });
  });

  it("refines only unseen documents and reconsolidates without double counting", async () => {
    const generateStructured = vi.fn(async () => ({
      candidates: [
        {
          label: "Service",
          definition: "A deployable software capability.",
          kind: "NodeType",
          examples: ["Billing"],
        },
      ],
    }));
    const extractor = new OntologyExtractor({
      llm: { generateStructured } as LlmAdapter,
      embeddings,
      output: { supportCountThreshold: 1 },
    });
    await extractor.extract([{ id: "one", text: "first service" }]).completed();

    const refined = await extractor
      .refine([
        { id: "one", text: "must be skipped" },
        { id: "two", text: "second service" },
      ])
      .completed();
    const reconsolidated = await extractor.consolidate().completed();

    expect(generateStructured).toHaveBeenCalledTimes(2);
    expect(refined.types[0]?.supportCount).toBe(2);
    expect(reconsolidated.types[0]?.supportCount).toBe(2);
    expect(reconsolidated.stats.documentCount).toBe(2);
  });

  it("keeps the last valid ontology when consolidation fails", async () => {
    let failEmbeddings = false;
    const controlledEmbeddings: EmbeddingAdapter = {
      dimensions: 2,
      async embed(texts): Promise<number[][]> {
        if (failEmbeddings) {
          throw new Error("embedding service unavailable");
        }
        return texts.map(() => [1, 0]);
      },
    };
    const llm: LlmAdapter = {
      async generateStructured<T>(): Promise<T> {
        return {
          candidates: [
            {
              label: "Service",
              definition: "A deployable capability.",
              kind: "NodeType",
              examples: ["Billing"],
            },
          ],
        } as T;
      },
    };
    const extractor = new OntologyExtractor({
      llm,
      embeddings: controlledEmbeddings,
      output: { supportCountThreshold: 1 },
    });
    const valid = await extractor.extract([{ id: "one", text: "service" }]).completed();
    failEmbeddings = true;

    await expect(extractor.consolidate().completed()).rejects.toThrow(
      "Embedding adapter failed",
    );

    await expect(extractor.getOntology()).resolves.toEqual(valid);
  });

  it("rejects a second active pipeline synchronously", async () => {
    let release!: () => void;
    const gate = new Promise<void>((resolve) => {
      release = resolve;
    });
    const llm: LlmAdapter = {
      async generateStructured<T>(): Promise<T> {
        await gate;
        return { candidates: [] } as T;
      },
    };
    const extractor = new OntologyExtractor({
      llm,
      embeddings,
      extraction: { requireExamples: false },
    });
    const first = extractor.extract([{ id: "one", text: "content" }]);
    await Promise.resolve();

    expect(() => extractor.consolidate()).toThrow(ConcurrentJobError);
    release();
    await first.completed();
  });
});