// Generated by GitHub Copilot

import { describe, expect, it } from "vitest";

import { toOntologyImportModel } from "../src/index.js";
import type { CanonicalType, Ontology } from "../src/index.js";

const customer: CanonicalType = {
  id: "node-customer",
  label: "Customer",
  definition: "A customer account.",
  kind: "NodeType",
  attributes: ["customerId", "displayName", "legacyField"],
  attributeDefinitions: [
    {
      name: "customerId",
      type: "STRING",
      label: "Customer ID",
      indexed: true,
      required: true,
      restricted: false,
    },
    { name: "displayName", type: "STRING", label: "Display name", required: true },
  ],
  category: "Customer Data",
  primaryKeyAttribute: "customerId",
  labelAttribute: "displayName",
  aliases: [],
  supportCount: 2,
  provenance: [],
};

const ticket: CanonicalType = {
  id: "node-ticket",
  label: "SupportTicket",
  definition: "A support case.",
  kind: "NodeType",
  attributes: ["ticketId"],
  aliases: [],
  supportCount: 1,
  provenance: [],
};

const relation: CanonicalType = {
  id: "rel-ticket",
  label: "HAS_TICKET",
  definition: "A customer can open support tickets.",
  kind: "RelType",
  domain: customer.id,
  range: ticket.id,
  attributes: ["openedAt"],
  attributeDefinitions: [{ name: "openedAt", type: "DATETIME", required: true }],
  fromCardinality: "1",
  toCardinality: "N",
  aliases: [],
  supportCount: 1,
  provenance: [],
};

/** Creates a compact ontology fixture around the supplied canonical types. */
function ontology(types: CanonicalType[]): Ontology {
  return {
    types,
    generatedAt: 1,
    stats: {
      documentCount: 1,
      candidateCount: types.length,
      typeCount: types.length,
      droppedBelowThreshold: 0,
    },
  };
}

describe("toOntologyImportModel", () => {
  it("maps rich entity and relationship metadata into the import contract", () => {
    const result = toOntologyImportModel(ontology([customer, ticket, relation]), {
      name: "customer-support",
      namespace: "support",
      description: "Support model",
    });

    expect(result).toMatchObject({
      version: 1,
      ontology: {
        name: "customer-support",
        namespace: "support",
        description: "Support model",
        status: "ACTIVE",
      },
      categories: [{ ref: "customer-data", name: "Customer Data" }],
      variables: [],
      entities: [
        {
          ref: "customer",
          name: "Customer",
          definition: {
            pkAttribute: "customerId",
            labelAttribute: "displayName",
            categoryRef: "customer-data",
          },
        },
        {
          ref: "support-ticket",
          name: "SupportTicket",
          definition: { pkAttribute: "ticketId" },
        },
      ],
      relationships: [
        {
          ref: "has-ticket",
          fromEntityRef: "customer",
          toEntityRef: "support-ticket",
          definition: {
            cardinality: "1 : N",
            fromCardinality: "1",
            toCardinality: "N",
          },
        },
      ],
    });
    expect(result.entities[0]?.definition.attributes).toEqual(expect.arrayContaining([
      expect.objectContaining({
        name: "customerId",
        type: "STRING",
        label: "Customer ID",
        indexed: true,
        required: true,
        restricted: false,
      }),
      expect.objectContaining({
        name: "legacyField",
        type: "STRING",
        label: "Legacy Field",
        indexed: false,
        required: false,
        restricted: false,
      }),
    ]));
    expect(result.relationships[0]?.definition.attributes[0]).toMatchObject({
      name: "openedAt",
      type: "DATETIME",
      required: true,
    });
  });

  it("is stable, omits security sections, and drops unresolved relations", () => {
    const unresolved = { ...relation, id: "unresolved", range: "missing" };
    const first = toOntologyImportModel(ontology([customer, unresolved]), {
      name: "model",
      namespace: "namespace",
    });
    const second = toOntologyImportModel(ontology([customer, unresolved]), {
      name: "model",
      namespace: "namespace",
    });

    expect(first).toEqual(second);
    expect(first.relationships).toEqual([]);
    expect(first.entities[0]?.definition.attributes[0]?.id).toMatch(
      /^[0-9a-f]{8}-[0-9a-f]{4}-5[0-9a-f]{3}-8[0-9a-f]{3}-[0-9a-f]{12}$/,
    );
    expect(first).not.toHaveProperty("userGroups");
    expect(first).not.toHaveProperty("securityProfiles");
    expect(first).not.toHaveProperty("policies");
  });

  it("guarantees a valid primary key for entities without extracted attributes", () => {
    const emptyEntity: CanonicalType = {
      id: "node-agent",
      label: "SupportAgent",
      definition: "A support employee.",
      kind: "NodeType",
      attributes: [],
      aliases: [],
      supportCount: 1,
      provenance: [],
    };

    const result = toOntologyImportModel(ontology([ticket, emptyEntity]), {
      name: "model",
      namespace: "model",
    });

    for (const entity of result.entities) {
      const primaryKey = entity.definition.attributes.find(
        ({ name }) => name === entity.definition.pkAttribute,
      );
      expect(primaryKey).toMatchObject({ indexed: true, required: true });
    }
    expect(result.entities[1]).toMatchObject({
      definition: {
        pkAttribute: "supportAgentId",
        attributes: [{
          name: "supportAgentId",
          type: "STRING",
          indexed: true,
          required: true,
        }],
      },
    });
  });

  it("rejects blank required ontology metadata", () => {
    expect(() => toOntologyImportModel(ontology([]), { name: " ", namespace: "test" }))
      .toThrow("options.name must be a non-empty string");
  });
});
