// Generated by GitHub Copilot

import { describe, expect, it } from "vitest";

import {
  InMemoryCandidateStore,
  StoreConflictError,
  type ExtractedCandidate,
} from "../src/index.js";

const candidate: ExtractedCandidate = {
  label: "Service",
  definition: "A deployable software capability.",
  kind: "NodeType",
  attributes: ["name"],
  documentId: "architecture.md",
  chunkIndex: 0,
};

describe("InMemoryCandidateStore", () => {
  it("records documents even when they have no candidates", async () => {
    const store = new InMemoryCandidateStore();

    await store.appendCandidates("empty.md", []);

    await expect(store.hasDocument("empty.md")).resolves.toBe(true);
    await expect(store.getDocumentIds()).resolves.toEqual(["empty.md"]);
    await expect(store.getAllCandidates()).resolves.toEqual([]);
  });

  it("returns defensive copies of nested candidate fields", async () => {
    const store = new InMemoryCandidateStore();
    await store.appendCandidates(candidate.documentId, [candidate]);

    const firstRead = await store.getAllCandidates();
    firstRead[0]?.attributes?.push("mutated");

    const secondRead = await store.getAllCandidates();
    expect(secondRead).toEqual([{ ...candidate, supportCount: 1 }]);
  });

  it("rejects duplicate documents and mismatched provenance", async () => {
    const store = new InMemoryCandidateStore();
    await store.appendCandidates(candidate.documentId, [candidate]);

    await expect(
      store.appendCandidates(candidate.documentId, []),
    ).rejects.toBeInstanceOf(StoreConflictError);
    await expect(
      new InMemoryCandidateStore().appendCandidates("other.md", [candidate]),
    ).rejects.toBeInstanceOf(StoreConflictError);
  });

  it("removes one document without affecting another", async () => {
    const store = new InMemoryCandidateStore();
    await store.appendCandidates(candidate.documentId, [candidate]);
    await store.appendCandidates("empty.md", []);

    await store.removeDocument(candidate.documentId);

    await expect(store.hasDocument(candidate.documentId)).resolves.toBe(false);
    await expect(store.hasDocument("empty.md")).resolves.toBe(true);
    await expect(store.getDocumentIds()).resolves.toEqual(["empty.md"]);
    await expect(store.getAllCandidates()).resolves.toEqual([]);
  });
});