// Generated by GitHub Copilot

import { SchemaValidationError } from "../errors.js";
import type { DocumentChunk, InputDocument } from "../types.js";

export interface ChunkingOptions {
  strategy: "recursive" | "markdown" | "html";
  chunkSize: number;
  chunkOverlap: number;
}

const separators: Record<ChunkingOptions["strategy"], string[]> = {
  recursive: ["\n\n", "\n", ". ", " "],
  markdown: ["\n# ", "\n## ", "\n### ", "\n\n", "\n", ". ", " "],
  html: ["</section>", "</article>", "</div>", "</p>", "\n", " "],
};

/** Validates documents and splits them into stable, overlapping chunks. */
export function splitDocuments(
  documents: InputDocument[],
  options: ChunkingOptions,
): DocumentChunk[] {
  validateDocuments(documents);
  return documents.flatMap((document) => splitDocument(document, options));
}

/** Splits one document while preferring semantic boundaries near chunk end. */
function splitDocument(
  document: InputDocument,
  options: ChunkingOptions,
): DocumentChunk[] {
  const chunks: DocumentChunk[] = [];
  let start = 0;

  while (start < document.text.length) {
    const maximumEnd = Math.min(start + options.chunkSize, document.text.length);
    const end = findBoundary(
      document.text,
      start,
      maximumEnd,
      separators[options.strategy],
    );
    const text = document.text.slice(start, end).trim();
    if (text.length > 0) {
      chunks.push({
        documentId: document.id,
        chunkIndex: chunks.length,
        text,
      });
    }

    if (end >= document.text.length) {
      break;
    }
    start = Math.max(end - options.chunkOverlap, start + 1);
  }

  return chunks;
}

/** Finds the latest useful separator without creating very small chunks. */
function findBoundary(
  text: string,
  start: number,
  maximumEnd: number,
  candidates: string[],
): number {
  if (maximumEnd === text.length) {
    return maximumEnd;
  }

  const minimumEnd = start + Math.floor((maximumEnd - start) * 0.5);
  for (const separator of candidates) {
    const index = text.lastIndexOf(separator, maximumEnd);
    if (index >= minimumEnd) {
      return index + separator.length;
    }
  }
  return maximumEnd;
}

/** Rejects empty, duplicate, or malformed document inputs. */
function validateDocuments(documents: InputDocument[]): void {
  const ids = new Set<string>();
  for (const document of documents) {
    if (document.id.trim().length === 0) {
      throw new SchemaValidationError("Document id must not be empty");
    }
    if (document.text.trim().length === 0) {
      throw new SchemaValidationError(
        `Document text must not be empty: ${document.id}`,
      );
    }
    if (ids.has(document.id)) {
      throw new SchemaValidationError(`Duplicate document id: ${document.id}`);
    }
    ids.add(document.id);
  }
}