// Generated by GitHub Copilot

import { copyFile, mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import { basename, extname, join, resolve } from "node:path";

import {
  OntologyExtractor,
  type InputDocument,
  type Ontology,
} from "ontology-extractor";

import { evaluateOntology } from "./evaluation.js";
import {
  createProviderAdapters,
  type ProviderName,
} from "./providers.js";
import { renderReport } from "./report.js";

const allowedExtensions = new Set([".txt", ".md", ".html", ".htm"]);
const maximumDocumentBytes = 2 * 1024 * 1024;

/** Runs the sample CLI and writes ontology, run metadata, and an HTML report. */
async function main(): Promise<void> {
  const options = parseArguments(process.argv.slice(2));
  const documents = await loadDocuments(options.input);
  const adapters = createProviderAdapters(options.provider);
  const extractor = new OntologyExtractor({
    llm: adapters.llm,
    embeddings: adapters.embeddings,
    output: { supportCountThreshold: 1 },
  });
  const firstJob = extractor.extract(documents);
  logProgress(firstJob);
  let ontology = await firstJob.completed();

  if (options.refine !== undefined) {
    const refinementDocuments = await loadDocuments(options.refine);
    const refinementJob = extractor.refine(refinementDocuments);
    logProgress(refinementJob);
    ontology = await refinementJob.completed();
  }
  const evaluation = options.gold === undefined
    ? undefined
    : evaluateOntology(ontology, await loadGoldOntology(options.gold));

  await mkdir(options.output, { recursive: true });
  await Promise.all([
    writeFile(join(options.output, "ontology.json"), `${JSON.stringify(ontology, null, 2)}\n`, "utf8"),
    writeFile(
      join(options.output, "index.html"),
      renderReport(ontology, "Ontology extraction report", evaluation),
      "utf8",
    ),
    writeFile(
      join(options.output, "run.json"),
      `${JSON.stringify({ provider: adapters.summary, stats: ontology.stats, evaluation }, null, 2)}\n`,
      "utf8",
    ),
    copyFile(
      new URL("./report-client.js", import.meta.url),
      join(options.output, "report-client.js"),
    ),
  ]);
  process.stdout.write(`Report written to ${join(options.output, "index.html")}\n`);
}

interface CliOptions {
  input: string;
  output: string;
  provider: ProviderName;
  gold?: string;
  refine?: string;
}

/** Parses a deliberately small and auditable CLI argument surface. */
function parseArguments(args: string[]): CliOptions {
  const normalizedArgs = args[0] === "--" ? args.slice(1) : args;
  const values = new Map<string, string>();
  for (let index = 0; index < normalizedArgs.length; index += 2) {
    const key = normalizedArgs[index];
    const value = normalizedArgs[index + 1];
    if (key === undefined || value === undefined || !key.startsWith("--")) {
      throw new Error("Usage: --input <directory> [--provider mock|lmstudio|azure] [--refine <directory>] [--gold <ontology.json>] [--output <directory>]");
    }
    values.set(key, value);
  }
  const input = values.get("--input");
  if (input === undefined) {
    throw new Error("Missing required --input directory");
  }
  const allowed = new Set(["--input", "--provider", "--refine", "--gold", "--output"]);
  for (const key of values.keys()) {
    if (!allowed.has(key)) {
      throw new Error(`Unknown option: ${key}`);
    }
  }
  const provider = readProvider(values.get("--provider") ?? "mock");
  const refine = values.get("--refine");
  const gold = values.get("--gold");
  return {
    input: resolve(input),
    output: resolve(values.get("--output") ?? "report"),
    provider,
    ...(gold === undefined ? {} : { gold: resolve(gold) }),
    ...(refine === undefined ? {} : { refine: resolve(refine) }),
  };
}

/** Loads and minimally validates a size-limited gold ontology JSON file. */
async function loadGoldOntology(filePath: string): Promise<Ontology> {
  const content = await readFile(filePath);
  if (content.byteLength > maximumDocumentBytes) {
    throw new Error(`Gold ontology exceeds 2 MiB limit: ${basename(filePath)}`);
  }
  const parsed: unknown = JSON.parse(content.toString("utf8"));
  if (!isRecord(parsed) || !Array.isArray(parsed.types) || !isRecord(parsed.stats)) {
    throw new Error("Gold ontology must contain types and stats");
  }
  return parsed as unknown as Ontology;
}

/** Narrows and validates the provider option before any document processing. */
function readProvider(value: string): ProviderName {
  if (value !== "mock" && value !== "lmstudio" && value !== "azure") {
    throw new Error(`Unsupported provider: ${value}`);
  }
  return value;
}

/** Loads supported regular files from one directory with a strict size cap. */
async function loadDocuments(directory: string): Promise<InputDocument[]> {
  const entries = await readdir(directory, { withFileTypes: true });
  const fileNames = entries
    .filter((entry) => entry.isFile() && allowedExtensions.has(extname(entry.name).toLowerCase()))
    .map(({ name }) => name)
    .sort((left, right) => left.localeCompare(right));
  if (fileNames.length === 0) {
    throw new Error(`No supported documents found in ${directory}`);
  }
  return Promise.all(fileNames.map(async (fileName) => {
    const filePath = join(directory, fileName);
    const content = await readFile(filePath);
    if (content.byteLength > maximumDocumentBytes) {
      throw new Error(`Document exceeds 2 MiB limit: ${fileName}`);
    }
    return { id: basename(fileName), text: content.toString("utf8") };
  }));
}

/** Prints phase changes without exposing document content or secrets. */
function logProgress(job: ReturnType<OntologyExtractor["extract"]>): void {
  job.on("phase", (phase) => process.stdout.write(`phase: ${phase}\n`));
}

/** Narrows unknown JSON values to records for boundary validation. */
function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

await main();