// Generated by GitHub Copilot

import type { CanonicalType, Ontology } from "ontology-extractor";

import type { EvaluationResult, MetricResult } from "./evaluation.js";

/** Generates an accessible report whose only script is a bundled local asset. */
export function renderReport(
  ontology: Ontology,
  title: string,
  evaluation?: EvaluationResult,
): string {
  const maximumSupport = Math.max(1, ...ontology.types.map(({ supportCount }) => supportCount));
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'self'; style-src 'unsafe-inline'; img-src data:">
  <title>${escapeHtml(title)}</title>
  <style>
    :root { color-scheme: light; --ink:#172121; --paper:#f4f1e8; --accent:#006b5f; --line:#b7b4a9; --warm:#d95d39; }
    * { box-sizing: border-box; }
    html, body { max-width:100%; overflow-x:clip; }
    body { margin:0; color:var(--ink); background:var(--paper); font-family:Georgia, 'Times New Roman', serif; line-height:1.5; }
    header, main, .footer-inner { width:min(1100px, calc(100% - 32px)); margin-inline:auto; }
    header { padding:48px 0 24px; border-bottom:2px solid var(--ink); }
    h1 { margin:0; font-size:clamp(2rem, 5vw, 4rem); letter-spacing:0; }
    h2 { margin-top:40px; font-size:1.5rem; letter-spacing:0; }
    .stats { display:grid; grid-template-columns:repeat(auto-fit,minmax(150px,1fr)); gap:1px; background:var(--line); margin-top:24px; border:1px solid var(--line); }
    .stat { background:var(--paper); padding:16px; }
    .stat strong { display:block; color:var(--accent); font:700 1.8rem ui-monospace,monospace; }
    .graph-shell { display:grid; grid-template-columns:minmax(0, 1fr) 260px; border-block:1px solid var(--line); background:#fff; }
    .graph-tools { display:flex; flex-wrap:wrap; align-items:end; gap:16px; padding:16px 0; }
    .control { display:grid; gap:5px; font-weight:700; }
    .control input[type="search"] { width:min(320px, 76vw); }
    input, button { min-height:40px; border:1px solid var(--ink); border-radius:4px; background:#fff; color:var(--ink); padding:7px 10px; font:inherit; }
    input[type="range"] { min-height:28px; padding:0; }
    button { cursor:pointer; font-weight:700; }
    button:hover { background:#e6e2d6; }
    input:focus-visible, button:focus-visible { outline:3px solid var(--warm); outline-offset:2px; }
    #ontology-graph { width:100%; height:560px; min-height:420px; }
    #graph-details { border-left:1px solid var(--line); padding:20px; overflow-wrap:anywhere; }
    #graph-details h3 { margin-top:0; }
    .graph-fallback { padding:12px 0; color:#555; }
    table { width:100%; table-layout:fixed; border-collapse:collapse; background:#fff; }
    th, td { border:1px solid var(--line); padding:10px; text-align:left; vertical-align:top; overflow-wrap:anywhere; }
    th { background:#e6e2d6; }
    code { font-family:ui-monospace,monospace; }
    footer { margin-top:48px; padding:24px 0 48px; border-top:1px solid var(--line); }
    @media (max-width:720px) { .graph-shell { grid-template-columns:1fr; } #ontology-graph { height:460px; } #graph-details { border-left:0; border-top:1px solid var(--line); } th:nth-child(3), td:nth-child(3) { display:none; } }
  </style>
</head>
<body>
  <header>
    <h1>${escapeHtml(title)}</h1>
    <p>Generated TBox projection. The offline demo adapter recognizes a deliberately small software architecture vocabulary.</p>
    <div class="stats" aria-label="Ontology statistics">
      ${renderStat("Documents", ontology.stats.documentCount)}
      ${renderStat("Candidates", ontology.stats.candidateCount)}
      ${renderStat("Types", ontology.stats.typeCount)}
      ${renderStat("Filtered", ontology.stats.droppedBelowThreshold)}
    </div>
  </header>
  <main>
    <h2>Schema overview</h2>
    <div class="graph-tools" aria-label="Graph controls">
      <label class="control" for="graph-search">Find type<input id="graph-search" type="search" autocomplete="off"></label>
      <label class="control" for="support-filter">Minimum support: <output id="support-value" for="support-filter">1</output><input id="support-filter" type="range" min="1" max="${maximumSupport}" value="1" step="1"></label>
      <label><input id="relation-filter" type="checkbox" checked> Show relations</label>
      <button id="fit-graph" type="button">Fit graph</button>
      <button id="reset-graph" type="button">Reset filters</button>
    </div>
    <p id="graph-status" role="status" aria-live="polite"></p>
    <div class="graph-shell">
      <div id="ontology-graph" role="img" aria-label="Interactive ontology graph. Use the equivalent canonical types table below for a text representation."></div>
      <aside id="graph-details" aria-live="polite"><h3>Selection details</h3><p>Select a type or relation in the graph.</p></aside>
    </div>
    <noscript><p class="graph-fallback">JavaScript is disabled. The complete ontology remains available in the table below.</p></noscript>
    <h2>Canonical types</h2>
    <table>
      <thead><tr><th>Type</th><th>Kind</th><th>Definition</th><th>Support</th><th>References</th></tr></thead>
      <tbody>${ontology.types.map(renderTypeRow).join("")}</tbody>
    </table>
    ${evaluation === undefined ? "" : renderEvaluation(evaluation)}
  </main>
  <footer><div class="footer-inner">Generated at <time>${escapeHtml(new Date(ontology.generatedAt).toISOString())}</time>.</div></footer>
  <script id="ontology-data" type="application/json">${serializeForHtml(ontology)}</script>
  <script src="./report-client.js" defer></script>
</body>
</html>`;
}

/** Serializes JSON without allowing data to terminate its script element. */
function serializeForHtml(value: unknown): string {
  return JSON.stringify(value)
    .replaceAll("<", String.raw`\u003c`)
    .replaceAll("\u2028", String.raw`\u2028`)
    .replaceAll("\u2029", String.raw`\u2029`);
}

/** Renders benchmark metrics only when a gold TBox was supplied. */
function renderEvaluation(evaluation: EvaluationResult): string {
  return `<h2>Gold TBox evaluation</h2>
    <table>
      <thead><tr><th>Dimension</th><th>Precision</th><th>Recall</th><th>F1</th><th>Mismatches</th></tr></thead>
      <tbody>
        ${renderMetricRow("Node types", evaluation.types)}
        ${renderMetricRow("Relations", evaluation.relations)}
      </tbody>
    </table>`;
}

/** Renders one metric row with escaped mismatch diagnostics. */
function renderMetricRow(label: string, metric: MetricResult): string {
  const mismatches = [
    ...metric.falsePositives.map((value) => `extra: ${value}`),
    ...metric.falseNegatives.map((value) => `missing: ${value}`),
  ].join("; ") || "none";
  return `<tr><td>${escapeHtml(label)}</td><td>${formatScore(metric.precision)}</td><td>${formatScore(metric.recall)}</td><td>${formatScore(metric.f1)}</td><td>${escapeHtml(mismatches)}</td></tr>`;
}

/** Formats a unit-interval score as a percentage. */
function formatScore(value: number): string {
  return `${(value * 100).toFixed(1)}%`;
}

/** Renders one numeric statistic. */
function renderStat(label: string, value: number): string {
  return `<div class="stat"><strong>${value}</strong>${escapeHtml(label)}</div>`;
}

/** Renders one canonical type as an accessible table row. */
function renderTypeRow(type: CanonicalType): string {
  const references = renderReferences(type);
  return `<tr><td><strong>${escapeHtml(type.label)}</strong></td><td>${type.kind}</td><td>${escapeHtml(type.definition)}</td><td>${type.supportCount}</td><td><code>${escapeHtml(references)}</code></td></tr>`;
}

/** Renders relation endpoints or an optional subtype reference. */
function renderReferences(type: CanonicalType): string {
  if (type.kind === "RelType") {
    return `${type.domain ?? "?"} → ${type.range ?? "?"}`;
  }
  return type.parent === undefined ? "—" : `is-a ${type.parent}`;
}

/** Escapes untrusted document-derived text before inserting it into HTML. */
function escapeHtml(value: string): string {
  return value.replace(/[&<>"']/g, (character) => ({
    "&": "&amp;",
    "<": "&lt;",
    ">": "&gt;",
    '"': "&quot;",
    "'": "&#39;",
  })[character] ?? character);
}