// Generated by GitHub Copilot

import cytoscape, { type Core, type ElementDefinition } from "cytoscape";
import type { CanonicalType, Ontology } from "ontology-extractor";

interface GraphState {
  cy: Core;
  ontology: Ontology;
  search: HTMLInputElement;
  support: HTMLInputElement;
  supportValue: HTMLElement;
  relations: HTMLInputElement;
  status: HTMLElement;
  details: HTMLElement;
}

/** Initializes the offline ontology graph and its keyboard-accessible controls. */
function initializeReport(): void {
  const ontology = readOntology();
  const container = requireElement<HTMLElement>("ontology-graph");
  const state: GraphState = {
    ontology,
    search: requireElement<HTMLInputElement>("graph-search"),
    support: requireElement<HTMLInputElement>("support-filter"),
    supportValue: requireElement<HTMLElement>("support-value"),
    relations: requireElement<HTMLInputElement>("relation-filter"),
    status: requireElement<HTMLElement>("graph-status"),
    details: requireElement<HTMLElement>("graph-details"),
    cy: cytoscape({
      container,
      elements: toElements(ontology.types),
      style: graphStyles,
      layout: {
        name: "cose",
        animate: false,
        randomize: false,
        nodeRepulsion: () => 9_000,
        idealEdgeLength: () => 130,
      },
      minZoom: 0.25,
      maxZoom: 2.5,
      wheelSensitivity: 0.2,
    }),
  };

  state.cy.on("tap", "node, edge", (event) => showDetails(state, event.target.id()));
  state.search.addEventListener("input", () => applyFilters(state));
  state.support.addEventListener("input", () => applyFilters(state));
  state.relations.addEventListener("change", () => applyFilters(state));
  requireElement<HTMLButtonElement>("fit-graph").addEventListener("click", () => {
    state.cy.fit(undefined, 48);
  });
  requireElement<HTMLButtonElement>("reset-graph").addEventListener("click", () => {
    state.search.value = "";
    state.support.value = "1";
    state.relations.checked = true;
    applyFilters(state);
    state.cy.fit(undefined, 48);
  });
  applyFilters(state);
}

const graphStyles: cytoscape.StylesheetJson = [
  {
    selector: "node",
    style: {
      "background-color": "#006b5f",
      color: "#172121",
      label: "data(label)",
      "font-family": "Georgia, serif",
      "font-size": 14,
      "text-valign": "bottom",
      "text-margin-y": 8,
      width: 42,
      height: 42,
      "border-color": "#ffffff",
      "border-width": 3,
    },
  },
  {
    selector: "node:selected",
    style: { "border-color": "#d95d39", "border-width": 5 },
  },
  {
    selector: "edge",
    style: {
      width: 2,
      "line-color": "#7a7a72",
      "target-arrow-color": "#7a7a72",
      "target-arrow-shape": "triangle",
      "curve-style": "bezier",
      label: "data(label)",
      "font-size": 11,
      "text-background-color": "#f4f1e8",
      "text-background-opacity": 1,
      "text-background-padding": "3px",
    },
  },
  {
    selector: "edge[subtype]",
    style: { "line-style": "dashed", "line-color": "#006b5f" },
  },
  {
    selector: ".filtered",
    style: { display: "none" },
  },
];

/** Converts canonical nodes, relation types, and is-a links to Cytoscape elements. */
function toElements(types: CanonicalType[]): ElementDefinition[] {
  const nodes = types
    .filter(({ kind }) => kind === "NodeType")
    .map((type) => ({
      data: {
        id: type.id,
        label: type.label,
        definition: type.definition,
        support: type.supportCount,
        aliases: type.aliases.join(", "),
        kind: type.kind,
      },
    }));
  const relationEdges = types
    .filter((type) => type.kind === "RelType" && type.domain !== undefined && type.range !== undefined)
    .map((type) => ({
      data: {
        id: type.id,
        source: type.domain,
        target: type.range,
        label: type.label,
        definition: type.definition,
        support: type.supportCount,
        kind: type.kind,
      },
    }));
  const subtypeEdges = types
    .filter((type) => type.kind === "NodeType" && type.parent !== undefined)
    .map((type) => ({
      data: {
        id: `parent-${type.id}`,
        source: type.id,
        target: type.parent,
        label: "is-a",
        definition: `${type.label} is a subtype`,
        support: type.supportCount,
        kind: "Subtype",
        subtype: true,
      },
    }));
  return [...nodes, ...relationEdges, ...subtypeEdges];
}

/** Applies all filters together and announces the visible graph size. */
function applyFilters(state: GraphState): void {
  const query = state.search.value.trim().toLocaleLowerCase("en");
  const minimumSupport = Number(state.support.value);
  state.supportValue.textContent = String(minimumSupport);
  state.cy.batch(() => {
    state.cy.elements().removeClass("filtered");
    state.cy.nodes().forEach((node) => {
      const label = String(node.data("label")).toLocaleLowerCase("en");
      const aliases = String(node.data("aliases") ?? "").toLocaleLowerCase("en");
      const visible = Number(node.data("support")) >= minimumSupport
        && (query.length === 0 || label.includes(query) || aliases.includes(query));
      if (!visible) {
        node.addClass("filtered");
        node.connectedEdges().addClass("filtered");
      }
    });
    if (!state.relations.checked) {
      state.cy.edges('[kind = "RelType"]').addClass("filtered");
    }
  });
  const visibleNodes = state.cy.nodes().not(".filtered").length;
  const visibleEdges = state.cy.edges().not(".filtered").length;
  state.status.textContent = `${visibleNodes} types and ${visibleEdges} relations visible`;
}

/** Shows escaped data already rendered by textContent in the details region. */
function showDetails(state: GraphState, elementId: string): void {
  const element = state.cy.getElementById(elementId);
  const label = String(element.data("label") ?? "Unknown");
  const definition = String(element.data("definition") ?? "No definition available.");
  const support = String(element.data("support") ?? "0");
  state.details.replaceChildren(
    createTextElement("h3", label),
    createTextElement("p", definition),
    createTextElement("p", `Support: ${support}`),
  );
}

/** Reads the safely serialized ontology payload from the report document. */
function readOntology(): Ontology {
  const payload = requireElement<HTMLScriptElement>("ontology-data").textContent;
  if (payload === null) {
    throw new Error("Ontology report data is missing");
  }
  return JSON.parse(payload) as Ontology;
}

/** Returns an element by id or fails with a useful initialization error. */
function requireElement<ElementType extends HTMLElement>(id: string): ElementType {
  const element = document.getElementById(id);
  if (element === null) {
    throw new Error(`Report element not found: ${id}`);
  }
  return element as ElementType;
}

/** Creates a text-only element so graph data never becomes markup. */
function createTextElement(tagName: "h3" | "p", text: string): HTMLElement {
  const element = document.createElement(tagName);
  element.textContent = text;
  return element;
}

initializeReport();