// Generated by GitHub Copilot

import { createWebApp } from "./web/app.js";
import { readWebRuntimeConfig } from "./web/runtime-config.js";

/** Starts the local web application and performs graceful shutdown. */
async function main(): Promise<void> {
  const config = readWebRuntimeConfig();
  const app = await createWebApp({ config });
  const shutdown = async (): Promise<void> => {
    await app.close();
    process.exitCode = 0;
  };
  process.once("SIGINT", () => void shutdown());
  process.once("SIGTERM", () => void shutdown());
  await app.listen({ host: config.host, port: config.port });
  process.stdout.write(`Ontology Workbench: http://${config.host}:${config.port}\n`);
}

await main();