// Generated by GitHub Copilot

import cytoscape, { type Core, type ElementDefinition } from "cytoscape";
import type { CanonicalType, Ontology, Progress } from "ontology-extractor";

interface RuntimeConfig {
	provider: { provider: string; chatModel: string; embeddingModel: string };
	limits: { maxFiles: number; maxFileBytes: number; maxTotalBytes: number };
}

interface JobSnapshot {
	id: string;
	status: "running" | "done" | "error" | "cancelled";
	progress: Progress;
	error?: string;
}

const elements = {
	provider: requireElement<HTMLElement>("provider-summary"),
	input: requireElement<HTMLInputElement>("documents"),
	dropZone: requireElement<HTMLElement>("drop-zone"),
	fileList: requireElement<HTMLUListElement>("file-list"),
	extract: requireElement<HTMLButtonElement>("extract"),
	cancel: requireElement<HTMLButtonElement>("cancel"),
	status: requireElement<HTMLElement>("status"),
	progress: requireElement<HTMLProgressElement>("progress"),
	empty: requireElement<HTMLElement>("empty"),
	results: requireElement<HTMLElement>("results"),
	graphTab: requireElement<HTMLButtonElement>("graph-tab"),
	jsonTab: requireElement<HTMLButtonElement>("json-tab"),
	graphPanel: requireElement<HTMLElement>("graph-panel"),
	jsonPanel: requireElement<HTMLElement>("json-panel"),
	graph: requireElement<HTMLElement>("ontology-graph"),
	typeTable: requireElement<HTMLTableSectionElement>("type-table-body"),
	json: requireElement<HTMLElement>("json-output"),
	download: requireElement<HTMLButtonElement>("download"),
};

let selectedFiles: File[] = [];
let activeJobId: string | undefined;
let eventSource: EventSource | undefined;
let ontology: Ontology | undefined;
let graph: Core | undefined;
let runtimeConfig: RuntimeConfig | undefined;

/** Initializes configuration, input controls, tabs, and drag/drop. */
async function initialize(): Promise<void> {
	runtimeConfig = await requestJson<RuntimeConfig>("/api/config");
	elements.provider.textContent = `${runtimeConfig.provider.provider} · ${runtimeConfig.provider.chatModel}`;
	elements.input.addEventListener("change", () => setFiles([...elements.input.files ?? []]));
	elements.extract.addEventListener("click", () => void startExtraction());
	elements.cancel.addEventListener("click", () => void cancelExtraction());
	elements.download.addEventListener("click", downloadOntology);
	elements.graphTab.addEventListener("click", () => selectTab("graph"));
	elements.jsonTab.addEventListener("click", () => selectTab("json"));
	for (const eventName of ["dragenter", "dragover"]) {
		elements.dropZone.addEventListener(eventName, (event) => {
			event.preventDefault();
			elements.dropZone.classList.add("dragging");
		});
	}
	for (const eventName of ["dragleave", "drop"]) {
		elements.dropZone.addEventListener(eventName, (event) => {
			event.preventDefault();
			elements.dropZone.classList.remove("dragging");
		});
	}
	elements.dropZone.addEventListener("drop", (event) => {
		setFiles([...event.dataTransfer?.files ?? []]);
	});
}

/** Replaces the current upload selection after client-side limit validation. */
function setFiles(files: File[]): void {
	if (runtimeConfig === undefined) {
		return;
	}
	const config = runtimeConfig;
	const accepted = files.filter((file) => isSupportedFile(file.name));
	const totalBytes = accepted.reduce((total, file) => total + file.size, 0);
	const invalid = files.length !== accepted.length
		|| accepted.length > config.limits.maxFiles
		|| accepted.some((file) => file.size > config.limits.maxFileBytes)
		|| totalBytes > config.limits.maxTotalBytes;
	if (invalid) {
		showError("Some files are unsupported or exceed the configured upload limits.");
		return;
	}
	selectedFiles = accepted;
	renderFiles();
	elements.extract.disabled = selectedFiles.length === 0 || activeJobId !== undefined;
	elements.status.classList.remove("error");
	const documentLabel = selectedFiles.length === 1 ? "document" : "documents";
	elements.status.textContent = selectedFiles.length === 0
		? "Select one or more documents to begin."
		: `${selectedFiles.length} ${documentLabel} ready.`;
}

/** Renders selected file metadata with per-file removal buttons. */
function renderFiles(): void {
	elements.fileList.replaceChildren(...selectedFiles.map((file, index) => {
		const item = document.createElement("li");
		const label = document.createElement("span");
		label.textContent = `${file.name} · ${formatBytes(file.size)}`;
		const remove = document.createElement("button");
		remove.type = "button";
		remove.textContent = "Remove";
		remove.setAttribute("aria-label", `Remove ${file.name}`);
		remove.addEventListener("click", () => {
			selectedFiles.splice(index, 1);
			renderFiles();
			elements.extract.disabled = selectedFiles.length === 0;
		});
		item.append(label, remove);
		return item;
	}));
}

/** Uploads selected files and switches to event-driven job progress. */
async function startExtraction(): Promise<void> {
	if (selectedFiles.length === 0) {
		return;
	}
	resetResults();
	setRunning(true);
	elements.status.textContent = "Uploading documents…";
	const body = new FormData();
	selectedFiles.forEach((file) => body.append("documents", file, file.name));
	try {
		const response = await fetch("/api/jobs", { method: "POST", body });
		if (!response.ok) {
			throw new Error(await readApiError(response));
		}
		const snapshot = await response.json() as JobSnapshot;
		activeJobId = snapshot.id;
		updateProgress(snapshot.progress);
		connectEvents(snapshot.id);
	} catch (error) {
		setRunning(false);
		showError(error instanceof Error ? error.message : "Upload failed");
	}
}

/** Opens one SSE stream and handles every terminal path exactly once. */
function connectEvents(jobId: string): void {
	eventSource?.close();
	eventSource = new EventSource(`/api/jobs/${encodeURIComponent(jobId)}/events`);
	eventSource.addEventListener("progress", (event) => {
		const snapshot = JSON.parse(event.data) as JobSnapshot;
		updateProgress(snapshot.progress);
	});
	eventSource.addEventListener("done", () => void completeExtraction(jobId));
	eventSource.addEventListener("cancelled", () => finishWithMessage("Extraction cancelled."));
	eventSource.addEventListener("error", (event) => {
		if (event instanceof MessageEvent) {
			const payload = JSON.parse(event.data) as { message?: string };
			finishWithMessage(payload.message ?? "Extraction failed.", true);
		}
	});
}

/** Fetches the final ontology only after the done event. */
async function completeExtraction(jobId: string): Promise<void> {
	try {
		ontology = await requestJson<Ontology>(`/api/jobs/${encodeURIComponent(jobId)}/ontology`);
		renderOntology(ontology);
		finishWithMessage(`Ontology ready: ${ontology.stats.typeCount} types extracted.`);
	} catch (error) {
		finishWithMessage(error instanceof Error ? error.message : "Could not load ontology.", true);
	}
}

/** Requests cooperative cancellation for the current job. */
async function cancelExtraction(): Promise<void> {
	if (activeJobId === undefined) {
		return;
	}
	elements.cancel.disabled = true;
	await fetch(`/api/jobs/${encodeURIComponent(activeJobId)}`, { method: "DELETE" });
}

/** Updates phase text and derives a stable percentage from the available counters. */
function updateProgress(progress: Progress): void {
	const chunkPercent = progress.chunks.total === 0
		? 0
		: (progress.chunks.processed / progress.chunks.total) * 70;
	const phaseBonus: Record<string, number> = {
		idle: 0,
		chunking: 5,
		extracting: 10,
		canonicalizing: 82,
		consolidating: 90,
		emitting: 96,
		done: 100,
		error: 100,
		cancelled: 100,
	};
	const percent = Math.min(100, Math.max(phaseBonus[progress.phase] ?? 0, chunkPercent));
	elements.progress.value = percent;
	elements.progress.textContent = `${Math.round(percent)}%`;
	elements.status.textContent = `${formatPhase(progress.phase)} · ${progress.chunks.processed}/${progress.chunks.total} chunks · ${progress.canonicalTypes} types`;
}

/** Renders graph and JSON from the same ontology value. */
function renderOntology(value: Ontology): void {
	elements.empty.hidden = true;
	elements.results.hidden = false;
	elements.json.textContent = JSON.stringify(value, null, 2);
	renderTypeTable(value.types);
	graph?.destroy();
	graph = cytoscape({
		container: elements.graph,
		elements: toGraphElements(value.types),
		style: [
			{ selector: "node", style: { label: "data(label)", "background-color": "#006b5f", color: "#172121", "text-valign": "bottom", "text-margin-y": 8, "font-family": "Georgia, serif", width: 44, height: 44 } },
			{ selector: "edge", style: { label: "data(label)", "line-color": "#7a7a72", "target-arrow-color": "#7a7a72", "target-arrow-shape": "triangle", "curve-style": "bezier", "font-size": 11, "text-background-color": "#fff", "text-background-opacity": 1 } },
		],
		layout: { name: "cose", animate: false, randomize: false },
	});
	selectTab("graph");
}

/** Renders a text-only ontology equivalent for keyboard and assistive technology users. */
function renderTypeTable(types: CanonicalType[]): void {
	elements.typeTable.replaceChildren(...types.map((type) => {
		const row = document.createElement("tr");
		for (const value of [type.label, type.kind, type.definition, String(type.supportCount)]) {
			const cell = document.createElement("td");
			cell.textContent = value;
			row.append(cell);
		}
		return row;
	}));
}

/** Converts TBox nodes, relation types, and parent links into graph elements. */
function toGraphElements(types: CanonicalType[]): ElementDefinition[] {
	const nodes = types.filter(({ kind }) => kind === "NodeType").map((type) => ({
		data: { id: type.id, label: type.label },
	}));
	const relations = types
		.filter((type) => type.kind === "RelType" && type.domain !== undefined && type.range !== undefined)
		.map((type) => ({ data: { id: type.id, source: type.domain, target: type.range, label: type.label } }));
	const parents = types
		.filter((type) => type.kind === "NodeType" && type.parent !== undefined)
		.map((type) => ({ data: { id: `parent-${type.id}`, source: type.id, target: type.parent, label: "is-a" } }));
	return [...nodes, ...relations, ...parents];
}

/** Switches tabs while preserving ARIA state and Cytoscape dimensions. */
function selectTab(tab: "graph" | "json"): void {
	const graphSelected = tab === "graph";
	elements.graphTab.setAttribute("aria-selected", String(graphSelected));
	elements.jsonTab.setAttribute("aria-selected", String(!graphSelected));
	elements.graphPanel.hidden = !graphSelected;
	elements.jsonPanel.hidden = graphSelected;
	if (graphSelected) {
		requestAnimationFrame(() => {
			graph?.resize();
			graph?.fit(undefined, 48);
		});
	}
}

/** Downloads the current ontology without server round-trips. */
function downloadOntology(): void {
	if (ontology === undefined) {
		return;
	}
	const url = URL.createObjectURL(new Blob([`${JSON.stringify(ontology, null, 2)}\n`], { type: "application/json" }));
	const link = document.createElement("a");
	link.href = url;
	link.download = "ontology.json";
	link.click();
	URL.revokeObjectURL(url);
}

/** Resets result views before a new isolated extraction. */
function resetResults(): void {
	ontology = undefined;
	graph?.destroy();
	graph = undefined;
	elements.results.hidden = true;
	elements.empty.hidden = false;
	elements.json.textContent = "";
}

/** Updates controls for active versus terminal job states. */
function setRunning(running: boolean): void {
	elements.extract.disabled = running || selectedFiles.length === 0;
	elements.cancel.hidden = !running;
	elements.cancel.disabled = false;
	elements.input.disabled = running;
	elements.progress.hidden = !running;
}

/** Closes streaming resources and announces one terminal message. */
function finishWithMessage(message: string, error = false): void {
	eventSource?.close();
	eventSource = undefined;
	activeJobId = undefined;
	setRunning(false);
	elements.progress.hidden = true;
	elements.status.classList.toggle("error", error);
	elements.status.textContent = message;
}

/** Displays a non-terminal validation or network error. */
function showError(message: string): void {
	elements.status.classList.add("error");
	elements.status.textContent = message;
}

/** Fetches JSON and normalizes API error payloads. */
async function requestJson<T>(url: string): Promise<T> {
	const response = await fetch(url, { headers: { Accept: "application/json" } });
	if (!response.ok) {
		throw new Error(await readApiError(response));
	}
	return response.json() as Promise<T>;
}

/** Reads a bounded API error message. */
async function readApiError(response: Response): Promise<string> {
	try {
		const payload = await response.json() as { error?: unknown };
		return typeof payload.error === "string" ? payload.error : `Request failed (${response.status})`;
	} catch {
		return `Request failed (${response.status})`;
	}
}

/** Checks only the extensions supported by the server MVP. */
function isSupportedFile(name: string): boolean {
	return /\.(?:txt|md|markdown|html?|htm)$/i.test(name);
}

/** Formats bytes for compact file-list display. */
function formatBytes(bytes: number): string {
	return bytes < 1_024 ? `${bytes} B` : `${(bytes / 1_024).toFixed(1)} KiB`;
}

/** Converts pipeline phase identifiers to concise UI text. */
function formatPhase(phase: string): string {
	return phase.charAt(0).toLocaleUpperCase("en") + phase.slice(1);
}

/** Returns a required DOM element or fails fast during initialization. */
function requireElement<ElementType extends HTMLElement>(id: string): ElementType {
	const element = document.getElementById(id);
	if (element === null) {
		throw new Error(`Application element not found: ${id}`);
	}
	return element as ElementType;
}

try {
	await initialize();
} catch (error: unknown) {
	showError(error instanceof Error ? error.message : "Application initialization failed");
}