// Generated by GitHub Copilot

import cytoscape, { type Core, type ElementDefinition } from "cytoscape";
import type { AttributeDefinition, CanonicalType, ExtractionAccuracy, Ontology, Progress } from "ontology-extractor";

interface RuntimeConfig {
	provider: { provider: string; chatModel: string; embeddingModel: string };
	limits: { maxFiles: number; maxFileBytes: number; maxTotalBytes: number };
	settings: WebExtractorSettings;
}

interface WebExtractorSettings {
	chunking: { strategy: "recursive" | "markdown" | "html"; chunkSize: number; chunkOverlap: number };
	extraction: { concurrency: number; accuracy: ExtractionAccuracy; requireExamples: boolean; systemPrompt?: string; prompt?: string };
	canonicalization: { topK: number; autoMatchThreshold: number; autoNewThreshold: number; useLlmForAmbiguous: boolean; systemPrompt?: string; prompt?: string };
	output: { supportCountThreshold: number };
}

interface JobSnapshot {
	id: string;
	status: "running" | "done" | "error" | "cancelled";
	progress: Progress;
	error?: string;
}

const elements = {
	provider: requireElement<HTMLElement>("provider-summary"),
	input: requireElement<HTMLInputElement>("documents"),
	dropZone: requireElement<HTMLElement>("drop-zone"),
	fileList: requireElement<HTMLUListElement>("file-list"),
	extract: requireElement<HTMLButtonElement>("extract"),
	cancel: requireElement<HTMLButtonElement>("cancel"),
	status: requireElement<HTMLElement>("status"),
	progress: requireElement<HTMLProgressElement>("progress"),
	empty: requireElement<HTMLElement>("empty"),
	results: requireElement<HTMLElement>("results"),
	graphTab: requireElement<HTMLButtonElement>("graph-tab"),
	jsonTab: requireElement<HTMLButtonElement>("json-tab"),
	graphPanel: requireElement<HTMLElement>("graph-panel"),
	jsonPanel: requireElement<HTMLElement>("json-panel"),
	graph: requireElement<HTMLElement>("ontology-graph"),
	graphDetails: requireElement<HTMLElement>("graph-details"),
	typeTable: requireElement<HTMLTableSectionElement>("type-table-body"),
	json: requireElement<HTMLElement>("json-output"),
	download: requireElement<HTMLButtonElement>("download"),
	chunkingStrategy: requireElement<HTMLSelectElement>("chunking-strategy"),
	chunkSize: requireElement<HTMLInputElement>("chunk-size"),
	chunkOverlap: requireElement<HTMLInputElement>("chunk-overlap"),
	extractionConcurrency: requireElement<HTMLInputElement>("extraction-concurrency"),
	extractionAccuracy: requireElement<HTMLSelectElement>("extraction-accuracy"),
	requireExamples: requireElement<HTMLInputElement>("require-examples"),
	topK: requireElement<HTMLInputElement>("top-k"),
	autoMatchThreshold: requireElement<HTMLInputElement>("auto-match-threshold"),
	autoNewThreshold: requireElement<HTMLInputElement>("auto-new-threshold"),
	useLlmForAmbiguous: requireElement<HTMLInputElement>("use-llm-for-ambiguous"),
	supportCountThreshold: requireElement<HTMLInputElement>("support-count-threshold"),
	extractionSystemPrompt: requireElement<HTMLTextAreaElement>("extraction-system-prompt"),
	extractionPrompt: requireElement<HTMLTextAreaElement>("extraction-prompt"),
	canonicalizationSystemPrompt: requireElement<HTMLTextAreaElement>("canonicalization-system-prompt"),
	canonicalizationPrompt: requireElement<HTMLTextAreaElement>("canonicalization-prompt"),
};

const promptExamples = {
	extractionSystem: "Extract ontology schema candidates for regulated manufacturing SOPs. Prefer process steps, controlled areas, roles, materials, equipment, and compliance evidence. Return only concepts explicitly grounded in the fragment.",
	extractionPrompt: JSON.stringify({
		instruction: "Extract NodeType and RelType candidates from this fragment. Include examples quoted from the text.",
		text: "Paste a representative document fragment here when overriding the full prompt.",
	}, null, 2),
	canonicalizationSystem: "Merge candidates only when they name the same GMP or manufacturing concept. Keep equipment, roles, rooms, documents, and process phases separate when the distinction affects compliance.",
	canonicalizationPrompt: JSON.stringify({
		instruction: "Classify the candidate as MATCH, SUBTYPE, or NEW. Use NEW when the evidence is not exact enough.",
		candidate: { label: "Cleanroom Gowning", kind: "NodeType", definition: "Procedure for entering controlled areas." },
		neighbors: [{ type: { id: "type-0001", label: "Gowning Procedure" }, score: 0.78 }],
	}, null, 2),
} as const;

let selectedFiles: File[] = [];
let activeJobId: string | undefined;
let eventSource: EventSource | undefined;
let ontology: Ontology | undefined;
let graph: Core | undefined;
let runtimeConfig: RuntimeConfig | undefined;

/** Initializes configuration, input controls, tabs, and drag/drop. */
async function initialize(): Promise<void> {
	runtimeConfig = await requestJson<RuntimeConfig>("/api/config");
	elements.provider.textContent = `${runtimeConfig.provider.provider} · ${runtimeConfig.provider.chatModel}`;
	populateSettings(runtimeConfig.settings);
	elements.input.addEventListener("change", () => setFiles([...elements.input.files ?? []]));
	elements.extract.addEventListener("click", () => void startExtraction());
	elements.cancel.addEventListener("click", () => void cancelExtraction());
	elements.download.addEventListener("click", downloadOntology);
	elements.graphTab.addEventListener("click", () => selectTab("graph"));
	elements.jsonTab.addEventListener("click", () => selectTab("json"));
	for (const eventName of ["dragenter", "dragover"]) {
		elements.dropZone.addEventListener(eventName, (event) => {
			event.preventDefault();
			elements.dropZone.classList.add("dragging");
		});
	}
	for (const eventName of ["dragleave", "drop"]) {
		elements.dropZone.addEventListener(eventName, (event) => {
			event.preventDefault();
			elements.dropZone.classList.remove("dragging");
		});
	}
	elements.dropZone.addEventListener("drop", (event) => {
		setFiles([...event.dataTransfer?.files ?? []]);
	});
	for (const button of document.querySelectorAll<HTMLButtonElement>("[data-prompt-example]")) {
		button.addEventListener("click", () => applyPromptExample(button));
	}
}

/** Populates setting controls from server defaults. */
function populateSettings(settings: WebExtractorSettings): void {
	elements.chunkingStrategy.value = settings.chunking.strategy;
	elements.chunkSize.value = String(settings.chunking.chunkSize);
	elements.chunkOverlap.value = String(settings.chunking.chunkOverlap);
	elements.extractionConcurrency.value = String(settings.extraction.concurrency);
	elements.extractionAccuracy.value = settings.extraction.accuracy;
	elements.requireExamples.checked = settings.extraction.requireExamples;
	elements.topK.value = String(settings.canonicalization.topK);
	elements.autoMatchThreshold.value = String(settings.canonicalization.autoMatchThreshold);
	elements.autoNewThreshold.value = String(settings.canonicalization.autoNewThreshold);
	elements.useLlmForAmbiguous.checked = settings.canonicalization.useLlmForAmbiguous;
	elements.supportCountThreshold.value = String(settings.output.supportCountThreshold);
}

/** Copies a safe example into one prompt override field. */
function applyPromptExample(button: HTMLButtonElement): void {
	const target = button.dataset.promptTarget;
	const example = button.dataset.promptExample;
	if (example === undefined) {
		return;
	}
	const text = promptExamples[example as keyof typeof promptExamples];
	if (target === "extraction-system") {
		elements.extractionSystemPrompt.value = text;
	} else if (target === "extraction-prompt") {
		elements.extractionPrompt.value = text;
	} else if (target === "canonicalization-system") {
		elements.canonicalizationSystemPrompt.value = text;
	} else if (target === "canonicalization-prompt") {
		elements.canonicalizationPrompt.value = text;
	}
}

/** Replaces the current upload selection after client-side limit validation. */
function setFiles(files: File[]): void {
	if (runtimeConfig === undefined) {
		return;
	}
	const config = runtimeConfig;
	const accepted = files.filter((file) => isSupportedFile(file.name));
	const totalBytes = accepted.reduce((total, file) => total + file.size, 0);
	const invalid = files.length !== accepted.length
		|| accepted.length > config.limits.maxFiles
		|| accepted.some((file) => file.size > config.limits.maxFileBytes)
		|| totalBytes > config.limits.maxTotalBytes;
	if (invalid) {
		showError("Some files are unsupported or exceed the configured upload limits.");
		return;
	}
	selectedFiles = accepted;
	renderFiles();
	elements.extract.disabled = selectedFiles.length === 0 || activeJobId !== undefined;
	elements.status.classList.remove("error");
	const documentLabel = selectedFiles.length === 1 ? "document" : "documents";
	elements.status.textContent = selectedFiles.length === 0
		? "Select one or more documents to begin."
		: `${selectedFiles.length} ${documentLabel} ready.`;
}

/** Renders selected file metadata with per-file removal buttons. */
function renderFiles(): void {
	elements.fileList.replaceChildren(...selectedFiles.map((file, index) => {
		const item = document.createElement("li");
		const label = document.createElement("span");
		label.textContent = `${file.name} · ${formatBytes(file.size)}`;
		const remove = document.createElement("button");
		remove.type = "button";
		remove.textContent = "Remove";
		remove.setAttribute("aria-label", `Remove ${file.name}`);
		remove.addEventListener("click", () => {
			selectedFiles.splice(index, 1);
			renderFiles();
			elements.extract.disabled = selectedFiles.length === 0;
		});
		item.append(label, remove);
		return item;
	}));
}

/** Uploads selected files and switches to event-driven job progress. */
async function startExtraction(): Promise<void> {
	if (selectedFiles.length === 0) {
		return;
	}
	resetResults();
	setRunning(true);
	elements.status.textContent = "Uploading documents…";
	const body = new FormData();
	body.append("settings", JSON.stringify(readSettings()));
	selectedFiles.forEach((file) => body.append("documents", file, file.name));
	try {
		const response = await fetch("/api/jobs", { method: "POST", body });
		if (!response.ok) {
			throw new Error(await readApiError(response));
		}
		const snapshot = await response.json() as JobSnapshot;
		activeJobId = snapshot.id;
		updateProgress(snapshot.progress);
		connectEvents(snapshot.id);
	} catch (error) {
		setRunning(false);
		showError(error instanceof Error ? error.message : "Upload failed");
	}
}

/** Reads extractor settings from accessible form controls. */
function readSettings(): WebExtractorSettings {
	return {
		chunking: {
			strategy: elements.chunkingStrategy.value as WebExtractorSettings["chunking"]["strategy"],
			chunkSize: readNumber(elements.chunkSize),
			chunkOverlap: readNumber(elements.chunkOverlap),
		},
		extraction: {
			concurrency: readNumber(elements.extractionConcurrency),
			accuracy: elements.extractionAccuracy.value as ExtractionAccuracy,
			requireExamples: elements.requireExamples.checked,
			...readOptionalPrompt("systemPrompt", elements.extractionSystemPrompt),
			...readOptionalPrompt("prompt", elements.extractionPrompt),
		},
		canonicalization: {
			topK: readNumber(elements.topK),
			autoMatchThreshold: readNumber(elements.autoMatchThreshold),
			autoNewThreshold: readNumber(elements.autoNewThreshold),
			useLlmForAmbiguous: elements.useLlmForAmbiguous.checked,
			...readOptionalPrompt("systemPrompt", elements.canonicalizationSystemPrompt),
			...readOptionalPrompt("prompt", elements.canonicalizationPrompt),
		},
		output: { supportCountThreshold: readNumber(elements.supportCountThreshold) },
	};
}

/** Reads one numeric input after browser constraint validation. */
function readNumber(input: HTMLInputElement): number {
	return Number(input.value);
}

/** Omits blank prompt overrides so server defaults remain active. */
function readOptionalPrompt(key: "systemPrompt" | "prompt", input: HTMLTextAreaElement): Partial<Record<"systemPrompt" | "prompt", string>> {
	const value = input.value.trim();
	return value.length === 0 ? {} : { [key]: value };
}

/** Opens one SSE stream and handles every terminal path exactly once. */
function connectEvents(jobId: string): void {
	eventSource?.close();
	eventSource = new EventSource(`/api/jobs/${encodeURIComponent(jobId)}/events`);
	eventSource.addEventListener("progress", (event) => {
		const snapshot = JSON.parse(event.data) as JobSnapshot;
		updateProgress(snapshot.progress);
	});
	eventSource.addEventListener("done", () => void completeExtraction(jobId));
	eventSource.addEventListener("cancelled", () => finishWithMessage("Extraction cancelled."));
	eventSource.addEventListener("error", (event) => {
		if (event instanceof MessageEvent) {
			const payload = JSON.parse(event.data) as { message?: string };
			finishWithMessage(payload.message ?? "Extraction failed.", true);
		}
	});
}

/** Fetches the final ontology only after the done event. */
async function completeExtraction(jobId: string): Promise<void> {
	try {
		ontology = await requestJson<Ontology>(`/api/jobs/${encodeURIComponent(jobId)}/ontology`);
		renderOntology(ontology);
		finishWithMessage(`Ontology ready: ${ontology.stats.typeCount} types extracted.`);
	} catch (error) {
		finishWithMessage(error instanceof Error ? error.message : "Could not load ontology.", true);
	}
}

/** Requests cooperative cancellation for the current job. */
async function cancelExtraction(): Promise<void> {
	if (activeJobId === undefined) {
		return;
	}
	elements.cancel.disabled = true;
	await fetch(`/api/jobs/${encodeURIComponent(activeJobId)}`, { method: "DELETE" });
}

/** Updates phase text and derives a stable percentage from the available counters. */
function updateProgress(progress: Progress): void {
	const chunkPercent = progress.chunks.total === 0
		? 0
		: (progress.chunks.processed / progress.chunks.total) * 70;
	const phaseBonus: Record<string, number> = {
		idle: 0,
		chunking: 5,
		extracting: 10,
		canonicalizing: 82,
		consolidating: 90,
		emitting: 96,
		done: 100,
		error: 100,
		cancelled: 100,
	};
	const percent = Math.min(100, Math.max(phaseBonus[progress.phase] ?? 0, chunkPercent));
	elements.progress.value = percent;
	elements.progress.textContent = `${Math.round(percent)}%`;
	elements.status.textContent = `${formatPhase(progress.phase)} · ${progress.chunks.processed}/${progress.chunks.total} chunks · ${progress.canonicalTypes} types`;
}

/** Renders graph and JSON from the same ontology value. */
function renderOntology(value: Ontology): void {
	elements.empty.hidden = true;
	elements.results.hidden = false;
	elements.json.textContent = JSON.stringify(value, null, 2);
	renderTypeTable(value.types);
	graph?.destroy();
	graph = cytoscape({
		container: elements.graph,
		elements: toGraphElements(value.types),
		style: [
			{ selector: "node", style: { label: "data(label)", "background-color": "#006b5f", color: "#172121", "text-valign": "bottom", "text-margin-y": 8, "font-family": "Georgia, serif", width: 44, height: 44 } },
			{ selector: "edge", style: { label: "data(label)", "line-color": "#7a7a72", "target-arrow-color": "#7a7a72", "target-arrow-shape": "triangle", "curve-style": "bezier", "font-size": 11, "text-background-color": "#fff", "text-background-opacity": 1 } },
		],
		layout: { name: "cose", animate: false, randomize: false },
	});
	graph.on("tap", "node, edge", (event) => showGraphDetails(event.target.id()));
	resetGraphDetails();
	selectTab("graph");
}

/** Renders a text-only ontology equivalent for keyboard and assistive technology users. */
function renderTypeTable(types: CanonicalType[]): void {
	elements.typeTable.replaceChildren(...types.map((type) => {
		const row = document.createElement("tr");
		for (const value of [type.label, type.kind, type.definition, formatAttributes(type), formatReferences(type), String(type.supportCount)]) {
			const cell = document.createElement("td");
			cell.textContent = value;
			row.append(cell);
		}
		return row;
	}));
}

/** Converts TBox nodes, relation types, and parent links into graph elements. */
function toGraphElements(types: CanonicalType[]): ElementDefinition[] {
	const nodes = types.filter(({ kind }) => kind === "NodeType").map((type) => ({
		data: { ...type, support: type.supportCount },
	}));
	const relations = types
		.filter((type) => type.kind === "RelType" && type.domain !== undefined && type.range !== undefined)
		.map((type) => ({ data: { ...type, source: type.domain, target: type.range, support: type.supportCount } }));
	const parents = types
		.filter((type) => type.kind === "NodeType" && type.parent !== undefined)
		.map((type) => ({ data: { id: `parent-${type.id}`, source: type.id, target: type.parent, label: "is-a", definition: `${type.label} is a subtype`, support: type.supportCount, kind: "Subtype" } }));
	return [...nodes, ...relations, ...parents];
}

/** Shows details for the selected graph element without treating ontology text as markup. */
function showGraphDetails(elementId: string): void {
	const element = graph?.getElementById(elementId);
	if (element === undefined || element.empty()) {
		resetGraphDetails();
		return;
	}
	const label = String(element.data("label") ?? "Unknown");
	const details = document.createElement("dl");
	appendDetail(details, "Kind", String(element.data("kind") ?? "Element"));
	appendDetail(details, "Definition", String(element.data("definition") ?? "No definition available."));
	appendDetail(details, "Attributes", formatAttributes(element.data() as Partial<CanonicalType>));
	appendDetail(details, "References", formatReferences(element.data() as Partial<CanonicalType>));
	appendDetail(details, "Category", optionalString(element.data("category")));
	appendDetail(details, "Primary key", optionalString(element.data("primaryKeyAttribute")));
	appendDetail(details, "Label attribute", optionalString(element.data("labelAttribute")));
	appendDetail(details, "Cardinality", formatCardinality(element.data() as Partial<CanonicalType>));
	appendDetail(details, "Aliases", formatStringList(element.data("aliases")));
	appendDetail(details, "Visual", formatVisual(element.data("visual")));
	appendDetail(details, "Provenance", formatProvenance(element.data("provenance")));
	appendDetail(details, "Support", String(element.data("support") ?? element.data("supportCount") ?? "0"));
	elements.graphDetails.replaceChildren(
		createTextElement("h3", label),
		details,
	);
}

/** Appends one labeled detail when a value is available. */
function appendDetail(list: HTMLDListElement, label: string, value: string): void {
	if (value.length === 0 || value === "none") {
		return;
	}
	const term = document.createElement("dt");
	term.textContent = label;
	const description = document.createElement("dd");
	description.textContent = value;
	list.append(term, description);
}

/** Formats ontology attributes with extracted value types when available. */
function formatAttributes(type: Partial<CanonicalType>): string {
	const definitions = type.attributeDefinitions ?? [];
	if (definitions.length > 0) {
		return definitions.map(formatAttributeDefinition).join("; ");
	}
	return formatStringList(type.attributes);
}

/** Formats one attribute definition as name, type, and flags. */
function formatAttributeDefinition(attribute: AttributeDefinition): string {
	const flags = [
		attribute.required === true ? "required" : "optional",
		attribute.indexed === true ? "indexed" : undefined,
		attribute.restricted === true ? "restricted" : undefined,
	].filter((value): value is string => value !== undefined);
	const description = attribute.description === undefined ? "" : ` - ${attribute.description}`;
	return `${attribute.label ?? attribute.name}: ${attribute.type ?? "STRING"} (${flags.join(", ")})${description}`;
}

/** Formats relation endpoints and subtype references. */
function formatReferences(type: Partial<CanonicalType>): string {
	if (type.kind === "RelType") {
		return `${type.domain ?? "?"} -> ${type.range ?? "?"}`;
	}
	return type.parent === undefined ? "" : `is-a ${type.parent}`;
}

/** Formats from/to cardinality for relation types. */
function formatCardinality(type: Partial<CanonicalType>): string {
	return type.fromCardinality === undefined && type.toCardinality === undefined
		? ""
		: `${type.fromCardinality ?? "?"} -> ${type.toCardinality ?? "?"}`;
}

/** Formats provenance entries as document and chunk references. */
function formatProvenance(value: unknown): string {
	if (!Array.isArray(value) || value.length === 0) {
		return "";
	}
	return value.map((item) => {
		if (typeof item !== "object" || item === null) {
			return "unknown";
		}
		const provenance = item as { documentId?: unknown; chunkIndex?: unknown };
		return `${String(provenance.documentId ?? "unknown")}#${String(provenance.chunkIndex ?? "?")}`;
	}).join(", ");
}

/** Formats optional visual metadata without rendering untrusted colors as CSS. */
function formatVisual(value: unknown): string {
	if (typeof value !== "object" || value === null) {
		return "";
	}
	const visual = value as { icon?: unknown; backColor?: unknown; textColor?: unknown };
	return [
		visual.icon === undefined ? undefined : `icon=${String(visual.icon)}`,
		visual.backColor === undefined ? undefined : `backColor=${String(visual.backColor)}`,
		visual.textColor === undefined ? undefined : `textColor=${String(visual.textColor)}`,
	].filter((item): item is string => item !== undefined).join(", ");
}

/** Formats a string array or returns an empty value. */
function formatStringList(value: unknown): string {
	return Array.isArray(value) && value.length > 0 ? value.map(String).join(", ") : "";
}

/** Converts optional unknown data to display text. */
function optionalString(value: unknown): string {
	return value === undefined || value === null || value === "" ? "" : String(value);
}

/** Restores the graph details placeholder for new or empty ontology states. */
function resetGraphDetails(): void {
	elements.graphDetails.replaceChildren(
		createTextElement("h3", "Selection details"),
		createTextElement("p", "Select a type or relation in the graph."),
	);
}

/** Creates a text-only details element for ontology-derived content. */
function createTextElement(tagName: "h3" | "p", text: string): HTMLElement {
	const element = document.createElement(tagName);
	element.textContent = text;
	return element;
}

/** Switches tabs while preserving ARIA state and Cytoscape dimensions. */
function selectTab(tab: "graph" | "json"): void {
	const graphSelected = tab === "graph";
	elements.graphTab.setAttribute("aria-selected", String(graphSelected));
	elements.jsonTab.setAttribute("aria-selected", String(!graphSelected));
	elements.graphPanel.hidden = !graphSelected;
	elements.jsonPanel.hidden = graphSelected;
	if (graphSelected) {
		requestAnimationFrame(() => {
			graph?.resize();
			graph?.fit(undefined, 48);
		});
	}
}

/** Downloads the current ontology without server round-trips. */
function downloadOntology(): void {
	if (ontology === undefined) {
		return;
	}
	const url = URL.createObjectURL(new Blob([`${JSON.stringify(ontology, null, 2)}\n`], { type: "application/json" }));
	const link = document.createElement("a");
	link.href = url;
	link.download = "ontology.json";
	link.click();
	URL.revokeObjectURL(url);
}

/** Resets result views before a new isolated extraction. */
function resetResults(): void {
	ontology = undefined;
	graph?.destroy();
	graph = undefined;
	resetGraphDetails();
	elements.results.hidden = true;
	elements.empty.hidden = false;
	elements.json.textContent = "";
}

/** Updates controls for active versus terminal job states. */
function setRunning(running: boolean): void {
	elements.extract.disabled = running || selectedFiles.length === 0;
	elements.cancel.hidden = !running;
	elements.cancel.disabled = false;
	elements.input.disabled = running;
	for (const control of document.querySelectorAll<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement | HTMLButtonElement>(".setting-control")) {
		control.disabled = running;
	}
	elements.progress.hidden = !running;
}

/** Closes streaming resources and announces one terminal message. */
function finishWithMessage(message: string, error = false): void {
	eventSource?.close();
	eventSource = undefined;
	activeJobId = undefined;
	setRunning(false);
	elements.progress.hidden = true;
	elements.status.classList.toggle("error", error);
	elements.status.textContent = message;
}

/** Displays a non-terminal validation or network error. */
function showError(message: string): void {
	elements.status.classList.add("error");
	elements.status.textContent = message;
}

/** Fetches JSON and normalizes API error payloads. */
async function requestJson<T>(url: string): Promise<T> {
	const response = await fetch(url, { headers: { Accept: "application/json" } });
	if (!response.ok) {
		throw new Error(await readApiError(response));
	}
	return response.json() as Promise<T>;
}

/** Reads a bounded API error message. */
async function readApiError(response: Response): Promise<string> {
	try {
		const payload = await response.json() as { error?: unknown };
		return typeof payload.error === "string" ? payload.error : `Request failed (${response.status})`;
	} catch {
		return `Request failed (${response.status})`;
	}
}

/** Checks only the extensions supported by the server MVP. */
function isSupportedFile(name: string): boolean {
	return /\.(?:txt|md|markdown|html?|htm|pdf)$/i.test(name);
}

/** Formats bytes for compact file-list display. */
function formatBytes(bytes: number): string {
	return bytes < 1_024 ? `${bytes} B` : `${(bytes / 1_024).toFixed(1)} KiB`;
}

/** Converts pipeline phase identifiers to concise UI text. */
function formatPhase(phase: string): string {
	return phase.charAt(0).toLocaleUpperCase("en") + phase.slice(1);
}

/** Returns a required DOM element or fails fast during initialization. */
function requireElement<ElementType extends HTMLElement>(id: string): ElementType {
	const element = document.getElementById(id);
	if (element === null) {
		throw new Error(`Application element not found: ${id}`);
	}
	return element as ElementType;
}

try {
	await initialize();
} catch (error: unknown) {
	showError(error instanceof Error ? error.message : "Application initialization failed");
}