// Generated by GitHub Copilot

import { LlmAdapterError, SchemaValidationError } from "../errors.js";
import type {
  AttributeDefinition,
  AttributeValueType,
  Candidate,
  Cardinality,
  DocumentChunk,
  ExtractionAccuracy,
  ExtractionPrompt,
  ExtractedCandidate,
  JsonSchema,
  LlmAdapter,
} from "../types.js";

export interface ExtractionOptions {
  concurrency: number;
  accuracy: ExtractionAccuracy;
  requireExamples: boolean;
  systemPrompt?: string;
  prompt?: ExtractionPrompt;
}

export interface ExtractionHooks {
  /** Reports completion of one chunk, including isolated failures. */
  onChunkProcessed?(candidateCount: number): void;
  /** Reports each extraction request sent to the LLM. */
  onLlmCall?(): void;
}

/** Extracts chunk candidates with bounded concurrency and isolated failures. */
export async function extractChunks(
  chunks: DocumentChunk[],
  llm: LlmAdapter,
  options: ExtractionOptions,
  signal?: AbortSignal,
  hooks: ExtractionHooks = {},
): Promise<ExtractedCandidate[]> {
  let failureCount = 0;
  let firstFailure: unknown;
  const results = await mapWithConcurrency(
    chunks,
    options.concurrency,
    async (chunk) => {
      signal?.throwIfAborted();
      hooks.onLlmCall?.();
      try {
        const response = await llm.generateStructured<unknown>({
          system: options.systemPrompt
            ?? createExtractionSystemPrompt(options.requireExamples, options.accuracy),
          prompt: createExtractionPrompt(chunk, options.prompt),
          schema: createCandidateSchema(options.requireExamples, options.accuracy),
          ...(signal === undefined ? {} : { signal }),
        });
        const candidates = validateCandidateResponse(response, options.requireExamples);
        hooks.onChunkProcessed?.(candidates.length);
        return candidates.map((candidate) => ({
          ...candidate,
          documentId: chunk.documentId,
          chunkIndex: chunk.chunkIndex,
        }));
      } catch (error) {
        if (signal?.aborted === true) {
          throw error;
        }
        firstFailure ??= error;
        failureCount += 1;
        hooks.onChunkProcessed?.(0);
        return [];
      }
    },
  );

  if (chunks.length > 0 && failureCount === chunks.length) {
    throw new LlmAdapterError("Extraction failed for every chunk", {
      cause: firstFailure,
    });
  }
  return results.flat();
}

/** Builds the user prompt for one document chunk. */
function createExtractionPrompt(
  chunk: DocumentChunk,
  prompt: ExtractionPrompt | undefined,
): string {
  if (typeof prompt === "function") {
    return prompt(chunk);
  }
  if (prompt !== undefined) {
    return prompt;
  }
  return JSON.stringify({ text: chunk.text });
}

/** Builds a prompt whose requirements match the response validator. */
function createExtractionSystemPrompt(
  requireExamples: boolean,
  accuracy: ExtractionAccuracy,
): string {
  return [
    "Extract ontology schema candidates from the document fragment.",
    "Return types, not individual instances. Use NodeType for concepts and RelType for relations.",
    createAccuracyInstruction(accuracy),
    "For NodeType, extract typed attribute definitions, category, primary key, label attribute, and visual metadata only when supported by the text.",
    "For RelType include domain and range labels, typed attribute definitions, and source/target cardinality when supported by the text.",
    "Never invent identifiers, colors, constraints, or cardinalities. Keep definitions concise.",
    ...(requireExamples ? ["Include one or two grounding examples for every candidate."] : []),
  ].join(" ");
}

/** Builds a structured-output schema consistent with the examples option. */
function createCandidateSchema(
  requireExamples: boolean,
  accuracy: ExtractionAccuracy,
): JsonSchema {
  return {
    type: "object",
    additionalProperties: false,
    required: ["candidates"],
    properties: {
      candidates: {
        type: "array",
        maxItems: maxCandidatesPerChunk(accuracy),
        items: {
          type: "object",
          additionalProperties: false,
          required: [
            "label",
            "definition",
            "kind",
            ...(requireExamples ? ["examples"] : []),
          ],
          properties: {
            label: { type: "string", minLength: 1 },
            definition: { type: "string", minLength: 1 },
            kind: { type: "string", enum: ["NodeType", "RelType"] },
            domain: { type: "string" },
            range: { type: "string" },
            attributes: { type: "array", items: { type: "string" } },
            attributeDefinitions: {
              type: "array",
              items: {
                type: "object",
                additionalProperties: false,
                required: ["name"],
                properties: {
                  name: { type: "string", minLength: 1 },
                  type: {
                    type: "string",
                    enum: ["STRING", "NUMBER", "FLOAT", "BOOLEAN", "DATE", "DATETIME"],
                  },
                  label: { type: "string", minLength: 1 },
                  description: { type: "string" },
                  indexed: { type: "boolean" },
                  required: { type: "boolean" },
                  restricted: { type: "boolean" },
                },
              },
            },
            category: { type: "string", minLength: 1 },
            primaryKeyAttribute: { type: "string", minLength: 1 },
            labelAttribute: { type: "string", minLength: 1 },
            fromCardinality: { type: "string", enum: ["0", "1", "N"] },
            toCardinality: { type: "string", enum: ["0", "1", "N"] },
            visual: {
              type: "object",
              additionalProperties: false,
              properties: {
                icon: { type: "string", minLength: 1 },
                backColor: { type: "string", pattern: "^#[0-9A-Fa-f]{6}$" },
                textColor: { type: "string", pattern: "^#[0-9A-Fa-f]{6}$" },
              },
            },
            examples: {
              type: "array",
              items: { type: "string", minLength: 1 },
              minItems: requireExamples ? 1 : 0,
              maxItems: 2,
            },
          },
        },
      },
    },
  };
}

/** Describes how selective the model should be before downstream canonicalization. */
function createAccuracyInstruction(accuracy: ExtractionAccuracy): string {
  if (accuracy === "low") {
    return "Use broad recall: include central schema types plus plausible secondary ontology candidates, but still exclude one-off instances.";
  }
  if (accuracy === "high") {
    return "Use strict importance filtering: return only the most important concepts and relations needed to understand the fragment; exclude synonyms, local details, minor attributes, and incidental mentions.";
  }
  return "Use balanced importance filtering: return candidates that are clearly central, recurring, or structurally useful for the ontology.";
}

/** Caps candidate volume per chunk according to the selected recall/precision trade-off. */
function maxCandidatesPerChunk(accuracy: ExtractionAccuracy): number {
  if (accuracy === "low") {
    return 12;
  }
  if (accuracy === "high") {
    return 4;
  }
  return 7;
}

/** Validates and normalizes the structured extraction response. */
function validateCandidateResponse(
  response: unknown,
  requireExamples: boolean,
): Candidate[] {
  if (!isRecord(response) || !Array.isArray(response.candidates)) {
    throw new SchemaValidationError("Extraction response must contain a candidates array");
  }
  return response.candidates.map((value, index) =>
    validateCandidate(value, index, requireExamples),
  );
}

/** Validates one candidate and strips unsupported or empty values. */
function validateCandidate(
  value: unknown,
  index: number,
  requireExamples: boolean,
): Candidate {
  if (!isRecord(value)) {
    throw new SchemaValidationError(`Candidate ${index} must be an object`);
  }
  const label = readRequiredString(value.label, `candidates[${index}].label`);
  const definition = readRequiredString(
    value.definition,
    `candidates[${index}].definition`,
  );
  if (value.kind !== "NodeType" && value.kind !== "RelType") {
    throw new SchemaValidationError(`candidates[${index}].kind is invalid`);
  }
  const examples = readOptionalStrings(
    value.examples,
    `candidates[${index}].examples`,
    2,
  );
  if (requireExamples && (examples === undefined || examples.length === 0)) {
    throw new SchemaValidationError(`candidates[${index}].examples is required`);
  }
  const attributes = readOptionalStrings(
    value.attributes,
    `candidates[${index}].attributes`,
  );
  const domain = readOptionalString(value.domain, `candidates[${index}].domain`);
  const range = readOptionalString(value.range, `candidates[${index}].range`);
  const metadata = readCandidateMetadata(value, index, attributes);
  if (value.kind === "RelType" && (domain === undefined || range === undefined)) {
    throw new SchemaValidationError(`RelType candidate ${index} requires domain and range`);
  }
  return {
    label,
    definition,
    kind: value.kind,
    ...(domain === undefined ? {} : { domain }),
    ...(range === undefined ? {} : { range }),
    ...(attributes === undefined ? {} : { attributes }),
    ...metadata,
    ...(examples === undefined ? {} : { examples }),
  };
}

/** Reads optional rich metadata and validates its internal attribute references. */
function readCandidateMetadata(
  value: Record<string, unknown>,
  index: number,
  attributes: string[] | undefined,
): Partial<Candidate> {
  const attributeDefinitions = readAttributeDefinitions(
    value.attributeDefinitions,
    `candidates[${index}].attributeDefinitions`,
  );
  const category = readOptionalString(value.category, `candidates[${index}].category`);
  const primaryKeyAttribute = readOptionalString(
    value.primaryKeyAttribute,
    `candidates[${index}].primaryKeyAttribute`,
  );
  const labelAttribute = readOptionalString(
    value.labelAttribute,
    `candidates[${index}].labelAttribute`,
  );
  const fromCardinality = readCardinality(
    value.fromCardinality,
    `candidates[${index}].fromCardinality`,
  );
  const toCardinality = readCardinality(
    value.toCardinality,
    `candidates[${index}].toCardinality`,
  );
  const visual = readVisual(value.visual, `candidates[${index}].visual`);
  validateAttributeReferences(
    attributes,
    attributeDefinitions,
    { primaryKeyAttribute, labelAttribute },
    index,
  );
  return {
    ...(attributeDefinitions === undefined ? {} : { attributeDefinitions }),
    ...(category === undefined ? {} : { category }),
    ...(primaryKeyAttribute === undefined ? {} : { primaryKeyAttribute }),
    ...(labelAttribute === undefined ? {} : { labelAttribute }),
    ...(fromCardinality === undefined ? {} : { fromCardinality }),
    ...(toCardinality === undefined ? {} : { toCardinality }),
    ...(visual === undefined ? {} : { visual }),
  };
}

/** Ensures primary and display attributes identify a declared attribute. */
function validateAttributeReferences(
  attributes: string[] | undefined,
  definitions: AttributeDefinition[] | undefined,
  references: Record<"primaryKeyAttribute" | "labelAttribute", string | undefined>,
  index: number,
): void {
  const names = new Set([
    ...(attributes ?? []),
    ...(definitions ?? []).map(({ name }) => name),
  ]);
  for (const [field, reference] of Object.entries(references)) {
    if (reference !== undefined && !names.has(reference)) {
      throw new SchemaValidationError(
        `candidates[${index}].${field} must reference a declared attribute`,
      );
    }
  }
}

const attributeValueTypes = new Set<AttributeValueType>([
  "STRING", "NUMBER", "FLOAT", "BOOLEAN", "DATE", "DATETIME",
]);

/** Reads structured attribute metadata and rejects duplicate names. */
function readAttributeDefinitions(
  value: unknown,
  path: string,
): AttributeDefinition[] | undefined {
  if (value === undefined) {
    return undefined;
  }
  if (!Array.isArray(value)) {
    throw new SchemaValidationError(`${path} must be an array`);
  }
  const definitions = value.map((item, index) => {
    if (!isRecord(item)) {
      throw new SchemaValidationError(`${path}[${index}] must be an object`);
    }
    const type = item.type;
    if (type !== undefined && !attributeValueTypes.has(type as AttributeValueType)) {
      throw new SchemaValidationError(`${path}[${index}].type is invalid`);
    }
    const definition: AttributeDefinition = {
      name: readRequiredString(item.name, `${path}[${index}].name`),
      ...(type === undefined ? {} : { type: type as AttributeValueType }),
    };
    for (const field of ["label", "description"] as const) {
      const text = readOptionalString(item[field], `${path}[${index}].${field}`);
      if (text !== undefined) definition[field] = text;
    }
    for (const field of ["indexed", "required", "restricted"] as const) {
      const flag = item[field];
      if (flag !== undefined && typeof flag !== "boolean") {
        throw new SchemaValidationError(`${path}[${index}].${field} must be boolean`);
      }
      if (flag !== undefined) definition[field] = flag;
    }
    return definition;
  });
  const names = definitions.map(({ name }) => name);
  if (new Set(names).size !== names.length) {
    throw new SchemaValidationError(`${path} contains duplicate names`);
  }
  return definitions.length === 0 ? undefined : definitions;
}

/** Reads one optional relationship cardinality. */
function readCardinality(value: unknown, path: string): Cardinality | undefined {
  if (value === undefined) return undefined;
  if (value !== "0" && value !== "1" && value !== "N") {
    throw new SchemaValidationError(`${path} is invalid`);
  }
  return value;
}

/** Reads optional visual metadata with strict six-digit hex colors. */
function readVisual(
  value: unknown,
  path: string,
): Candidate["visual"] | undefined {
  if (value === undefined) return undefined;
  if (!isRecord(value)) {
    throw new SchemaValidationError(`${path} must be an object`);
  }
  const visual: NonNullable<Candidate["visual"]> = {};
  const icon = readOptionalString(value.icon, `${path}.icon`);
  if (icon !== undefined) visual.icon = icon;
  for (const field of ["backColor", "textColor"] as const) {
    const color = readOptionalString(value[field], `${path}.${field}`);
    if (color !== undefined && !/^#[\dA-Fa-f]{6}$/.test(color)) {
      throw new SchemaValidationError(`${path}.${field} must be a six-digit hex color`);
    }
    if (color !== undefined) visual[field] = color.toUpperCase();
  }
  return Object.keys(visual).length === 0 ? undefined : visual;
}

/** Runs indexed work with at most limit promises in flight. */
async function mapWithConcurrency<Input, Output>(
  items: Input[],
  limit: number,
  operation: (item: Input) => Promise<Output>,
): Promise<Output[]> {
  const results = new Array<Output>(items.length);
  let nextIndex = 0;

  /** Claims indices synchronously and processes them until the queue is empty. */
  async function worker(): Promise<void> {
    while (nextIndex < items.length) {
      const index = nextIndex;
      nextIndex += 1;
      const item = items[index];
      if (item !== undefined) {
        results[index] = await operation(item);
      }
    }
  }

  const workerCount = Math.min(limit, items.length);
  await Promise.all(Array.from({ length: workerCount }, () => worker()));
  return results;
}

/** Reads and trims a required string value. */
function readRequiredString(value: unknown, path: string): string {
  if (typeof value !== "string" || value.trim().length === 0) {
    throw new SchemaValidationError(`${path} must be a non-empty string`);
  }
  return value.trim();
}

/** Reads and trims an optional string value. */
function readOptionalString(value: unknown, path: string): string | undefined {
  if (value === undefined) {
    return undefined;
  }
  return readRequiredString(value, path);
}

/** Reads an optional string array and removes duplicates and empty values. */
function readOptionalStrings(
  value: unknown,
  path: string,
  limit = Number.POSITIVE_INFINITY,
): string[] | undefined {
  if (value === undefined) {
    return undefined;
  }
  if (!Array.isArray(value) || value.some((item) => typeof item !== "string")) {
    throw new SchemaValidationError(`${path} must be an array of strings`);
  }
  const strings = [...new Set(value.map((item) => String(item).trim()))].filter(Boolean);
  return strings.length === 0 ? undefined : strings.slice(0, limit);
}

/** Narrows unknown JSON values to records. */
function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}