// Generated by GitHub Copilot

import AxeBuilder from "@axe-core/playwright";
import { expect, test } from "@playwright/test";
import { copyFile, mkdtemp, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { pathToFileURL } from "node:url";
import { PNG } from "pngjs";

import type { Ontology } from "ontology-extractor";

import { renderReport } from "../src/report.js";

const ontology: Ontology = {
  types: [
    {
      id: "service",
      label: "Service",
      definition: "A deployable software capability.",
      kind: "NodeType",
      attributes: ["name"],
      aliases: [],
      supportCount: 3,
      provenance: [],
    },
    {
      id: "api",
      label: "API",
      definition: "A programmatic interface.",
      kind: "NodeType",
      attributes: ["version"],
      aliases: [],
      supportCount: 2,
      provenance: [],
    },
    {
      id: "exposes",
      label: "exposes",
      definition: "A service makes an API available.",
      kind: "RelType",
      domain: "service",
      range: "api",
      attributes: [],
      aliases: [],
      supportCount: 2,
      provenance: [],
    },
  ],
  generatedAt: 1,
  stats: {
    documentCount: 3,
    candidateCount: 7,
    typeCount: 3,
    droppedBelowThreshold: 0,
  },
};

/** Creates a complete offline report directory for browser validation. */
async function createReport(): Promise<string> {
  const directory = await mkdtemp(join(tmpdir(), "ontology-report-e2e-"));
  await Promise.all([
    writeFile(join(directory, "index.html"), renderReport(ontology, "E2E ontology"), "utf8"),
    copyFile(new URL("../dist/report-client.js", import.meta.url), join(directory, "report-client.js")),
  ]);
  return pathToFileURL(join(directory, "index.html")).href;
}

test("renders an interactive, accessible graph without network dependencies", async ({ page }, testInfo) => {
  const consoleErrors: string[] = [];
  page.on("console", (message) => {
    if (message.type() === "error") {
      consoleErrors.push(message.text());
    }
  });
  page.on("pageerror", (error) => consoleErrors.push(error.message));

  await page.goto(await createReport());
  await expect(page.locator("#graph-status")).toHaveText("2 types and 1 relations visible");
  await expect(page.locator("#ontology-graph canvas")).toHaveCount(3);

  const graphScreenshot = await page.locator("#ontology-graph").screenshot();
  const graphImage = PNG.sync.read(graphScreenshot);
  let coloredPixels = 0;
  for (let index = 0; index < graphImage.data.length; index += 4) {
    const red = graphImage.data[index] ?? 255;
    const green = graphImage.data[index + 1] ?? 255;
    const blue = graphImage.data[index + 2] ?? 255;
    const alpha = graphImage.data[index + 3] ?? 0;
    if (alpha > 0 && (red < 245 || green < 245 || blue < 245)) {
      coloredPixels += 1;
    }
  }
  expect(coloredPixels).toBeGreaterThan(100);

  await page.locator("#graph-search").fill("API");
  await expect(page.locator("#graph-status")).toHaveText("1 types and 0 relations visible");
  await page.locator("#reset-graph").click();
  await expect(page.locator("#graph-status")).toHaveText("2 types and 1 relations visible");

  const accessibility = await new AxeBuilder({ page }).analyze();
  expect(accessibility.violations).toEqual([]);
  expect(consoleErrors).toEqual([]);
  await page.screenshot({ path: testInfo.outputPath("desktop-report.png"), fullPage: true });
});

test("fits mobile without horizontal overflow", async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto(await createReport());
  await expect(page.locator("#graph-status")).toContainText("2 types");

  const dimensions = await page.evaluate(() => ({
    scrollWidth: document.documentElement.scrollWidth,
    clientWidth: document.documentElement.clientWidth,
    graphHeight: document.getElementById("ontology-graph")?.getBoundingClientRect().height ?? 0,
  }));
  expect(dimensions.scrollWidth).toBeLessThanOrEqual(dimensions.clientWidth);
  expect(dimensions.graphHeight).toBeGreaterThanOrEqual(420);
  await page.screenshot({ path: testInfo.outputPath("mobile-report.png"), fullPage: true });
});