// Generated by GitHub Copilot

import AxeBuilder from "@axe-core/playwright";
import { expect, type Page, test } from "@playwright/test";

/** Clicks one relative position on the Cytoscape canvas. */
async function clickGraphPosition(page: Page, xRatio: number, yRatio: number): Promise<void> {
  const graph = page.locator("#ontology-graph canvas").first();
  const box = await graph.boundingBox();
  if (box === null) {
    throw new Error("Graph canvas is not visible");
  }
  await graph.click({ position: { x: box.width * xRatio, y: box.height * yRatio }, force: true });
}

test("uploads documents and renders graph plus JSON", async ({ page }, testInfo) => {
  const errors: string[] = [];
  page.on("console", (message) => {
    if (message.type() === "error") {
      errors.push(message.text());
    }
  });
  page.on("pageerror", (error) => errors.push(error.message));

  await page.goto("/");
  await expect(page.locator("#provider-summary")).toContainText("mock");
  await page.locator("#documents").setInputFiles([
    {
      name: "architecture.md",
      mimeType: "text/markdown",
      buffer: Buffer.from("The billing service exposes an API and uses a database."),
    },
  ]);
  await expect(page.locator("#extract")).toBeEnabled();
  await page.locator("#extract").click();

  await expect(page.locator("#status")).toContainText("Ontology ready", { timeout: 10_000 });
  await expect(page.locator("#ontology-graph canvas")).toHaveCount(3);
  await expect(page.locator("#results")).toBeVisible();
  await expect(page.locator("#empty")).toBeHidden();
  await expect(page.getByText("Your graph and JSON will appear here.")).toBeHidden();

  await clickGraphPosition(page, 0.4, 0.4);
  await expect(page.locator("#graph-details")).toContainText("RelType");
  await expect(page.locator("#graph-details")).toContainText("References");

  await clickGraphPosition(page, 0.7, 0.7);
  await expect(page.locator("#graph-details")).toContainText("NodeType");
  await expect(page.locator("#graph-details")).toContainText("Name: STRING");
  await expect(page.locator("#graph-details")).toContainText("Provenance");

  await page.locator("#json-tab").click();
  await expect(page.locator("#empty")).toBeHidden();
  await expect(page.locator("#json-output")).toContainText('"types"');
  await expect(page.locator("#json-output")).toContainText('"Service"');
  await page.locator("#graph-tab").click();

  const accessibility = await new AxeBuilder({ page }).analyze();
  expect(accessibility.violations).toEqual([]);
  expect(errors).toEqual([]);
  await page.screenshot({ path: testInfo.outputPath("web-desktop.png"), fullPage: true });
});

test("stays usable on a mobile viewport", async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto("/");
  await expect(page.locator("#upload-title")).toBeVisible();

  const dimensions = await page.evaluate(() => ({
    scrollWidth: document.documentElement.scrollWidth,
    clientWidth: document.documentElement.clientWidth,
  }));
  expect(dimensions.scrollWidth).toBeLessThanOrEqual(dimensions.clientWidth);
  await page.screenshot({ path: testInfo.outputPath("web-mobile.png"), fullPage: true });
});