// Generated by GitHub Copilot

import { StoreConflictError } from "../errors.js";
import type {
  CandidateStore,
  ExtractedCandidate,
  StoredCandidate,
} from "../types.js";

/** In-memory candidate persistence with document-level append semantics. */
export class InMemoryCandidateStore implements CandidateStore {
  readonly #documents = new Set<string>();
  readonly #candidatesByDocument = new Map<string, StoredCandidate[]>();

  /** Reports whether a document has already been processed. */
  async hasDocument(documentId: string): Promise<boolean> {
    return this.#documents.has(documentId);
  }

  /** Atomically records a document and normalized copies of its candidates. */
  async appendCandidates(
    documentId: string,
    candidates: ExtractedCandidate[],
  ): Promise<void> {
    if (this.#documents.has(documentId)) {
      throw new StoreConflictError(`Document already exists: ${documentId}`);
    }

    if (candidates.some((candidate) => candidate.documentId !== documentId)) {
      throw new StoreConflictError(
        `Candidate provenance does not match document: ${documentId}`,
      );
    }

    const stored = candidates.map((candidate) => cloneStoredCandidate(candidate));
    this.#candidatesByDocument.set(documentId, stored);
    this.#documents.add(documentId);
  }

  /** Returns document ids in stable lexical order. */
  async getDocumentIds(): Promise<string[]> {
    return [...this.#documents].sort((left, right) => left.localeCompare(right));
  }

  /** Returns detached candidate values so callers cannot mutate store state. */
  async getAllCandidates(): Promise<StoredCandidate[]> {
    return [...this.#candidatesByDocument.values()]
      .flat()
      .map((candidate) => cloneStoredCandidate(candidate));
  }

  /** Removes a document and all candidates associated with it. */
  async removeDocument(documentId: string): Promise<void> {
    this.#candidatesByDocument.delete(documentId);
    this.#documents.delete(documentId);
  }

  /** Clears all in-memory state. */
  async clear(): Promise<void> {
    this.#candidatesByDocument.clear();
    this.#documents.clear();
  }
}

/** Creates a detached stored candidate with one unit of chunk support. */
function cloneStoredCandidate(
  candidate: ExtractedCandidate | StoredCandidate,
): StoredCandidate {
  return {
    ...candidate,
    ...(candidate.attributes === undefined
      ? {}
      : { attributes: [...candidate.attributes] }),
    ...(candidate.attributeDefinitions === undefined
      ? {}
      : { attributeDefinitions: candidate.attributeDefinitions.map((item) => ({ ...item })) }),
    ...(candidate.visual === undefined ? {} : { visual: { ...candidate.visual } }),
    ...(candidate.examples === undefined
      ? {}
      : { examples: [...candidate.examples] }),
    supportCount: "supportCount" in candidate ? candidate.supportCount : 1,
  };
}